function [model, actuation, geometry, definition, units] = springDamperFixture(preload)
%SPRINGDAMPERFIXTURE Ideal test parameters only, not a vehicle setup.
if nargin < 1, preload = 0.02; end
[geometry,actuation] = actuationFixture();
definition = struct("configuration","COILOVER", ...
    "spring",struct("modelType","LINEAR_COMPRESSION","rate",30000, ...
    "freeLength",0.20,"preloadCompression",preload), ...
    "damper",struct("modelType","LINEAR_ASYMMETRIC", ...
    "compressionCoefficient",1500,"reboundCoefficient",2500), ...
    "metadata",struct("sourceKind","ASSUMED","sourceNote","Independent test parameters only"));
units = struct("length","m","springRate","N/m","dampingCoefficient","N*s/m","velocity","m/s");
model = fsd.model.createSpringDamperModel(actuation,definition,units);
end
