function analysis = analyzeActuationCore(actuation, result)
%ANALYZEACTUATIONCORE Build a scalar analysis from validated inputs.

analysis = struct( ...
    "schemaVersion", "0.7.0", ...
    "kind", "ActuationAnalysis", ...
    "actuationIdentity", actuation.identity, ...
    "cornerId", string(actuation.cornerId), ...
    "actuationType", string(actuation.actuationType), ...
    "attachmentBody", string(actuation.suspensionAttachment.body), ...
    "sourceResultKind", string(result.sourceResultKind), ...
    "wheelTravel_m", result.sourceAchievedWheelTravel_m, ...
    "converged", logical(result.converged), ...
    "actuationStatus", string(result.status), ...
    "failureReason", string(result.failureReason), ...
    "rockerAngle_rad", result.rockerAngle_rad, ...
    "damperLength_m", result.damperLength_m, ...
    "damperCompression_m", result.damperCompression_m, ...
    "actuationRodLengthResidual_m", ...
        result.actuationRodLengthResidual_m, ...
    "conditioning", result.conditioning, ...
    "isIllConditioned", logical(result.isIllConditioned));
end
