function analysis = analyzeCornerStateCore(geometry, result)
%ANALYZECORNERSTATECORE Analyze one already validated solver result.

analysis = emptyAnalysis(geometry, result);
if ~result.converged
    return
end

steeringAxis = fsd.analysis.steeringAxisFromPoints( ...
    result.state.lbj_m, result.state.ubj_m);
analysis.wheelTravel_m = double(result.achievedWheelTravel_m);
analysis.camber_rad = fsd.analysis.camberFromWheelAxis( ...
    result.wheelAxis, geometry.cornerId);
analysis.toe_rad = fsd.analysis.toeFromWheelAxis( ...
    result.wheelAxis, geometry.cornerId);
analysis.caster_rad = fsd.analysis.casterFromSteeringAxis(steeringAxis);
analysis.kingpinInclination_rad = fsd.analysis.kingpinInclination( ...
    steeringAxis, geometry.cornerId);
analysis.steeringAxis = steeringAxis;
end

function analysis = emptyAnalysis(geometry, result)
analysis = struct( ...
    "schemaVersion", "0.3.0", ...
    "kind", "CornerKinematicAnalysis", ...
    "geometryIdentity", result.geometryIdentity, ...
    "cornerId", geometry.cornerId, ...
    "requestedWheelTravel_m", double(result.requestedWheelTravel_m), ...
    "wheelTravel_m", NaN, ...
    "camber_rad", NaN, ...
    "toe_rad", NaN, ...
    "caster_rad", NaN, ...
    "kingpinInclination_rad", NaN, ...
    "steeringAxis", [NaN, NaN, NaN], ...
    "converged", logical(result.converged), ...
    "status", string(result.status), ...
    "failureReason", string(result.failureReason), ...
    "solverDiagnostics", result.diagnostics);
end
