function analysis = analyzeAxleStateCore(axle, leftResult, rightResult, ...
    requestedWheelTravel_m, leftRadius_m, rightRadius_m, axleIdentity)
%ANALYZEAXLESTATECORE Analyze one already validated axle state.

timer = tic;
left = analyzeSide(axle.leftGeometry, leftResult, leftRadius_m);
right = analyzeSide(axle.rightGeometry, rightResult, rightRadius_m);
rollCenter = intersectConstructionLines(left, right);
[roadReferenceZ_m, heightStatus] = roadReference(left, right, rollCenter);
rollCenterHeight_m = NaN;
if string(rollCenter.status) == "FINITE" && heightStatus == "DEFINED"
    rollCenterHeight_m = rollCenter.z_m - roadReferenceZ_m;
end
analysis = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "AxleRollCenterAnalysis", ...
    "axleIdentity", axleIdentity, ...
    "axleId", string(axle.axleId), ...
    "requestedWheelTravel_m", requestedWheelTravel_m, ...
    "status", string(rollCenter.status), ...
    "rollCenterY_m", double(rollCenter.y_m), ...
    "rollCenterZ_m", double(rollCenter.z_m), ...
    "rollCenterHeight_m", double(rollCenterHeight_m), ...
    "rollCenterHeightStatus", heightStatus, ...
    "roadReferenceZ_m", double(roadReferenceZ_m), ...
    "rollCenterHomogeneousPoint", double(rollCenter.homogeneousPoint), ...
    "rollCenterDirection_yz", double(rollCenter.direction_yz), ...
    "rollCenterConditioning", double(rollCenter.conditioning), ...
    "rollCenterIllConditioned", logical(rollCenter.isIllConditioned), ...
    "diagnostic", string(rollCenter.diagnostic), ...
    "left", left, ...
    "right", right, ...
    "analysisElapsedTime_s", toc(timer));
end

function side = analyzeSide(geometry, result, radius_m)
instantCenter = frontViewInstantCenterCore(geometry, result);
contact = geometricWheelContactCore(geometry, result, radius_m);
if ismember(string(instantCenter.status), ["FINITE", "INFINITE"]) && ...
        string(contact.status) == "FINITE"
    constructionLine = fsd.geometry.lineYZFromHomogeneousPoints( ...
        [contact.point_m(2:3), 1], instantCenter.homogeneousPoint);
else
    constructionLine = undefinedLine( ...
        "A valid projective instant center and finite contact are required.");
end
side = struct( ...
    "cornerId", string(geometry.cornerId), ...
    "instantCenter", instantCenter, ...
    "geometricContact", contact, ...
    "rollCenterConstructionLine", constructionLine);
end

function line = undefinedLine(diagnostic)
line = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "LineYZ", ...
    "status", "DEGENERATE", ...
    "homogeneousLine", [NaN, NaN, NaN], ...
    "coefficients", [NaN, NaN, NaN], ...
    "point_yz_m", [NaN, NaN], ...
    "direction_yz", [NaN, NaN], ...
    "diagnostic", diagnostic);
end

function rollCenter = intersectConstructionLines(left, right)
if string(left.rollCenterConstructionLine.status) ~= "FINITE" || ...
        string(right.rollCenterConstructionLine.status) ~= "FINITE"
    rollCenter = undefinedIntersection( ...
        "A required side construction is undefined.");
    return
end
rollCenter = fsd.geometry.intersectLinesYZ( ...
    left.rollCenterConstructionLine, ...
    right.rollCenterConstructionLine);
end

function [roadZ_m, status] = roadReference(left, right, rollCenter)
roadZ_m = NaN;
if string(left.geometricContact.status) ~= "FINITE" || ...
        string(right.geometricContact.status) ~= "FINITE"
    status = "CONTACT_UNDEFINED";
    return
end
leftZ_m = left.geometricContact.point_m(3);
rightZ_m = right.geometricContact.point_m(3);
tolerances = fsd.model.numericTolerances();
tolerance_m = tolerances.AbsTol_m + tolerances.RelTol * ...
    max([abs(leftZ_m), abs(rightZ_m), 1]);
if abs(leftZ_m - rightZ_m) > tolerance_m
    status = "CONTACT_LEVEL_MISMATCH";
    return
end
roadZ_m = 0.5 * (leftZ_m + rightZ_m);
switch string(rollCenter.status)
    case "FINITE"
        status = "DEFINED";
    case "INFINITE"
        status = "ROLL_CENTER_INFINITE";
    otherwise
        status = "ROLL_CENTER_UNDEFINED";
end
end

function result = undefinedIntersection(diagnostic)
result = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "ProjectiveIntersectionYZ", ...
    "status", "DEGENERATE", ...
    "homogeneousPoint", [NaN, NaN, NaN], ...
    "point_yz_m", [NaN, NaN], ...
    "y_m", NaN, ...
    "z_m", NaN, ...
    "direction_yz", [NaN, NaN], ...
    "conditioning", NaN, ...
    "isIllConditioned", false, ...
    "diagnostic", diagnostic);
end
