function analysis = analyzeAxleRollCore(axle, result, reference, ...
        leftRadius_m, rightRadius_m, axleIdentity)
%ANALYZEAXLEROLLCORE Analyze one already validated body-roll result.

timer = tic;
if ~result.converged
    analysis = failedAnalysis(axle, result, axleIdentity, toc(timer));
    return
end

travel = result.axleTravelResult;
base = analyzeAxleStateCore(axle, travel.leftResult, travel.rightResult, ...
    travel.requestedWheelTravel_m, leftRadius_m, rightRadius_m, axleIdentity);
leftAxis = travel.leftResult.wheelAxis;
rightAxis = travel.rightResult.wheelAxis;
chassisCamber = [ ...
    fsd.analysis.camberFromWheelAxis(leftAxis, axle.leftGeometry.cornerId), ...
    fsd.analysis.camberFromWheelAxis(rightAxis, axle.rightGeometry.cornerId)];
roadCamber = [ ...
    fsd.analysis.roadRelativeCamber(leftAxis, axle.leftGeometry.cornerId, ...
        result.requestedBodyRollAngle_rad), ...
    fsd.analysis.roadRelativeCamber(rightAxis, axle.rightGeometry.cornerId, ...
        result.requestedBodyRollAngle_rad)];
toe = [ ...
    fsd.analysis.toeFromWheelAxis(leftAxis, axle.leftGeometry.cornerId), ...
    fsd.analysis.toeFromWheelAxis(rightAxis, axle.rightGeometry.cornerId)];
leftCenter = travel.leftResult.state.wheelCenter_m;
rightCenter = travel.rightResult.state.wheelCenter_m;
wheelCenterTrack_m = rightCenter(2) - leftCenter(2);
contactVector = result.rightGeometricContact.point_m - ...
    result.leftGeometricContact.point_m;
contactTrack_m = dot(result.roadFrame.direction_yz, contactVector(2:3));

roadHeight_m = NaN;
roadHeightStatus = rollCenterHeightStatus(base.status);
if string(base.status) == "FINITE"
    roadHeight_m = fsd.geometry.signedDistanceToRoadLine( ...
        [base.rollCenterY_m, base.rollCenterZ_m], result.targetRoadLine);
    roadHeightStatus = "DEFINED";
end

analysis = struct( ...
    "schemaVersion", "0.6.0", ...
    "kind", "AxleRollAnalysis", ...
    "axleIdentity", axleIdentity, ...
    "axleId", string(axle.axleId), ...
    "bodyRollAngle_rad", result.requestedBodyRollAngle_rad, ...
    "axleHeave_m", result.requestedAxleHeave_m, ...
    "wheelTravel_m", result.wheelTravel_m, ...
    "wheelTravelDifferential_m", result.wheelTravelDifferential_m, ...
    "converged", true, ...
    "kinematicStatus", string(result.status), ...
    "status", "CONVERGED", ...
    "failureReason", "", ...
    "chassisCamber_rad", chassisCamber, ...
    "roadCamber_rad", roadCamber, ...
    "toe_rad", toe, ...
    "leftInstantCenterY_m", base.left.instantCenter.instantCenterY_m, ...
    "leftInstantCenterZ_m", base.left.instantCenter.instantCenterZ_m, ...
    "rightInstantCenterY_m", base.right.instantCenter.instantCenterY_m, ...
    "rightInstantCenterZ_m", base.right.instantCenter.instantCenterZ_m, ...
    "rollCenterStatus", string(base.status), ...
    "rollCenterY_m", base.rollCenterY_m, ...
    "rollCenterZ_m", base.rollCenterZ_m, ...
    "rollCenterHeight_m", base.rollCenterHeight_m, ...
    "rollCenterHeightStatus", string(base.rollCenterHeightStatus), ...
    "rollCenterRoadHeight_m", roadHeight_m, ...
    "rollCenterRoadHeightStatus", roadHeightStatus, ...
    "wheelCenterTrack_m", wheelCenterTrack_m, ...
    "geometricContactTrack_m", contactTrack_m, ...
    "wheelCenterTrackChange_m", wheelCenterTrack_m - ...
        reference.wheelCenterTrack_m, ...
    "geometricContactTrackChange_m", contactTrack_m - ...
        reference.geometricContactTrack_m, ...
    "reference", reference, ...
    "roadLine", result.targetRoadLine, ...
    "axleStateAnalysis", base, ...
    "left", base.left, ...
    "right", base.right, ...
    "analysisElapsedTime_s", toc(timer));
end

function status = rollCenterHeightStatus(rollCenterStatus)
switch string(rollCenterStatus)
    case "INFINITE"
        status = "ROLL_CENTER_INFINITE";
    case "COINCIDENT"
        status = "ROLL_CENTER_COINCIDENT";
    otherwise
        status = "ROLL_CENTER_UNDEFINED";
end
end

function analysis = failedAnalysis(axle, result, axleIdentity, elapsed_s)
diagnostic = "Body-roll kinematics did not converge; analysis metrics are undefined.";
analysis = struct( ...
    "schemaVersion", "0.6.0", "kind", "AxleRollAnalysis", ...
    "axleIdentity", axleIdentity, "axleId", string(axle.axleId), ...
    "bodyRollAngle_rad", result.requestedBodyRollAngle_rad, ...
    "axleHeave_m", result.requestedAxleHeave_m, ...
    "wheelTravel_m", [NaN, NaN], "wheelTravelDifferential_m", NaN, ...
    "converged", false, "kinematicStatus", string(result.status), ...
    "status", "KINEMATICS_NOT_CONVERGED", ...
    "failureReason", string(result.failureReason), ...
    "chassisCamber_rad", [NaN, NaN], ...
    "roadCamber_rad", [NaN, NaN], "toe_rad", [NaN, NaN], ...
    "leftInstantCenterY_m", NaN, "leftInstantCenterZ_m", NaN, ...
    "rightInstantCenterY_m", NaN, "rightInstantCenterZ_m", NaN, ...
    "rollCenterStatus", "KINEMATICS_NOT_CONVERGED", ...
    "rollCenterY_m", NaN, "rollCenterZ_m", NaN, ...
    "rollCenterHeight_m", NaN, ...
    "rollCenterHeightStatus", "KINEMATICS_NOT_CONVERGED", ...
    "rollCenterRoadHeight_m", NaN, ...
    "rollCenterRoadHeightStatus", "KINEMATICS_NOT_CONVERGED", ...
    "wheelCenterTrack_m", NaN, "geometricContactTrack_m", NaN, ...
    "wheelCenterTrackChange_m", NaN, ...
    "geometricContactTrackChange_m", NaN, ...
    "reference", emptyReference(), "roadLine", struct(), ...
    "axleStateAnalysis", struct(), "left", struct(), "right", struct(), ...
    "analysisElapsedTime_s", elapsed_s);
if strlength(analysis.failureReason) == 0
    analysis.failureReason = diagnostic;
end
end

function value = emptyReference()
value = struct("bodyRollAngle_rad", 0, "axleHeave_m", 0, ...
    "wheelCenterTrack_m", NaN, "geometricContactTrack_m", NaN);
end
