function analysis = analyzeCornerStateCore(geometry, result)
%ANALYZECORNERSTATECORE Analyze one state after geometry validation.

validateResultEnvelope(result);
analysis = emptyAnalysis(geometry, result);
if ~result.converged
    return
end

validateConvergedResult(result);
steeringAxis = fsd.analysis.steeringAxisFromPoints( ...
    result.state.lbj_m, result.state.ubj_m);

analysis.wheelTravel_m = double(result.achievedWheelTravel_m);
analysis.camber_rad = fsd.analysis.camberFromWheelAxis( ...
    result.wheelAxis, geometry.cornerId);
analysis.toe_rad = fsd.analysis.toeFromWheelAxis( ...
    result.wheelAxis, geometry.cornerId);
analysis.caster_rad = fsd.analysis.casterFromSteeringAxis(steeringAxis);
analysis.kingpinInclination_rad = fsd.analysis.kingpinInclination( ...
    steeringAxis, geometry.cornerId);
analysis.steeringAxis = steeringAxis;
end

function analysis = emptyAnalysis(geometry, result)
failureReason = "";
if isfield(result, "failureReason") && ...
        (ischar(result.failureReason) || ...
        (isstring(result.failureReason) && isscalar(result.failureReason)))
    failureReason = string(result.failureReason);
end
solverDiagnostics = struct();
if isfield(result, "diagnostics") && isstruct(result.diagnostics) && ...
        isscalar(result.diagnostics)
    solverDiagnostics = result.diagnostics;
end
analysis = struct( ...
    "schemaVersion", "0.3.0", ...
    "kind", "CornerKinematicAnalysis", ...
    "cornerId", geometry.cornerId, ...
    "requestedWheelTravel_m", double(result.requestedWheelTravel_m), ...
    "wheelTravel_m", NaN, ...
    "camber_rad", NaN, ...
    "toe_rad", NaN, ...
    "caster_rad", NaN, ...
    "kingpinInclination_rad", NaN, ...
    "steeringAxis", [NaN, NaN, NaN], ...
    "converged", logical(result.converged), ...
    "status", string(result.status), ...
    "failureReason", failureReason, ...
    "solverDiagnostics", solverDiagnostics);
end

function validateResultEnvelope(result)
if ~isstruct(result) || ~isscalar(result)
    error("fsd:analysis:InvalidKinematicResult", ...
        "result must be a scalar KinematicResult struct.");
end
required = ["kind", "requestedWheelTravel_m", "achievedWheelTravel_m", ...
    "converged", "status", "state", "wheelAxis", "camber_rad"];
for index = 1:numel(required)
    if ~isfield(result, required(index))
        error("fsd:analysis:InvalidKinematicResult", ...
            "KinematicResult is missing field '%s'.", required(index));
    end
end
if ~isTextScalar(result.kind) || string(result.kind) ~= "KinematicResult" || ...
        ~isnumeric(result.requestedWheelTravel_m) || ...
        ~isreal(result.requestedWheelTravel_m) || ...
        ~isscalar(result.requestedWheelTravel_m) || ...
        ~isfinite(result.requestedWheelTravel_m) || ...
        ~isnumeric(result.achievedWheelTravel_m) || ...
        ~isreal(result.achievedWheelTravel_m) || ...
        ~isscalar(result.achievedWheelTravel_m) || ...
        isinf(result.achievedWheelTravel_m) || ...
        ~islogical(result.converged) || ~isscalar(result.converged) || ...
        ~isTextScalar(result.status) || ...
        strlength(string(result.status)) == 0
    error("fsd:analysis:InvalidKinematicResult", ...
        "result does not satisfy the KinematicResult envelope.");
end

if ~isnumeric(result.wheelAxis) || ~isreal(result.wheelAxis) || ...
        ~isequal(size(result.wheelAxis), [1, 3]) || ...
        any(isinf(result.wheelAxis)) || ...
        ~isnumeric(result.camber_rad) || ~isreal(result.camber_rad) || ...
        ~isscalar(result.camber_rad) || isinf(result.camber_rad) || ...
        ~isstruct(result.state) || ~isscalar(result.state)
    error("fsd:analysis:InvalidKinematicResult", ...
        "result state and metric fields have invalid types or dimensions.");
end
end

function validateConvergedResult(result)
if ~isnumeric(result.achievedWheelTravel_m) || ...
        ~isreal(result.achievedWheelTravel_m) || ...
        ~isscalar(result.achievedWheelTravel_m) || ...
        ~isfinite(result.achievedWheelTravel_m) || ...
        ~isnumeric(result.camber_rad) || ~isreal(result.camber_rad) || ...
        ~isscalar(result.camber_rad) || ~isfinite(result.camber_rad) || ...
        ~isstruct(result.state) || ~isscalar(result.state) || ...
        ~isfield(result.state, "ubj_m") || ...
        ~isfield(result.state, "lbj_m")
    error("fsd:analysis:InvalidKinematicResult", ...
        "A converged result must contain finite state and travel data.");
end
end

function tf = isTextScalar(value)
tf = (ischar(value) && isrow(value)) || ...
    (isstring(value) && isscalar(value) && ~ismissing(value));
end
