function analysis = analyzeSteeringCore(steering, result)
%ANALYZESTEERINGCORE Analyze an already validated bilateral steering state.

timer = tic;
if result.converged
    left = analyzeSide(steering.frontAxleGeometry.leftGeometry, ...
        result.leftResult);
    right = analyzeSide(steering.frontAxleGeometry.rightGeometry, ...
        result.rightResult);
    ackermann = fsd.analysis.ackermannGeometry( ...
        left.geometricContact.point_m, left.roadWheelHeading, ...
        right.geometricContact.point_m, right.roadWheelHeading, ...
        steering.rearAxleX_m, left.rackInducedSteer_rad, ...
        right.rackInducedSteer_rad);
else
    diagnostic = "The bilateral steering state did not converge; " + ...
        "no derived side metrics were published.";
    left = invalidSide(result.leftResult, diagnostic);
    right = invalidSide(result.rightResult, diagnostic);
    ackermann = invalidAckermann(result.failureReason);
end
analysis = struct( ...
    "schemaVersion", "0.5.0", ...
    "kind", "SteeringAxleAnalysis", ...
    "steeringSystemIdentity", steering.identity, ...
    "requestedRackTravel_m", result.requestedRackTravel_m, ...
    "requestedWheelTravel_m", result.requestedWheelTravel_m, ...
    "converged", result.converged, ...
    "status", string(result.status), ...
    "failureReason", string(result.failureReason), ...
    "left", left, ...
    "right", right, ...
    "ackermann", ackermann, ...
    "analysisElapsedTime_s", toc(timer));
end

function side = analyzeSide(geometry, result)
[~, staticAngle_rad] = fsd.analysis.roadWheelHeading( ...
    geometry.wheel.wheelAxis, geometry.cornerId);
[heading, angle_rad] = fsd.analysis.roadWheelHeading( ...
    result.wheelAxis, geometry.cornerId);
[~, rackZeroAngle_rad] = fsd.analysis.roadWheelHeading( ...
    result.rackZeroKinematicResult.wheelAxis, geometry.cornerId);
toe_rad = fsd.analysis.toeFromWheelAxis( ...
    result.wheelAxis, geometry.cornerId);
staticToe_rad = fsd.analysis.toeFromWheelAxis( ...
    geometry.wheel.wheelAxis, geometry.cornerId);
steeringAxis = fsd.analysis.steeringAxisFromPoints( ...
    result.state.lbj_m, result.state.ubj_m);
scrubTrail = fsd.analysis.scrubAndMechanicalTrail( ...
    result.state.lbj_m, result.state.ubj_m, ...
    result.geometricContact.point_m, geometry.cornerId);
side = struct( ...
    "cornerId", string(geometry.cornerId), ...
    "status", "FINITE", ...
    "kinematicConverged", result.converged, ...
    "kinematicStatus", string(result.status), ...
    "kinematicFailureReason", string(result.failureReason), ...
    "solverDiagnostics", result.diagnostics, ...
    "roadWheelHeading", heading, ...
    "roadWheelAngle_rad", angle_rad, ...
    "staticRoadWheelAngle_rad", staticAngle_rad, ...
    "steerDeflectionFromStatic_rad", ...
        fsd.geometry.wrapAngle(angle_rad - staticAngle_rad), ...
    "rackInducedSteer_rad", ...
        fsd.geometry.wrapAngle(angle_rad - rackZeroAngle_rad), ...
    "toe_rad", toe_rad, ...
    "staticToe_rad", staticToe_rad, ...
    "bumpSteer_rad", fsd.geometry.wrapAngle(toe_rad - staticToe_rad), ...
    "steeringAxis", steeringAxis, ...
    "geometricContact", result.geometricContact, ...
    "steeringAxisRoadIntersection", ...
        scrubTrail.steeringAxisRoadIntersection, ...
    "scrubRadius_m", scrubTrail.scrubRadius_m, ...
    "mechanicalTrail_m", scrubTrail.mechanicalTrail_m, ...
    "diagnostic", string(scrubTrail.diagnostic));
end

function side = invalidSide(result, diagnostic)
side = struct( ...
    "cornerId", string(result.cornerId), ...
    "status", "KINEMATICS_NOT_CONVERGED", ...
    "kinematicConverged", result.converged, ...
    "kinematicStatus", string(result.status), ...
    "kinematicFailureReason", string(result.failureReason), ...
    "solverDiagnostics", result.diagnostics, ...
    "roadWheelHeading", [NaN, NaN, NaN], ...
    "roadWheelAngle_rad", NaN, ...
    "staticRoadWheelAngle_rad", NaN, ...
    "steerDeflectionFromStatic_rad", NaN, ...
    "rackInducedSteer_rad", NaN, ...
    "toe_rad", NaN, ...
    "staticToe_rad", NaN, ...
    "bumpSteer_rad", NaN, ...
    "steeringAxis", [NaN, NaN, NaN], ...
    "geometricContact", invalidContact(diagnostic), ...
    "steeringAxisRoadIntersection", invalidIntersection(diagnostic), ...
    "scrubRadius_m", NaN, ...
    "mechanicalTrail_m", NaN, ...
    "diagnostic", string(diagnostic));
end

function value = invalidContact(diagnostic)
value = struct( ...
    "status", "KINEMATICS_NOT_CONVERGED", ...
    "point_m", [NaN, NaN, NaN], ...
    "geometricRadius_m", NaN, ...
    "diagnostic", string(diagnostic));
end

function value = invalidIntersection(diagnostic)
value = struct( ...
    "schemaVersion", "0.5.0", ...
    "kind", "SteeringAxisHorizontalPlaneIntersection", ...
    "status", "KINEMATICS_NOT_CONVERGED", ...
    "point_m", [NaN, NaN, NaN], ...
    "conditioning", NaN, ...
    "isIllConditioned", false, ...
    "diagnostic", string(diagnostic));
end

function value = invalidAckermann(reason)
icr = struct("status", "KINEMATICS_NOT_CONVERGED", "y_m", NaN, ...
    "homogeneousPoint", [NaN, NaN], "conditioning", NaN, ...
    "isIllConditioned", false, "diagnostic", string(reason));
value = struct( ...
    "schemaVersion", "0.5.0", ...
    "kind", "AckermannGeometryAnalysis", ...
    "status", "KINEMATICS_NOT_CONVERGED", ...
    "steeringDirection", "UNDEFINED", ...
    "innerCorner", "", ...
    "outerCorner", "", ...
    "leftIcr", icr, ...
    "rightIcr", icr, ...
    "icrMismatch_m", NaN, ...
    "actualInnerRoadWheelAngle_rad", NaN, ...
    "actualOuterRoadWheelAngle_rad", NaN, ...
    "idealOuterRoadWheelAngle_rad", NaN, ...
    "ackermannAngleError_rad", NaN, ...
    "conditioning", NaN, ...
    "diagnostic", string(reason));
end
