function instantCenter = frontViewInstantCenterCore(geometry, result)
%FRONTVIEWINSTANTCENTERCORE Compute FVIC from already validated inputs.

if isempty(result)
    ubj_m = point(geometry, "UBJ");
    lbj_m = point(geometry, "LBJ");
else
    ubj_m = double(result.state.ubj_m);
    lbj_m = double(result.state.lbj_m);
end
upperConstraint = fsd.geometry.frontViewKinematicConstraint( ...
    point(geometry, "UCA_FWD_CHASSIS"), ...
    point(geometry, "UCA_AFT_CHASSIS"), ubj_m);
lowerConstraint = fsd.geometry.frontViewKinematicConstraint( ...
    point(geometry, "LCA_FWD_CHASSIS"), ...
    point(geometry, "LCA_AFT_CHASSIS"), lbj_m);
upperLine = upperConstraint.line;
lowerLine = lowerConstraint.line;
intersection = fsd.geometry.intersectLinesYZ(upperLine, lowerLine);
instantCenter = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "FrontViewInstantCenter", ...
    "cornerId", string(geometry.cornerId), ...
    "status", string(intersection.status), ...
    "instantCenterY_m", double(intersection.y_m), ...
    "instantCenterZ_m", double(intersection.z_m), ...
    "point_yz_m", double(intersection.point_yz_m), ...
    "homogeneousPoint", double(intersection.homogeneousPoint), ...
    "direction_yz", double(intersection.direction_yz), ...
    "conditioning", double(intersection.conditioning), ...
    "isIllConditioned", logical(intersection.isIllConditioned), ...
    "upperConstraint", upperConstraint, ...
    "lowerConstraint", lowerConstraint, ...
    "upperLine", upperLine, ...
    "lowerLine", lowerLine, ...
    "diagnostic", string(intersection.diagnostic));
end

function point_m = point(geometry, role)
pointId = string(geometry.cornerId) + "_" + role;
point_m = double(geometry.hardpoints.xyz_m( ...
    geometry.hardpoints.ids == pointId, :));
end
