function contact = geometricWheelContactCore(geometry, result, radius_m)
%GEOMETRICWHEELCONTACTCORE Apply contact model to validated inputs.

cornerId = string(geometry.cornerId);
staticDatum_m = point(geometry, "CONTACT_PATCH");
if isempty(result)
    wheelCenter_m = point(geometry, "WHEEL_CENTER");
    wheelAxis = double(geometry.wheel.wheelAxis);
else
    wheelCenter_m = double(result.state.wheelCenter_m);
    wheelAxis = double(result.wheelAxis);
end
ideal = fsd.geometry.geometricWheelContact( ...
    wheelCenter_m, wheelAxis, radius_m);
contact = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "IdealRigidWheelContact", ...
    "cornerId", cornerId, ...
    "status", string(ideal.status), ...
    "geometricRadius_m", radius_m, ...
    "wheelCenter_m", wheelCenter_m, ...
    "wheelAxis", wheelAxis, ...
    "point_m", double(ideal.point_m), ...
    "staticDatum_m", staticDatum_m, ...
    "diagnostic", string(ideal.diagnostic));
end

function point_m = point(geometry, role)
pointId = string(geometry.cornerId) + "_" + role;
point_m = double(geometry.hardpoints.xyz_m( ...
    geometry.hardpoints.ids == pointId, :));
end
