function o = globalSolverOptions(input)
%GLOBALSOLVEROPTIONS Explicit search box/scales and dimensional numerical budgets.
id = "fsd:analysis:InvalidGlobalStaticInput";
mandatory = ["bounds","coordinateScales","forceTolerance_N","momentTolerance_Nm", ...
    "positionTolerance_m","angleTolerance_rad","stabilityTolerance_J"];
o = struct("bounds",[],"coordinateScales",[],"forceTolerance_N",[], ...
    "momentTolerance_Nm",[],"positionTolerance_m",[],"angleTolerance_rad",[], ...
    "stabilityTolerance_J",[],"maxIterations",80,"maxLineSearchSteps",30, ...
    "selection","UNIQUE_ONLY","conditioningThreshold",sqrt(eps));
if ~isstruct(input) || ~isscalar(input) || ~all(isfield(input,mandatory)) || ...
        ~isempty(setdiff(fieldnames(input),fieldnames(o)))
    error(id,"Explicit search bounds, coordinate scales and dimensional budgets required.");
end
names = fieldnames(input);
for i = 1:numel(names), o.(names{i}) = input.(names{i}); end
if ~isnumeric(o.bounds) || ~isreal(o.bounds) || ~isequal(size(o.bounds),[7,2]) || ...
        any(~isfinite(o.bounds),"all") || any(o.bounds(:,1) >= o.bounds(:,2)) || ...
        any(abs(o.bounds(2:3,:)) >= pi/2,"all") || ...
        ~isnumeric(o.coordinateScales) || ~isreal(o.coordinateScales) || ...
        ~isequal(size(o.coordinateScales),[7,1]) || any(~isfinite(o.coordinateScales)) || ...
        any(o.coordinateScales <= 0)
    error(id,"Invalid bounds/scales; search box is not a set of physical stops.");
end
for name = [mandatory(3:end),"conditioningThreshold","maxIterations","maxLineSearchSteps"]
    v = o.(name);
    if ~isnumeric(v) || ~isreal(v) || ~isscalar(v) || ~isfinite(v) || v <= 0
        error(id,"Positive finite solver budgets required.");
    end
end
if o.maxIterations ~= fix(o.maxIterations) || o.maxLineSearchSteps ~= fix(o.maxLineSearchSteps) || ...
        o.conditioningThreshold >= 1 || ~any(string(o.selection) == ["UNIQUE_ONLY","LOWEST_ENERGY_STABLE"])
    error(id,"Invalid iteration/conditioning/selection policy.");
end
o.selection = string(o.selection);
end
