function globalVerifyResult(p, result)
%GLOBALVERIFYRESULT Reconstruct transformed physics, root acceptance, stability and selection.
id = "fsd:analysis:InvalidGlobalStaticEquilibrium";
if ~isstruct(result) || ~isscalar(result) || ~all(isfield(result, ...
        ["schemaVersion","kind","systemIdentity","solverOptions","initialGuesses", ...
        "attempts","alternatives","selectedIndex","status","rootCompleteness","performance"])) || ...
        ~isequal(result.schemaVersion,"0.10.0") || ...
        ~isequal(result.kind,"GlobalStaticEquilibriumResult") || ...
        ~isequaln(result.systemIdentity,p.identity) || ...
        ~isequal(result.rootCompleteness,"SUPPLIED_SEEDS_ONLY")
    error(id,"Invalid result/identity.");
end
o = globalSolverOptions(result.solverOptions);
if ~iscell(result.attempts) || numel(result.attempts) ~= size(result.initialGuesses,2) || ...
        size(result.initialGuesses,1) ~= 7 || any(~isfinite(result.initialGuesses),"all")
    error(id,"Invalid attempts/seeds.");
end
for i = 1:numel(result.attempts)
    a = result.attempts{i};
    if ~isstruct(a) || ~all(isfield(a,["initialGuess","solution","diagnostics"])) || ...
            ~isequal(a.initialGuess,result.initialGuesses(:,i)) || ...
            any(a.initialGuess < o.bounds(:,1) | a.initialGuess > o.bounds(:,2))
        error(id,"Inconsistent attempt input.");
    end
    q = globalCoordinateInput(a.solution.state.q);
    if any(q < o.bounds(:,1) | q > o.bounds(:,2)) || ...
            ~isequaln(a.solution,globalSolutionCore(p,q,o))
        error(id,"Inconsistent solution physics/status/stability.");
    end
    d = a.diagnostics;
    if ~isstruct(d) || ~all(isfield(d,["method","termination","iterations", ...
            "residualEvaluations","sourceRevalidationsDuringSolve","scaledResidualHistory","solveTime_s"])) || ...
            d.sourceRevalidationsDuringSolve ~= 0 || ~isequal(d.method,"SCALED_DAMPED_NEWTON") || ...
            ~isfinite(d.solveTime_s) || d.solveTime_s < 0 || d.iterations < 0 || ...
            d.iterations > o.maxIterations || d.iterations ~= fix(d.iterations) || ...
            d.residualEvaluations < 1 || numel(d.scaledResidualHistory) ~= d.iterations+1
        error(id,"Invalid solver diagnostics.");
    end
end
[alternatives,selected,status] = globalSelectionCore(result.attempts,o);
if ~isequaln(result.alternatives,alternatives) || ~isequaln(result.selectedIndex,selected) || ...
        ~isequal(result.status,status)
    error(id,"Inconsistent alternatives/selection.");
end
end
