function metrics = springDamperMetrics(a)
%SPRINGDAMPERMETRICS Complete-path extrema only, never hide missing samples.
metrics = struct("maximumSpringAxialForce_N",maximum(a.springAxialForce_N), ...
    "maximumAbsoluteSpringWheelResistance_N",maximum(abs(a.springWheelResistance_N)), ...
    "minimumWheelRate_N_per_m",minimum(a.wheelRateTotal_N_per_m), ...
    "maximumWheelRate_N_per_m",maximum(a.wheelRateTotal_N_per_m), ...
    "minimumDamperLength_m",minimum(a.damperLength_m), ...
    "maximumDamperLength_m",maximum(a.damperLength_m), ...
    "maximumCompression_m",nonnegativeMaximum(a.damperCompression_m), ...
    "maximumExtension_m",nonnegativeMaximum(-a.damperCompression_m), ...
    "maximumSpringStoredEnergy_J",maximum(a.springStoredEnergy_J), ...
    "maximumAbsoluteDamperVelocity_m_per_s",maximum(abs(a.damperVelocity_m_per_s)), ...
    "maximumAbsoluteDamperResistance_N",maximum(abs(a.damperAxialResistance_N)), ...
    "maximumDissipatedPower_W",maximum(a.damperDissipatedPower_W), ...
    "minimumDamperCompressionMargin_m",minimum(a.damperMinimumMargin_m), ...
    "minimumDamperExtensionMargin_m",minimum(a.damperMaximumMargin_m), ...
    "minimumSpringSolidMargin_m",minimum(a.springSolidMargin_m));
end

function value = maximum(x)
value = NaN;
if all(isfinite(x)), value = max(x); end
end

function value = minimum(x)
value = NaN;
if all(isfinite(x)), value = min(x); end
end

function value = nonnegativeMaximum(x)
value = NaN;
if all(isfinite(x)), value = max([x;0]); end
end
