function analysis = springDamperSingleCore(model, source, velocity)
%SPRINGDAMPERSINGLECORE No invented wheel derivatives in scalar responses.
state = springDamperStateCore(model,source.damperLength_m,source.damperCompression_m, ...
    source.converged,NaN,NaN,"UNAVAILABLE_SINGLE_STATE",velocity,"damper");
analysis = struct("schemaVersion","0.8.0","kind","SpringDamperStateAnalysis", ...
    "modelIdentity",model.identity,"source",source, ...
    "inputDamperVelocity_m_per_s",velocity,"state",state);
end
