function state = springDamperStateCore(model, length, compression, valid, ...
        mr, derivative, derivativeStatus, velocity, velocityKind)
%SPRINGDAMPERSTATECORE Axial laws plus optional validated path projection.
state = struct("damperLength_m",length,"damperCompression_m",compression, ...
    "springSeatSeparation_m",NaN,"springRawCompression_m",NaN, ...
    "springCompression_m",NaN,"springGap_m",NaN,"springLength_m",NaN, ...
    "springAxialForce_N",NaN,"springStoredEnergy_J",NaN, ...
    "springStatus","UNAVAILABLE_ACTUATION_FAILURE", ...
    "damperTravelStatus","UNAVAILABLE_ACTUATION_FAILURE", ...
    "springSolidStatus","UNAVAILABLE_ACTUATION_FAILURE", ...
    "damperMinimumMargin_m",NaN,"damperMaximumMargin_m",NaN,"springSolidMargin_m",NaN, ...
    "feasibleRelativeToProvidedLimits",false, ...
    "damperMotionRatio",mr,"motionRatioDerivative_per_m",derivative, ...
    "derivativeStatus",derivativeStatus,"wheelVelocity_m_per_s",NaN, ...
    "damperVelocity_m_per_s",NaN,"damperAxialResistance_N",NaN, ...
    "damperDissipatedPower_W",NaN,"damperLocalCoefficient_Ns_per_m",NaN, ...
    "damperStatus","UNAVAILABLE_ACTUATION_FAILURE", ...
    "springWheelResistance_N",NaN,"damperWheelResistance_N",NaN, ...
    "damperWheelLocalCoefficient_Ns_per_m",NaN, ...
    "damperWheelCompressionCoefficient_Ns_per_m",NaN, ...
    "damperWheelReboundCoefficient_Ns_per_m",NaN, ...
    "wheelRateElastic_N_per_m",NaN,"wheelRateGeometric_N_per_m",NaN, ...
    "wheelRateTotal_N_per_m",NaN,"wheelRateStatus","UNAVAILABLE_ACTUATION_FAILURE", ...
    "stiffnessDiagnostic","UNAVAILABLE");
if ~valid, return; end
state.springSeatSeparation_m = length+model.derivedStaticGeometry.springSeatOffset_m;
spring = springLaw(model.spring,compression);
bounds = mechanicalBounds(model,length,state.springSeatSeparation_m);
state = copyFields(state,spring); state = copyFields(state,bounds);
if ~bounds.feasibleRelativeToProvidedLimits
    state.springAxialForce_N = NaN; state.springStoredEnergy_J = NaN;
    state.wheelRateStatus = "UNAVAILABLE_MECHANICAL_LIMIT";
    state.damperStatus = "UNAVAILABLE_MECHANICAL_LIMIT";
    return;
end
if velocityKind == "wheel"
    state.wheelVelocity_m_per_s = velocity;
    axialVelocity = mr*velocity;
else
    axialVelocity = velocity;
end
state = copyFields(state,damperLaw(model.damper,axialVelocity));
state = projectSpringDamperResponse(state,model);
names = string(fieldnames(state));
for name = names'
    value = state.(name);
    if isnumeric(value) && any(isinf(value),"all")
        error("fsd:analysis:InvalidSpringDamperAnalysis","Mechanical arithmetic overflow.");
    end
end
end

function target = copyFields(target, source)
names = fieldnames(source);
for i = 1:numel(names), target.(names{i}) = source.(names{i}); end
end
