function c = designConstraintCore(input)
%DESIGNCONSTRAINTCORE Closed XYZ box or explicit coordinate-wise fixed tolerance.
template = struct("id",[],"scope",[],"type",[],"strength",[],"unit",[], ...
    "position",[],"bounds",[],"comparisonTolerance",[],"frame","VEHICLE_GLOBAL", ...
    "sourceNote",[],"metadata",struct());
d = designDefinition(input,template,["id","scope","type","strength","unit","sourceNote"]);
d.id = designText(d.id); d.type = designText(d.type); d.strength = designText(d.strength);
d.scope = fsd.model.designScope(d.scope.kind,d.scope.id,d.scope.cornerId);
designRequire(d.scope.kind == "HARDPOINT" && d.unit == "m" && ...
    d.frame == "VEHICLE_GLOBAL" && any(d.strength == ["HARD","SOFT"]),"Constraint scope/frame/unit/strength mismatch.");
designRequire(isscalar(string(d.sourceNote)) && strlength(string(d.sourceNote)) > 0,"Constraint source note required.");
if d.type == "AXIS_ALIGNED_BOX"
    designRequire(isnumeric(d.bounds) && isreal(d.bounds) && isequal(size(d.bounds),[3,2]) && ...
        all(isfinite(d.bounds),"all") && all(d.bounds(:,1) <= d.bounds(:,2)) && ...
        isempty(d.position) && isempty(d.comparisonTolerance),"Box requires complete ordered XYZ bounds only.");
elseif d.type == "HARDPOINT_FIXED"
    designRequire(isnumeric(d.position) && isreal(d.position) && isequal(size(d.position),[1,3]) && ...
        all(isfinite(d.position)) && isnumeric(d.comparisonTolerance) && isreal(d.comparisonTolerance) && ...
        isscalar(d.comparisonTolerance) && isfinite(d.comparisonTolerance) && ...
        d.comparisonTolerance >= 0 && isempty(d.bounds),"Fixed point needs XYZ and explicit comparison tolerance.");
else
    designRequire(false,"Unsupported constraint type.");
end
c = designRecord("DesignConstraint",d);
end
