function loadCase = vehicleLoadCaseCore(vehicleIdentity, definition)
%VEHICLELOADCASECORE Canonical fourth condition or explicit underdetermination.
fsd.model.validateVehicleIdentity(vehicleIdentity);
vehicleRequire(isstruct(definition) && isscalar(definition) && ...
    all(isfield(definition,["mode","sourceKind"])) && ...
    isempty(setdiff(string(fieldnames(definition)), ...
    ["mode","sourceKind","crossweightFraction","measuredCornerLoads_N"])),"Invalid load-case definition.");
mode = vehicleText(definition.mode); source = vehicleText(definition.sourceKind);
vehicleRequire(any(source == ["KNOWN","FIXED","RANGE","FREE","TARGET","DERIVED", ...
    "ASSUMED","RULE","UNSPECIFIED"]),"Invalid load provenance.");
cw = NaN; measured = nan(4,1);
if isfield(definition,"crossweightFraction"), cw = vehicleValue(definition.crossweightFraction,1,true); end
if isfield(definition,"measuredCornerLoads_N")
    measured = vehicleValue(definition.measuredCornerLoads_N,4,true)';
end
switch mode
    case "UNDERDETERMINED"
        vehicleRequire(isnan(cw) && all(isnan(measured)),"Underdetermined case cannot close loads.");
    case "CROSSWEIGHT_SPECIFIED"
        vehicleRequire(isfinite(cw) && cw >= 0 && cw <= 1 && all(isnan(measured)), ...
            "Crossweight requires one fraction, not measurements.");
    case "MEASURED_CORNER_LOADS"
        vehicleRequire(isnan(cw) && all(isfinite(measured)) && all(measured >= 0), ...
            "Measured loads must be four nonnegative normals.");
    case "ASSUMED_SYMMETRIC_BASELINE"
        vehicleRequire(source == "ASSUMED" && isnan(cw) && all(isnan(measured)), ...
            "Symmetric baseline must explicitly be ASSUMED.");
    otherwise
        vehicleRequire(false,"Unknown distribution mode.");
end
d = struct("mode",mode,"sourceKind",source,"crossweightFraction",cw, ...
    "measuredCornerLoads_N",measured);
loadCase = struct("schemaVersion","0.9.0","kind","VehicleLoadCase", ...
    "vehicleIdentity",vehicleIdentity,"operatingConfiguration", ...
    vehicleIdentity.definitionSI.operatingConfiguration,"definitionSI",d,"metadata",struct);
loadCase.identity = struct("schemaVersion","1.0.0","kind","VehicleLoadCaseIdentity", ...
    "vehicleIdentity",vehicleIdentity,"operatingConfiguration",loadCase.operatingConfiguration, ...
    "definitionSI",d,"assumptions",["HORIZONTAL_GROUND","UNIFORM_GRAVITY", ...
    "NO_ACCELERATION","NO_AERO_OR_OTHER_EXTERNAL_LOADS","VERTICAL_CONTACT_REACTIONS"]);
end
