function identity = actuationIdentity(actuation)
%ACTUATIONIDENTITY Return the canonical physical/architectural identity.
%   This function accepts a construction-stage struct without an identity
%   field so createActuationGeometry can build the final self-consistent
%   model. Public callers normally pass a validated ActuationGeometry.

required = ["schemaVersion", "kind", "cornerId", ...
    "cornerGeometryIdentity", "actuationType", ...
    "suspensionAttachment", "rocker", "damper"];
if ~isstruct(actuation) || ~isscalar(actuation) || ...
        any(~isfield(actuation, required))
    error("fsd:model:InvalidActuationGeometry", ...
        "ActuationGeometry is incomplete.");
end
identity = struct( ...
    "schemaVersion", "1.0.0", ...
    "kind", "ActuationGeometryIdentity", ...
    "actuationSchemaVersion", string(actuation.schemaVersion), ...
    "cornerId", string(actuation.cornerId), ...
    "cornerGeometryIdentity", actuation.cornerGeometryIdentity, ...
    "actuationType", string(actuation.actuationType), ...
    "suspensionAttachmentBody", ...
        string(actuation.suspensionAttachment.body), ...
    "suspensionAttachmentPointStatic_m", ...
        double(actuation.suspensionAttachment.pointStatic_m), ...
    "rockerAxisPoint_m", double(actuation.rocker.axis.point_m), ...
    "rockerAxisDirection_unit", ...
        double(actuation.rocker.axis.direction_unit), ...
    "rockerRodPointStatic_m", ...
        double(actuation.rocker.actuationRodPoint.pointStatic_m), ...
    "rockerDamperPointStatic_m", ...
        double(actuation.rocker.damperPoint.pointStatic_m), ...
    "damperChassisPoint_m", ...
        double(actuation.damper.chassisPoint.point_m));
end
