function identity = axleIdentity(axle)
%AXLEIDENTITY Return the canonical identity of a validated axle geometry.

fsd.model.validateAxleGeometry(axle);
identity = struct( ...
    "schemaVersion", "1.0.0", ...
    "kind", "AxleGeometryIdentity", ...
    "axleSchemaVersion", string(axle.schemaVersion), ...
    "axleId", string(axle.axleId), ...
    "leftGeometryIdentity", ...
        fsd.model.geometryIdentity(axle.leftGeometry), ...
    "rightGeometryIdentity", ...
        fsd.model.geometryIdentity(axle.rightGeometry));
end
