function system = createGlobalStaticSystem(vehicle, loadCase, sources, tires, options)
%CREATEGLOBALSTATICSYSTEM Serializable inputs; downstream preparation validates paths.
% Sources/tires are four cells in FL/FR/RL/RR order. All option lengths are SI.
id = "fsd:model:InvalidGlobalStaticSystem";
fsd.model.validateVehicleParameters(vehicle);
fsd.model.validateVehicleLoadCase(loadCase,vehicle);
if ~iscell(sources) || numel(sources) ~= 4 || ~iscell(tires) || numel(tires) ~= 4 || ...
        ~isstruct(options) || ~isscalar(options) || ...
        ~all(isfield(options,["massApproximation","unsprungPositionAssumption"]))
    error(id,"Four sources/tires and explicit mass assumptions required.");
end
defaults = struct("massApproximation","KNOWN_UNSPRUNG_MASSES", ...
    "unsprungPositionAssumption","UNSPRUNG_MASS_AT_WHEEL_CENTER", ...
    "roadHeight_m",0,"rideHeightPointsBody_m",zeros(0,3),"rideHeightPointIds",strings(0,1));
if ~isempty(setdiff(fieldnames(options),fieldnames(defaults))), error(id,"Unknown options."); end
names = fieldnames(options);
for i = 1:numel(names), defaults.(names{i}) = options.(names{i}); end
o = defaults;
if ~isequal(o.unsprungPositionAssumption,"UNSPRUNG_MASS_AT_WHEEL_CENTER") || ...
        ~any(string(o.massApproximation) == ["KNOWN_UNSPRUNG_MASSES","ZERO_UNSPRUNG_APPROXIMATION"]) || ...
        ~isnumeric(o.roadHeight_m) || ~isreal(o.roadHeight_m) || ~isscalar(o.roadHeight_m) || ...
        ~isfinite(o.roadHeight_m) || ~isnumeric(o.rideHeightPointsBody_m) || ...
        ~isreal(o.rideHeightPointsBody_m) || size(o.rideHeightPointsBody_m,2) ~= 3 || ...
        any(~isfinite(o.rideHeightPointsBody_m),"all") || ~isstring(o.rideHeightPointIds) || ...
        ~iscolumn(o.rideHeightPointIds) || any(ismissing(o.rideHeightPointIds)) || ...
        any(strlength(o.rideHeightPointIds) == 0) || ...
        numel(o.rideHeightPointIds) ~= size(o.rideHeightPointsBody_m,1) || ...
        numel(unique(o.rideHeightPointIds)) ~= numel(o.rideHeightPointIds)
    error(id,"Invalid ground, reference points or mass assumptions.");
end
mu = vehicle.unsprungMass_kg;
if o.massApproximation == "ZERO_UNSPRUNG_APPROXIMATION", mu = zeros(4,1); end
if any(~isfinite(mu)) || vehicle.totalMass_kg-sum(mu) <= 0 || any(~isfinite(vehicle.cg_m))
    error(id,"Known XYZ CG and four masses (or explicit zero approximation) required.");
end
corners = ["FL";"FR";"RL";"RR"]; physical = cell(4,1);
for i = 1:4
    s = sources{i}; tire = tires{i};
    fsd.model.validateVerticalTireModel(tire);
    if ~isstruct(s) || ~isscalar(s) || ~all(isfield(s, ...
            ["geometry","actuation","springDamper","mechanical","pathKind"]))
        error(id,"Incomplete corner source.");
    end
    fsd.model.validateDoubleWishboneGeometry(s.geometry);
    fsd.model.validateActuationGeometry(s.actuation);
    fsd.model.validateSpringDamperModel(s.springDamper);
    if ~isequal(s.geometry.cornerId,corners(i)) || ~isequal(s.actuation.cornerId,corners(i)) || ...
            ~isequal(s.springDamper.cornerId,corners(i)) || ~isequal(tire.cornerId,corners(i)) || ...
            ~isequal(s.actuation.cornerGeometryIdentity,fsd.model.geometryIdentity(s.geometry)) || ...
            ~isequal(s.springDamper.actuationIdentity,s.actuation.identity) || ...
            ~all(isfield(s.mechanical,["path","modelIdentity","derivativeDiagnostics"])) || ...
            ~isequal(s.mechanical.modelIdentity,s.springDamper.identity) || ...
            ~any(string(s.pathKind) == ["ACTUATION_BUMP_3D","IDEAL_PRESCRIBED_3D"])
        error(id,"Mixed corner identities or unsupported source kind.");
    end
    physical{i} = struct("geometry",fsd.model.geometryIdentity(s.geometry), ...
        "actuation",s.actuation.identity,"springDamper",s.springDamper.identity, ...
        "tire",tire.identity,"pathKind",s.pathKind,"path",s.mechanical.path, ...
        "derivativeDiagnostics",s.mechanical.derivativeDiagnostics);
    if s.pathKind == "IDEAL_PRESCRIBED_3D"
        if ~all(isfield(s,["idealWheelCenterPath_m","sourceKind","sourceNote"])) || ...
                ~isequal(s.sourceKind,"ASSUMED") || strlength(string(s.sourceNote)) == 0
            error(id,"Ideal path requires explicit ASSUMED provenance.");
        end
        physical{i}.idealWheelCenterPath_m = s.idealWheelCenterPath_m;
    else
        if ~isfield(s.mechanical,"source") || ~isequal(s.mechanical.source.kind,"ActuationSweep") || ...
                ~isfield(s.mechanical.source,"sweep") || ~isfield(s.mechanical.source.sweep,"results")
            error(id,"Production source requires complete actuation results.");
        end
        results = s.mechanical.source.sweep.results;
        positions = nan(numel(results),3); angles = nan(numel(results),1);
        for j = 1:numel(results)
            if ~all(isfield(results(j),["sourceResult","rockerAngle_rad","converged"]))
                error(id,"Incomplete production path snapshot.");
            end
            if results(j).converged
                positions(j,:) = results(j).sourceResult.state.wheelCenter_m;
                angles(j) = results(j).rockerAngle_rad;
            end
        end
        physical{i}.wheelCentersBody_m = positions;
        physical{i}.rockerAngles_rad = angles;
    end
end
system = struct("schemaVersion","0.10.0","kind","GlobalStaticSystem", ...
    "vehicle",vehicle,"loadCase",loadCase,"cornerIds",corners,"sources",{sources(:)}, ...
    "tires",{tires(:)},"options",o,"coordinateSystem","X_REAR_Y_RIGHT_Z_UP", ...
    "rotationOrder","Rx(phi)*Ry(theta)","unsprungMass_kg",mu);
system.identity = struct("schemaVersion","1.0.0","kind","GlobalStaticSystemIdentity", ...
    "vehicle",vehicle.identity,"loadCase",loadCase.identity,"corners",{physical}, ...
    "options",rmfield(o,"rideHeightPointIds"),"rotationOrder",system.rotationOrder);
end
