function steering = createSteeringSystem(frontAxleGeometry, ...
    rearAxleX, inputUnit)
%CREATESTEERINGSYSTEM Build a canonical front rack steering system.

fsd.model.validateAxleGeometry(frontAxleGeometry);
if string(frontAxleGeometry.axleId) ~= "FRONT"
    error("fsd:model:SteeringRequiresFrontAxle", ...
        "SteeringSystemGeometry requires a FRONT AxleGeometry.");
end
rearAxleX_m = fsd.model.convertLengthToMetres(rearAxleX, inputUnit);
if ~isscalar(rearAxleX_m)
    error("fsd:model:InvalidRearAxleReference", ...
        "rearAxleX must be a finite real scalar.");
end
leftInner_m = fsd.model.getPoint(frontAxleGeometry.leftGeometry, ...
    "FL_TIE_ROD_INBOARD");
rightInner_m = fsd.model.getPoint(frontAxleGeometry.rightGeometry, ...
    "FR_TIE_ROD_INBOARD");
rackVector_m = rightInner_m - leftInner_m;
tolerances = fsd.model.numericTolerances();
scale_m = max([norm(leftInner_m), norm(rightInner_m), 1]);
if norm(rackVector_m) <= tolerances.AbsTol_m + ...
        tolerances.RelTol * scale_m
    error("fsd:model:DegenerateRackAxis", ...
        "The left and right tie-rod inner joints must not coincide.");
end
rackAxis = rackVector_m ./ norm(rackVector_m);
rackGeometry = struct( ...
    "leftInnerStatic_m", leftInner_m, ...
    "rightInnerStatic_m", rightInner_m, ...
    "axisDirection", rackAxis, ...
    "jointSeparation_m", norm(rackVector_m));
steering = struct( ...
    "schemaVersion", "0.5.0", ...
    "kind", "SteeringSystemGeometry", ...
    "frontAxleGeometry", frontAxleGeometry, ...
    "rackGeometry", rackGeometry, ...
    "rearAxleX_m", double(rearAxleX_m), ...
    "identity", struct());
steering.identity = fsd.model.steeringSystemIdentity(steering);
fsd.model.validateSteeringSystemGeometry(steering);
end
