function identity = geometryIdentity(geometry)
%GEOMETRYIDENTITY Return the canonical solver-relevant geometry identity.
%   The identity contains only validated fields that can alter the v0.2
%   kinematic mechanism: geometry schema, corner, canonical hardpoint IDs
%   and coordinates, and the static wheel axis.

fsd.model.validateDoubleWishboneGeometry(geometry);
canonicalIds = geometry.cornerId + "_" + ...
    fsd.model.requiredHardpointRoles();
canonicalXyz_m = zeros(numel(canonicalIds), 3);
for index = 1:numel(canonicalIds)
    canonicalXyz_m(index, :) = geometry.hardpoints.xyz_m( ...
        geometry.hardpoints.ids == canonicalIds(index), :);
end

identity = struct( ...
    "schemaVersion", "1.0.0", ...
    "kind", "DoubleWishboneGeometryIdentity", ...
    "geometrySchemaVersion", string(geometry.schemaVersion), ...
    "cornerId", string(geometry.cornerId), ...
    "hardpointIds", canonicalIds, ...
    "hardpointXyz_m", canonicalXyz_m, ...
    "wheelAxis", double(geometry.wheel.wheelAxis));
end
