function roles = requiredHardpointRoles()
%REQUIREDHARDPOINTROLES Canonical point roles required by v0.2.

roles = [ ...
    "UCA_FWD_CHASSIS"; ...
    "UCA_AFT_CHASSIS"; ...
    "UBJ"; ...
    "LCA_FWD_CHASSIS"; ...
    "LCA_AFT_CHASSIS"; ...
    "LBJ"; ...
    "TIE_ROD_INBOARD"; ...
    "TIE_ROD_OUTBOARD"; ...
    "WHEEL_CENTER"; ...
    "CONTACT_PATCH"];
end
