function identity = springDamperIdentity(model)
%SPRINGDAMPERIDENTITY Canonical physical identity; metadata is excluded.
identity = struct("schemaVersion","1.0.0","kind","SpringDamperModelIdentity", ...
    "modelSchemaVersion","0.8.0","cornerId",model.cornerId, ...
    "actuationIdentity",model.actuationIdentity, ...
    "configuration",model.configuration,"spring",model.spring,"damper",model.damper, ...
    "derivedStaticGeometry",model.derivedStaticGeometry);
end
