function identity = steeringSystemIdentity(steering)
%STEERINGSYSTEMIDENTITY Return canonical v0.5 steering identity.

validateIdentityInputs(steering);
rack = steering.rackGeometry;
identity = struct( ...
    "schemaVersion", "1.0.0", ...
    "kind", "SteeringSystemGeometryIdentity", ...
    "steeringSchemaVersion", string(steering.schemaVersion), ...
    "frontAxleIdentity", ...
        fsd.model.axleIdentity(steering.frontAxleGeometry), ...
    "leftInnerStatic_m", double(rack.leftInnerStatic_m), ...
    "rightInnerStatic_m", double(rack.rightInnerStatic_m), ...
    "rackAxisDirection", double(rack.axisDirection), ...
    "rearAxleX_m", double(steering.rearAxleX_m));
end

function validateIdentityInputs(steering)
if ~isstruct(steering) || ~isscalar(steering) || ...
        ~all(isfield(steering, ["schemaVersion", "kind", ...
        "frontAxleGeometry", "rackGeometry", "rearAxleX_m"])) || ...
        string(steering.schemaVersion) ~= "0.5.0" || ...
        string(steering.kind) ~= "SteeringSystemGeometry"
    error("fsd:model:InvalidSteeringSystemGeometry", ...
        "steering does not contain the canonical v0.5 model fields.");
end
fsd.model.validateAxleGeometry(steering.frontAxleGeometry);
if string(steering.frontAxleGeometry.axleId) ~= "FRONT"
    error("fsd:model:SteeringRequiresFrontAxle", ...
        "SteeringSystemGeometry requires a FRONT axle.");
end
rack = steering.rackGeometry;
if ~isstruct(rack) || ~isscalar(rack) || ...
        ~all(isfield(rack, ["leftInnerStatic_m", "rightInnerStatic_m", ...
        "axisDirection", "jointSeparation_m"])) || ...
        ~isFiniteSize(rack.leftInnerStatic_m, [1, 3]) || ...
        ~isFiniteSize(rack.rightInnerStatic_m, [1, 3]) || ...
        ~isFiniteSize(rack.axisDirection, [1, 3]) || ...
        ~isFiniteScalar(rack.jointSeparation_m) || ...
        ~isFiniteScalar(steering.rearAxleX_m)
    error("fsd:model:InvalidSteeringSystemGeometry", ...
        "rackGeometry or rearAxleX_m has an invalid contract.");
end
end

function tf = isFiniteSize(value, expectedSize)
tf = isnumeric(value) && isreal(value) && ...
    isequal(size(value), expectedSize) && all(isfinite(value));
end

function tf = isFiniteScalar(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && isfinite(value);
end
