function isValid = validateActuationIdentity(identity)
%VALIDATEACTUATIONIDENTITY Validate a canonical actuation identity.

if ~isstruct(identity) || ~isscalar(identity)
    invalid("Identity must be a scalar struct.");
end
required = ["schemaVersion", "kind", "actuationSchemaVersion", ...
    "cornerId", "cornerGeometryIdentity", "actuationType", ...
    "suspensionAttachmentBody", "suspensionAttachmentPointStatic_m", ...
    "rockerAxisPoint_m", ...
    "rockerAxisDirection_unit", "rockerRodPointStatic_m", ...
    "rockerDamperPointStatic_m", "damperChassisPoint_m"];
if any(~isfield(identity, required))
    invalid("Identity is missing required fields.");
end
if string(identity.schemaVersion) ~= "1.0.0" || ...
        string(identity.kind) ~= "ActuationGeometryIdentity" || ...
        string(identity.actuationSchemaVersion) ~= "0.7.0"
    invalid("Unsupported actuation identity schema.");
end
try
    fsd.model.validateGeometryIdentity(identity.cornerGeometryIdentity);
catch cause
    exception = MException("fsd:model:InvalidActuationIdentity", ...
        "Invalid corner geometry identity.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
if string(identity.cornerId) ~= ...
        string(identity.cornerGeometryIdentity.cornerId) || ...
        ~ismember(string(identity.actuationType), ["PUSHROD", "PULLROD"]) || ...
        ~ismember(string(identity.suspensionAttachmentBody), ...
            ["UPRIGHT", "UCA", "LCA"])
    invalid("Identity categorical fields are inconsistent.");
end
pointFields = ["suspensionAttachmentPointStatic_m", ...
    "rockerAxisPoint_m", "rockerAxisDirection_unit", ...
    "rockerRodPointStatic_m", "rockerDamperPointStatic_m", ...
    "damperChassisPoint_m"];
for index = 1:numel(pointFields)
    value = identity.(pointFields(index));
    if ~isnumeric(value) || ~isreal(value) || ...
            ~isequal(size(value), [1, 3]) || any(~isfinite(value))
        invalid("Identity vector fields must be finite 1-by-3 values.");
    end
end
tolerances = fsd.model.numericTolerances();
u = double(identity.rockerAxisDirection_unit);
if abs(norm(u) - 1) > tolerances.AbsTol_m + tolerances.RelTol || ...
        abs(dot(double(identity.rockerAxisPoint_m), u)) > ...
        10 * (tolerances.AbsTol_m + tolerances.RelTol * ...
        max([abs(identity.rockerAxisPoint_m), 1]))
    invalid("Rocker axis is not canonical and unit-normalized.");
end
isValid = true;
end

function invalid(message, varargin)
error("fsd:model:InvalidActuationIdentity", message, varargin{:});
end
