function isValid = validateActuationGeometry(actuation)
%VALIDATEACTUATIONGEOMETRY Validate a canonical v0.7 actuation model.

if ~isstruct(actuation) || ~isscalar(actuation)
    invalid("ActuationGeometry must be a scalar struct.");
end
required = ["schemaVersion", "kind", "cornerId", ...
    "cornerGeometryIdentity", "actuationType", ...
    "suspensionAttachment", "rocker", "damper", "actuationRod", ...
    "metadata", "identity"];
if any(~isfield(actuation, required)) || ...
        string(actuation.schemaVersion) ~= "0.7.0" || ...
        string(actuation.kind) ~= "ActuationGeometry"
    invalid("Unsupported or incomplete ActuationGeometry schema.");
end
try
    fsd.model.validateGeometryIdentity(actuation.cornerGeometryIdentity);
    fsd.model.validateActuationIdentity(actuation.identity);
catch cause
    exception = MException("fsd:model:InvalidActuationGeometry", ...
        "ActuationGeometry contains an invalid identity.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
if string(actuation.cornerId) ~= ...
        string(actuation.cornerGeometryIdentity.cornerId) || ...
        ~isequal(actuation.identity, fsd.model.actuationIdentity(actuation))
    invalid("ActuationGeometry identity or corner is inconsistent.");
end
if string(actuation.suspensionAttachment.id) ~= ...
        "ACTUATION_ROD_SUSPENSION" || ...
        string(actuation.rocker.actuationRodPoint.id) ~= ...
        "ACTUATION_ROD_ROCKER" || ...
        string(actuation.rocker.damperPoint.id) ~= "DAMPER_ROCKER" || ...
        string(actuation.damper.chassisPoint.id) ~= "DAMPER_CHASSIS"
    invalid("Actuation hardpoint IDs are not canonical.");
end
orientationMode = string(actuation.rocker.orientationMode);
axisDirection = actuation.rocker.axis.direction_unit;
if ~ismember(orientationMode, ["YZ_PLANE", "XZ_PLANE", "CUSTOM"]) || ...
        (orientationMode == "YZ_PLANE" && ...
        ~isequal(axisDirection, [1,0,0])) || ...
        (orientationMode == "XZ_PLANE" && ...
        ~isequal(axisDirection, [0,1,0]))
    invalid("Rocker orientation mode contradicts its axis direction.");
end
if string(actuation.metadata.lengthUnit) ~= "m" || ...
        string(actuation.metadata.coordinateSystem) ~= ...
        "X_REAR_Y_RIGHT_Z_UP"
    invalid("Actuation metadata must declare SI and the vehicle frame.");
end

tolerances = fsd.model.numericTolerances();
scale_m = max([abs(actuation.identity.rockerRodPointStatic_m), ...
    abs(actuation.identity.rockerDamperPointStatic_m), ...
    abs(actuation.identity.damperChassisPoint_m), 1]);
threshold_m = tolerances.AbsTol_m + tolerances.RelTol * scale_m;
axisPoint = actuation.rocker.axis.point_m;
rodLever_m = norm(cross( ...
    actuation.rocker.actuationRodPoint.pointStatic_m - axisPoint, ...
    axisDirection), 2);
damperLever_m = norm(cross( ...
    actuation.rocker.damperPoint.pointStatic_m - axisPoint, ...
    axisDirection), 2);
expectedRodLength_m = norm( ...
    actuation.suspensionAttachment.pointStatic_m - ...
    actuation.rocker.actuationRodPoint.pointStatic_m, 2);
expectedDamperLength_m = norm( ...
    actuation.rocker.damperPoint.pointStatic_m - ...
    actuation.damper.chassisPoint.point_m, 2);
if expectedRodLength_m <= threshold_m || ...
        expectedDamperLength_m <= threshold_m
    invalid("Static rod and damper lengths must be nonzero.");
end
if rodLever_m <= threshold_m
    error("fsd:model:RockerLeverArmDegenerate", ...
        "ACTUATION_ROD_ROCKER must not lie on the rocker axis.");
end
if damperLever_m <= threshold_m
    error("fsd:model:RockerDamperLeverArmDegenerate", ...
        "DAMPER_ROCKER must not lie on the rocker axis.");
end
if abs(actuation.actuationRod.staticLength_m - expectedRodLength_m) > ...
        10 * threshold_m || ...
        abs(actuation.damper.staticLength_m - expectedDamperLength_m) > ...
        10 * threshold_m
    invalid("Stored static lengths contradict the hardpoints.");
end
isValid = true;
end

function invalid(message, varargin)
error("fsd:model:InvalidActuationGeometry", message, varargin{:});
end
