function valid = validateVehicleLoadCase(loadCase, vehicle)
%VALIDATEVEHICLELOADCASE Validate operating inputs and vehicle association.
fsd.model.validateVehicleParameters(vehicle);
vehicleRequire(isstruct(loadCase) && isscalar(loadCase) && ...
    all(isfield(loadCase,["vehicleIdentity","definitionSI","metadata"])) && ...
    isstruct(loadCase.metadata) && isscalar(loadCase.metadata) && ...
    isequaln(loadCase.vehicleIdentity,vehicle.identity),"Invalid/mismatched load case.");
expected = vehicleLoadCaseCore(vehicle.identity,loadCase.definitionSI);
vehicleRequire(isequaln(rmfield(loadCase,"metadata"),rmfield(expected,"metadata")), ...
    "Inconsistent load-case payload.");
valid = true;
end
