function isValid = validateSpringDamperModel(model)
%VALIDATESPRINGDAMPERMODEL Check physical parameters, association and identity.
id = "fsd:model:InvalidSpringDamperModel";
require(isstruct(model) && isscalar(model) && all(isfield(model, ...
    ["schemaVersion","kind","cornerId","actuationIdentity","configuration", ...
    "spring","damper","derivedStaticGeometry","metadata","identity"])),id);
require(isequal(model.schemaVersion,"0.8.0") && isequal(model.kind,"SpringDamperModel") ...
    && isequal(model.configuration,"COILOVER"),id);
fsd.model.validateActuationIdentity(model.actuationIdentity);
require(isequal(model.cornerId,model.actuationIdentity.cornerId) && ...
    isstruct(model.metadata) && isscalar(model.metadata),id);
s = model.spring; d = model.damper;
require(isstruct(s) && isscalar(s) && all(isfield(s, ...
    ["modelType","rate_N_per_m","freeLength_m","preloadCompression_m","solidHeight_m"])),id);
require(isequal(s.modelType,"LINEAR_COMPRESSION") && ...
    scalar(s.rate_N_per_m) && s.rate_N_per_m > 0 && ...
    scalar(s.freeLength_m) && s.freeLength_m > 0 && ...
    scalar(s.preloadCompression_m) && s.preloadCompression_m >= 0 && ...
    s.preloadCompression_m < s.freeLength_m,id);
require(isempty(s.solidHeight_m) || (scalar(s.solidHeight_m) && ...
    s.solidHeight_m > 0 && s.solidHeight_m < s.freeLength_m),id);
require(isstruct(d) && isscalar(d) && all(isfield(d, ...
    ["modelType","compressionCoefficient_Ns_per_m","reboundCoefficient_Ns_per_m", ...
    "compressionTable","reboundTable","minimumLength_m","maximumLength_m"])),id);
if isequal(d.modelType,"LINEAR_ASYMMETRIC")
    require(scalar(d.compressionCoefficient_Ns_per_m) && ...
        d.compressionCoefficient_Ns_per_m >= 0 && ...
        scalar(d.reboundCoefficient_Ns_per_m) && ...
        d.reboundCoefficient_Ns_per_m >= 0 && ...
        isempty(d.compressionTable) && isempty(d.reboundTable),id);
elseif isequal(d.modelType,"TABULATED_FORCE_VELOCITY")
    require(tableValid(d.compressionTable) && tableValid(d.reboundTable) && ...
        isempty(d.compressionCoefficient_Ns_per_m) && ...
        isempty(d.reboundCoefficient_Ns_per_m),id);
else
    require(false,id);
end
for name = ["minimumLength_m","maximumLength_m"]
    value = d.(name);
    require(isempty(value) || (scalar(value) && value > 0),id);
end
require(isempty(d.minimumLength_m) || isempty(d.maximumLength_m) || ...
    d.minimumLength_m <= d.maximumLength_m,id);
derived = springDamperStaticGeometry(model);
require(scalar(derived.damperStaticLength_m) && derived.damperStaticLength_m > 0 && ...
    scalar(derived.springSeatSeparationStatic_m) && scalar(derived.springSeatOffset_m) && ...
    isequaln(model.derivedStaticGeometry,derived) ...
    && isequaln(model.identity,fsd.model.springDamperIdentity(model)),id);
isValid = true;
end

function tf = scalar(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && isfinite(value);
end

function tf = tableValid(value)
tf = isnumeric(value) && isreal(value) && size(value,2) == 2 && ...
    size(value,1) >= 2 && all(isfinite(value),"all") && ...
    all(value >= 0,"all") && isequal(value(1,:),[0,0]) && all(diff(value(:,1)) > 0);
end

function require(tf,id)
if ~tf, error(id,"Invalid or inconsistent mechanical model."); end
end
