function isValid = validateSpringDamperIdentity(identity)
%VALIDATESPRINGDAMPERIDENTITY Validate a standalone physical identity.
if ~isstruct(identity) || ~isscalar(identity) || ~all(isfield(identity, ...
        ["schemaVersion","kind","modelSchemaVersion","cornerId","actuationIdentity", ...
        "configuration","spring","damper","derivedStaticGeometry"])) || ...
        ~isequal(identity.schemaVersion,"1.0.0") || ...
        ~isequal(identity.kind,"SpringDamperModelIdentity") || ...
        ~isequal(identity.modelSchemaVersion,"0.8.0")
    error("fsd:model:InvalidSpringDamperModel","Invalid mechanical identity.");
end
model = struct("schemaVersion",identity.modelSchemaVersion,"kind","SpringDamperModel", ...
    "cornerId",identity.cornerId,"actuationIdentity",identity.actuationIdentity, ...
    "configuration",identity.configuration,"spring",identity.spring, ...
    "damper",identity.damper,"derivedStaticGeometry",identity.derivedStaticGeometry, ...
    "metadata",struct,"identity",identity);
isValid = fsd.model.validateSpringDamperModel(model);
end
