function frame = bodyRollRoadFrame(bodyRollAngle_rad)
%BODYROLLROADFRAME Road directions expressed in rolled chassis coordinates.

if ~isnumeric(bodyRollAngle_rad) || ~isreal(bodyRollAngle_rad) || ...
        ~isscalar(bodyRollAngle_rad) || ~isfinite(bodyRollAngle_rad) || ...
        abs(bodyRollAngle_rad) >= pi / 2
    error("fsd:geometry:InvalidBodyRollAngle", ...
        "bodyRollAngle_rad must satisfy abs(angle)<pi/2.");
end
phi = double(bodyRollAngle_rad);
direction_yz = [cos(phi), -sin(phi)];
normal_yz = [sin(phi), cos(phi)];
frame = struct( ...
    "schemaVersion", "0.6.0", ...
    "kind", "BodyRollRoadFrame", ...
    "bodyRollAngle_rad", phi, ...
    "direction_yz", direction_yz, ...
    "normal_yz", normal_yz, ...
    "chassisToRoadRotation", fsd.geometry.rotationMatrixX(phi));
end
