function constraint = frontViewKinematicConstraint( ...
    pivotFwd_m, pivotAft_m, ballJoint_m)
%FRONTVIEWKINEMATICCONSTRAINT Project one wishbone's instantaneous motion.

pivotFwd_m = validatePoint(pivotFwd_m, "pivotFwd_m");
pivotAft_m = validatePoint(pivotAft_m, "pivotAft_m");
ballJoint_m = validatePoint(ballJoint_m, "ballJoint_m");
tolerances = fsd.model.numericTolerances();
axisVector_m = pivotAft_m - pivotFwd_m;
scale_m = max([norm(pivotFwd_m, 2), norm(pivotAft_m, 2), ...
    norm(ballJoint_m, 2), 1]);
lengthTolerance_m = tolerances.AbsTol_m + tolerances.RelTol * scale_m;
axisLength_m = norm(axisVector_m, 2);
if axisLength_m <= lengthTolerance_m
    constraint = degenerateConstraint("PIVOT_AXIS", ...
        "The two inboard pivots do not define an axis.");
    return
end

axisDirection = axisVector_m ./ axisLength_m;
axisPoint_m = pivotFwd_m + dot( ...
    ballJoint_m - pivotFwd_m, axisDirection) * axisDirection;
radialVector_m = ballJoint_m - axisPoint_m;
radialLength_m = norm(radialVector_m, 2);
if radialLength_m <= lengthTolerance_m
    constraint = degenerateConstraint("BALL_JOINT_ON_AXIS", ...
        "The ball joint lies on the inboard pivot axis.");
    return
end

velocityVector = cross(axisDirection, radialVector_m);
velocityMagnitude = norm(velocityVector, 2);
projectedVelocity = velocityVector(2:3);
projectedMagnitude = norm(projectedVelocity, 2);
if projectedMagnitude <= tolerances.AbsTol_m + ...
        tolerances.RelTol * max([velocityMagnitude, 1])
    constraint = degenerateConstraint("PROJECTED_VELOCITY", ...
        "Ball-joint instantaneous velocity is degenerate in front view.");
    constraint.pivotAxisPoint_m = axisPoint_m;
    constraint.pivotAxisDirection = axisDirection;
    constraint.radialVector_m = radialVector_m;
    constraint.velocityDirection3d = velocityVector ./ velocityMagnitude;
    return
end

projectedVelocityDirection = projectedVelocity ./ projectedMagnitude;
coefficients = [projectedVelocityDirection, ...
    -dot(projectedVelocityDirection, ballJoint_m(2:3))];
coefficients = canonicalize(coefficients);
lineDirection = [coefficients(2), -coefficients(1)];
line = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "LineYZ", ...
    "status", "FINITE", ...
    "homogeneousLine", coefficients, ...
    "coefficients", coefficients, ...
    "point_yz_m", -coefficients(3) * coefficients(1:2), ...
    "direction_yz", lineDirection, ...
    "diagnostic", "");
constraint = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "FrontViewKinematicConstraint", ...
    "status", "FINITE", ...
    "degeneracy", "", ...
    "pivotAxisPoint_m", axisPoint_m, ...
    "pivotAxisDirection", axisDirection, ...
    "radialVector_m", radialVector_m, ...
    "velocityDirection3d", velocityVector ./ velocityMagnitude, ...
    "projectedVelocityDirection_yz", projectedVelocityDirection, ...
    "line", line, ...
    "diagnostic", "");
end

function point_m = validatePoint(value, name)
if ~isnumeric(value) || ~isreal(value) || ...
        ~isequal(size(value), [1, 3]) || any(~isfinite(value))
    error("fsd:geometry:InvalidPoint", ...
        "%s must be a finite real 1-by-3 point in metres.", name);
end
point_m = double(value);
end

function coefficients = canonicalize(coefficients)
threshold = 100 * eps(max([abs(coefficients), 1]));
first = find(abs(coefficients) > threshold, 1);
if ~isempty(first) && coefficients(first) < 0
    coefficients = -coefficients;
end
end

function constraint = degenerateConstraint(degeneracy, diagnostic)
line = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "LineYZ", ...
    "status", "DEGENERATE", ...
    "homogeneousLine", [NaN, NaN, NaN], ...
    "coefficients", [NaN, NaN, NaN], ...
    "point_yz_m", [NaN, NaN], ...
    "direction_yz", [NaN, NaN], ...
    "diagnostic", diagnostic);
constraint = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "FrontViewKinematicConstraint", ...
    "status", "DEGENERATE", ...
    "degeneracy", degeneracy, ...
    "pivotAxisPoint_m", [NaN, NaN, NaN], ...
    "pivotAxisDirection", [NaN, NaN, NaN], ...
    "radialVector_m", [NaN, NaN, NaN], ...
    "velocityDirection3d", [NaN, NaN, NaN], ...
    "projectedVelocityDirection_yz", [NaN, NaN], ...
    "line", line, ...
    "diagnostic", diagnostic);
end
