function intersection = intersectLinesYZ(lineA, lineB)
%INTERSECTLINESYZ Intersect normalized YZ lines projectively.

validateLine(lineA, "lineA");
validateLine(lineB, "lineB");
if string(lineA.status) ~= "FINITE" || string(lineB.status) ~= "FINITE"
    intersection = resultStruct("DEGENERATE", ...
        [NaN, NaN, NaN], [NaN, NaN], [NaN, NaN], NaN, false, ...
        "Both source lines must be valid Euclidean lines.");
    return
end

coefficientsA = double(lineA.homogeneousLine);
coefficientsB = double(lineB.homogeneousLine);
rawPoint = cross(coefficientsA, coefficientsB);
conditioning = abs(rawPoint(3));
parallelTolerance = 100 * eps;
illConditionedTolerance = sqrt(eps);

if conditioning <= parallelTolerance
    coincidenceError = min(norm(coefficientsA - coefficientsB, 2), ...
        norm(coefficientsA + coefficientsB, 2));
    if coincidenceError <= 1000 * eps(max([abs(coefficientsA), ...
            abs(coefficientsB), 1]))
        intersection = resultStruct("COINCIDENT", ...
            [NaN, NaN, NaN], [NaN, NaN], [NaN, NaN], ...
            conditioning, false, "The two YZ lines are coincident.");
    else
        direction = normalizeDirection(rawPoint(1:2), coefficientsA);
        intersection = resultStruct("INFINITE", ...
            [direction, 0], [NaN, NaN], direction, conditioning, false, ...
            "The two YZ lines intersect at infinity.");
    end
    return
end

point_yz_m = rawPoint(1:2) ./ rawPoint(3);
homogeneousPoint = [point_yz_m, 1];
isIllConditioned = conditioning <= illConditionedTolerance;
diagnostic = "";
if isIllConditioned
    diagnostic = "Finite intersection is numerically ill-conditioned.";
end
intersection = resultStruct("FINITE", homogeneousPoint, point_yz_m, ...
    [NaN, NaN], conditioning, isIllConditioned, diagnostic);
end

function direction = normalizeDirection(rawDirection, line)
directionNorm = norm(rawDirection, 2);
if directionNorm <= realmin
    direction = [line(2), -line(1)];
else
    direction = rawDirection ./ directionNorm;
end
threshold = 100 * eps;
first = find(abs(direction) > threshold, 1);
if ~isempty(first) && direction(first) < 0
    direction = -direction;
end
end

function validateLine(line, name)
if ~isstruct(line) || ~isscalar(line) || ...
        ~all(isfield(line, ["kind", "status", "homogeneousLine"])) || ...
        string(line.kind) ~= "LineYZ" || ...
        ~ismember(string(line.status), ["FINITE", "DEGENERATE"])
    error("fsd:geometry:InvalidLineYZ", ...
        "%s must satisfy the LineYZ contract.", name);
end
if string(line.status) == "FINITE" && ...
        (~isnumeric(line.homogeneousLine) || ...
        ~isreal(line.homogeneousLine) || ...
        ~isequal(size(line.homogeneousLine), [1, 3]) || ...
        any(~isfinite(line.homogeneousLine)) || ...
        abs(norm(line.homogeneousLine(1:2), 2) - 1) > 1000 * eps)
    error("fsd:geometry:InvalidLineYZ", ...
        "%s must contain a normalized finite homogeneous line.", name);
end
end

function result = resultStruct(status, homogeneousPoint, point_yz_m, ...
        direction_yz, conditioning, isIllConditioned, diagnostic)
result = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "ProjectiveIntersectionYZ", ...
    "status", status, ...
    "homogeneousPoint", homogeneousPoint, ...
    "point_yz_m", point_yz_m, ...
    "y_m", point_yz_m(1), ...
    "z_m", point_yz_m(2), ...
    "direction_yz", direction_yz, ...
    "conditioning", conditioning, ...
    "isIllConditioned", logical(isIllConditioned), ...
    "diagnostic", diagnostic);
end
