function line = lineYZFromPoints(pointA_yz_m, pointB_yz_m)
%LINEYZFROMPOINTS Define a normalized homogeneous YZ line.

pointA_yz_m = validatePoint(pointA_yz_m, "pointA_yz_m");
pointB_yz_m = validatePoint(pointB_yz_m, "pointB_yz_m");
tolerances = fsd.model.numericTolerances();
scale_m = max([norm(pointA_yz_m, 2), norm(pointB_yz_m, 2), 1]);
if norm(pointB_yz_m - pointA_yz_m, 2) <= ...
        tolerances.AbsTol_m + tolerances.RelTol * scale_m
    line = lineStruct("DEGENERATE", [NaN, NaN, NaN], ...
        "Two distinct YZ points are required to define a line.");
    return
end
line = fsd.geometry.lineYZFromHomogeneousPoints( ...
    [pointA_yz_m, 1], [pointB_yz_m, 1]);
end

function point_yz_m = validatePoint(value, name)
if ~isnumeric(value) || ~isreal(value) || ...
        ~isequal(size(value), [1, 2]) || any(~isfinite(value))
    error("fsd:geometry:InvalidPointYZ", ...
        "%s must be a finite real 1-by-2 [Y,Z] point.", name);
end
point_yz_m = double(value);
end

function line = lineStruct(status, coefficients, diagnostic)
line = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "LineYZ", ...
    "status", status, ...
    "homogeneousLine", coefficients, ...
    "coefficients", coefficients, ...
    "point_yz_m", [NaN, NaN], ...
    "direction_yz", [NaN, NaN], ...
    "diagnostic", diagnostic);
end
