function line = lineYZFromHomogeneousPoints(pointA, pointB)
%LINEYZFROMHOMOGENEOUSPOINTS Join two projective YZ points.

pointA = validatePoint(pointA, "pointA");
pointB = validatePoint(pointB, "pointB");
coefficients = cross(pointA, pointB);
normalMagnitude = norm(coefficients(1:2), 2);
scale = max([norm(pointA, 2) * norm(pointB, 2), 1]);
if normalMagnitude <= 100 * eps(scale)
    line = lineStruct("DEGENERATE", [NaN, NaN, NaN], ...
        "The homogeneous points do not define a unique Euclidean line.");
    return
end
coefficients = coefficients ./ normalMagnitude;
coefficients = canonicalize(coefficients);
point_yz_m = -coefficients(3) * coefficients(1:2);
direction_yz = [coefficients(2), -coefficients(1)];
line = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "LineYZ", ...
    "status", "FINITE", ...
    "homogeneousLine", coefficients, ...
    "coefficients", coefficients, ...
    "point_yz_m", point_yz_m, ...
    "direction_yz", direction_yz, ...
    "diagnostic", "");
end

function point = validatePoint(value, name)
if ~isnumeric(value) || ~isreal(value) || ...
        ~isequal(size(value), [1, 3]) || any(~isfinite(value)) || ...
        norm(double(value), 2) == 0
    error("fsd:geometry:InvalidHomogeneousPoint", ...
        "%s must be a finite nonzero homogeneous 1-by-3 point.", name);
end
point = double(value);
end

function coefficients = canonicalize(coefficients)
threshold = 100 * eps(max([abs(coefficients), 1]));
first = find(abs(coefficients) > threshold, 1);
if ~isempty(first) && coefficients(first) < 0
    coefficients = -coefficients;
end
end

function line = lineStruct(status, coefficients, diagnostic)
line = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "LineYZ", ...
    "status", status, ...
    "homogeneousLine", coefficients, ...
    "coefficients", coefficients, ...
    "point_yz_m", [NaN, NaN], ...
    "direction_yz", [NaN, NaN], ...
    "diagnostic", diagnostic);
end
