function line = roadLineFromContacts(leftContact_m, rightContact_m)
%ROADLINEFROMCONTACTS Construct a +Z-normal road line from bilateral contacts.

leftContact_m = validateContact(leftContact_m, "leftContact_m");
rightContact_m = validateContact(rightContact_m, "rightContact_m");
chord_yz = rightContact_m(2:3) - leftContact_m(2:3);
tolerances = fsd.model.numericTolerances();
scale_m = max([norm(leftContact_m(2:3)), ...
    norm(rightContact_m(2:3)), 1]);
tolerance_m = tolerances.AbsTol_m + tolerances.RelTol * scale_m;
length_m = norm(chord_yz);
if length_m <= tolerance_m
    line = invalidLine("COINCIDENT_CONTACTS", ...
        "Bilateral contacts do not define a road line.");
    return
end
direction = chord_yz ./ length_m;
if direction(1) <= tolerances.RelTol
    line = invalidLine("INVERTED_CONTACT_ORDER", ...
        "The right contact must remain to the right of the left contact.");
    return
end
normal = [-direction(2), direction(1)];
midpoint = 0.5 * (leftContact_m(2:3) + rightContact_m(2:3));
coefficients = [normal, -dot(normal, midpoint)];
line = struct( ...
    "schemaVersion", "0.6.0", ...
    "kind", "RoadLineYZ", ...
    "status", "FINITE", ...
    "coefficients", coefficients, ...
    "homogeneousLine", coefficients, ...
    "direction_yz", direction, ...
    "point_yz_m", midpoint, ...
    "contactSeparation_m", length_m, ...
    "diagnostic", "");
end

function point = validateContact(value, name)
if ~isnumeric(value) || ~isreal(value) || ...
        ~isequal(size(value), [1, 3]) || any(~isfinite(value))
    error("fsd:geometry:InvalidContact", ...
        "%s must be a finite real 1-by-3 point.", name);
end
point = double(value);
end

function line = invalidLine(status, diagnostic)
line = struct( ...
    "schemaVersion", "0.6.0", ...
    "kind", "RoadLineYZ", ...
    "status", status, ...
    "coefficients", [NaN, NaN, NaN], ...
    "homogeneousLine", [NaN, NaN, NaN], ...
    "direction_yz", [NaN, NaN], ...
    "point_yz_m", [NaN, NaN], ...
    "contactSeparation_m", NaN, ...
    "diagnostic", diagnostic);
end
