function line = roadLineFromBodyRoll(bodyRollAngle_rad, referencePoint_yz_m)
%ROADLINEFROMBODYROLL Construct the target road line through a YZ point.

frame = fsd.geometry.bodyRollRoadFrame(bodyRollAngle_rad);
referencePoint_yz_m = validatePoint(referencePoint_yz_m);
normal = frame.normal_yz;
c = -dot(normal, referencePoint_yz_m);
line = roadLine("FINITE", [normal, c], frame.direction_yz, ...
    referencePoint_yz_m, "");
end

function point = validatePoint(value)
if ~isnumeric(value) || ~isreal(value) || ...
        ~isequal(size(value), [1, 2]) || any(~isfinite(value))
    error("fsd:geometry:InvalidPointYZ", ...
        "referencePoint_yz_m must be a finite real 1-by-2 point.");
end
point = double(value);
end

function line = roadLine(status, coefficients, direction, point, diagnostic)
line = struct( ...
    "schemaVersion", "0.6.0", ...
    "kind", "RoadLineYZ", ...
    "status", status, ...
    "coefficients", coefficients, ...
    "homogeneousLine", coefficients, ...
    "direction_yz", direction, ...
    "point_yz_m", point, ...
    "contactSeparation_m", NaN, ...
    "diagnostic", diagnostic);
end
