function rotatedPoints_m = rotatePointsAboutAxis( ...
    points_m, axisPoint_m, axisDirection, angle_rad)
%ROTATEPOINTSABOUTAXIS Rotate points about an oriented 3-D line.

if ~isnumeric(axisPoint_m) || ~isreal(axisPoint_m) || ...
        ~isequal(size(axisPoint_m), [1, 3]) || any(~isfinite(axisPoint_m))
    error("fsd:geometry:InvalidAxisPoint", ...
        "axisPoint_m must be a finite real 1-by-3 vector.");
end
rotationMatrix = fsd.geometry.rotationMatrixAboutAxis( ...
    axisDirection, angle_rad);
rotatedPoints_m = fsd.geometry.transformPointsRigid( ...
    points_m, double(axisPoint_m), [0, 0, 0], rotationMatrix);
end
