function distance_m = signedDistanceToRoadLine(point_yz_m, roadLine)
%SIGNEDDISTANCETOROADLINE Signed perpendicular distance to a normalized road.

if ~isnumeric(point_yz_m) || ~isreal(point_yz_m) || ...
        ~isequal(size(point_yz_m), [1, 2]) || any(~isfinite(point_yz_m))
    error("fsd:geometry:InvalidPointYZ", ...
        "point_yz_m must be a finite real 1-by-2 point.");
end
if ~isstruct(roadLine) || ~isscalar(roadLine) || ...
        ~all(isfield(roadLine, ["kind", "status", "coefficients"])) || ...
        string(roadLine.kind) ~= "RoadLineYZ" || ...
        string(roadLine.status) ~= "FINITE" || ...
        ~isnumeric(roadLine.coefficients) || ...
        ~isequal(size(roadLine.coefficients), [1, 3]) || ...
        any(~isfinite(roadLine.coefficients)) || ...
        abs(norm(roadLine.coefficients(1:2)) - 1) > 1000 * eps
    error("fsd:geometry:InvalidRoadLine", ...
        "roadLine must be a finite normalized RoadLineYZ.");
end
distance_m = dot(roadLine.coefficients, [double(point_yz_m), 1]);
end
