function metrics = staticMetrics(geometry)
%STATICMETRICS Compute elementary static dimensions.

fsd.model.validateDoubleWishboneGeometry(geometry);
prefix = geometry.cornerId + "_";
metrics = struct();
metrics.ucaInboardAxisLength_m = fsd.geometry.distanceBetweenPoints( ...
    geometry, prefix + "UCA_FWD_CHASSIS", prefix + "UCA_AFT_CHASSIS");
metrics.lcaInboardAxisLength_m = fsd.geometry.distanceBetweenPoints( ...
    geometry, prefix + "LCA_FWD_CHASSIS", prefix + "LCA_AFT_CHASSIS");
metrics.ubjLbjDistance_m = fsd.geometry.distanceBetweenPoints( ...
    geometry, prefix + "UBJ", prefix + "LBJ");
metrics.wheelCenterContactPatchDistance_m = ...
    fsd.geometry.distanceBetweenPoints(geometry, ...
    prefix + "WHEEL_CENTER", prefix + "CONTACT_PATCH");
metrics.tieRodLength_m = fsd.geometry.distanceBetweenPoints(geometry, ...
    prefix + "TIE_ROD_INBOARD", prefix + "TIE_ROD_OUTBOARD");
end
