function transformedPoints_m = transformPointsRigid( ...
    points_m, referencePoint_m, translation_m, rotationMatrix)
%TRANSFORMPOINTSRIGID Apply one rigid transform about a reference point.

if ~isnumeric(points_m) || ~isreal(points_m) || ...
        ~ismatrix(points_m) || size(points_m, 2) ~= 3 || ...
        any(~isfinite(points_m), "all")
    error("fsd:geometry:InvalidPoints", ...
        "points_m must be a finite real N-by-3 matrix.");
end
if ~isnumeric(referencePoint_m) || ~isreal(referencePoint_m) || ...
        ~isequal(size(referencePoint_m), [1, 3]) || ...
        any(~isfinite(referencePoint_m))
    error("fsd:geometry:InvalidReferencePoint", ...
        "referencePoint_m must be a finite real 1-by-3 vector.");
end
if ~isnumeric(translation_m) || ~isreal(translation_m) || ...
        ~isequal(size(translation_m), [1, 3]) || ...
        any(~isfinite(translation_m))
    error("fsd:geometry:InvalidTranslation", ...
        "translation_m must be a finite real 1-by-3 vector.");
end
if ~isnumeric(rotationMatrix) || ~isreal(rotationMatrix) || ...
        ~isequal(size(rotationMatrix), [3, 3]) || ...
        any(~isfinite(rotationMatrix), "all")
    error("fsd:geometry:InvalidRotationMatrix", ...
        "rotationMatrix must be a finite real 3-by-3 matrix.");
end

tolerances = fsd.model.numericTolerances();
matrixError = norm(rotationMatrix' * rotationMatrix - eye(3), "fro");
determinantError = abs(det(rotationMatrix) - 1);
rotationTolerance = 10 * tolerances.RelTol;
if matrixError > rotationTolerance || determinantError > rotationTolerance
    error("fsd:geometry:InvalidRotationMatrix", ...
        "rotationMatrix must be a proper orthonormal rotation.");
end

centeredPoints_m = double(points_m) - double(referencePoint_m);
transformedPoints_m = double(referencePoint_m) + double(translation_m) + ...
    (double(rotationMatrix) * centeredPoints_m')';
end
