classdef TestSteeringKinematics < matlab.unittest.TestCase
    properties
        OriginalPath
    end

    methods (TestMethodSetup)
        function addSourceToPath(testCase)
            root = fileparts(fileparts(mfilename("fullpath")));
            testCase.OriginalPath = path;
            testCase.addTeardown(@() path(testCase.OriginalPath));
            addpath(fullfile(root, "src"));
        end
    end

    methods (Test)
        function zeroRackMatchesExistingBumpSolver(testCase)
            steering = testCase.system();
            travel_mm = [12, -7];
            result = fsd.kinematics.solveSteering( ...
                steering, 0, travel_mm, "mm");
            left = fsd.kinematics.solveBump( ...
                steering.frontAxleGeometry.leftGeometry, travel_mm(1), "mm");
            right = fsd.kinematics.solveBump( ...
                steering.frontAxleGeometry.rightGeometry, travel_mm(2), "mm");
            testCase.verifyTrue(result.converged, result.failureReason);
            testCase.verifyEqual(result.leftResult.state, left.state, ...
                "AbsTol", 2e-12);
            testCase.verifyEqual(result.rightResult.state, right.state, ...
                "AbsTol", 2e-12);
            testCase.verifyEqual(result.leftResult.uprightPose.rotationMatrix, ...
                left.uprightPose.rotationMatrix, "AbsTol", 2e-12);
            testCase.verifyEqual(result.rightResult.wheelAxis, ...
                right.wheelAxis, "AbsTol", 2e-12);
        end

        function rackTranslatesBothInnerJointsRigidly(testCase)
            steering = testCase.system();
            q_m = 0.006;
            result = fsd.kinematics.solveSteering( ...
                steering, q_m, 0, "m");
            rack = steering.rackGeometry;
            testCase.assertTrue(result.converged, result.failureReason);
            testCase.verifyEqual(result.leftResult.tieRodInboardCurrent_m, ...
                rack.leftInnerStatic_m + q_m * rack.axisDirection, ...
                "AbsTol", 1e-15);
            testCase.verifyEqual(result.rightResult.tieRodInboardCurrent_m, ...
                rack.rightInnerStatic_m + q_m * rack.axisDirection, ...
                "AbsTol", 1e-15);
            testCase.verifyEqual(norm( ...
                result.rightResult.tieRodInboardCurrent_m - ...
                result.leftResult.tieRodInboardCurrent_m), ...
                rack.jointSeparation_m, "AbsTol", 1e-14);
        end

        function combinedBumpAndSteeringSatisfiesConstraints(testCase)
            steering = testCase.system();
            result = fsd.kinematics.solveSteering( ...
                steering, -8, [15, 10], "mm");
            testCase.assertTrue(result.converged, result.failureReason);
            testCase.verifyTrue( ...
                fsd.kinematics.validateSteeringResult(result, steering));
            testCase.verifyEqual(result.leftResult.achievedWheelTravel_m, ...
                0.015, "AbsTol", 2e-9);
            testCase.verifyEqual(result.rightResult.achievedWheelTravel_m, ...
                0.010, "AbsTol", 2e-9);
            testCase.verifyEqual(norm(result.leftResult.wheelAxis), 1, ...
                "AbsTol", 1e-12);
            testCase.verifyTrue(all(isfinite( ...
                result.leftResult.geometricContact.point_m)));
            testCase.verifyTrue(result.diagnostics.bilateralConverged);
            testCase.verifyEqual(result.diagnostics.left, ...
                result.leftResult.diagnostics);
            testCase.verifyEqual(result.diagnostics.right, ...
                result.rightResult.diagnostics);
        end

        function rackSweepUsesContinuationAndRoundTrips(testCase)
            steering = testCase.system();
            travel_mm = [0; 12; 0; -12; 0];
            sweep = fsd.kinematics.solveRackSweep( ...
                steering, travel_mm, 5, "mm");
            testCase.verifyTrue(sweep.allConverged);
            testCase.verifyTrue( ...
                fsd.kinematics.validateRackSweepResult(sweep, steering));
            testCase.verifyEqual(sweep.results(3).leftResult.state.xyz_m, ...
                sweep.results(1).leftResult.state.xyz_m, "AbsTol", 2e-8);
            testCase.verifyEqual(sweep.results(5).rightResult.state.xyz_m, ...
                sweep.results(1).rightResult.state.xyz_m, "AbsTol", 2e-8);
        end

        function impossibleRackTravelFailsExplicitly(testCase)
            steering = testCase.system();
            sweep = fsd.kinematics.solveRackSweep( ...
                steering, [0; 500; 5], 0, "mm");
            testCase.verifyEqual(sweep.status, ...
                ["CONVERGED"; "NO_CONVERGENCE"; "NOT_ATTEMPTED"]);
            testCase.verifyTrue(all(isnan( ...
                sweep.results(2).leftResult.state.xyz_m), "all"));
            testCase.verifyTrue(all(isnan(sweep.results(2).leftResult. ...
                geometricContact.point_m)));
        end

        function rejectsResultFromDifferentSystem(testCase)
            first = testCase.system();
            second = fsd.model.createSteeringSystem( ...
                first.frontAxleGeometry, 1.7, "m");
            result = fsd.kinematics.solveSteering(first, 5, 0, "mm");
            testCase.verifyError(@() ...
                fsd.kinematics.validateSteeringResult(result, second), ...
                "fsd:kinematics:InvalidSteeringResult");
        end

        function rejectsTamperedPoseAndContact(testCase)
            steering = testCase.system();
            result = fsd.kinematics.solveSteering(steering, 5, 0, "mm");
            poseTampered = result;
            poseTampered.leftResult.uprightPose.rotationVector_rad(1) = ...
                poseTampered.leftResult.uprightPose.rotationVector_rad(1) + ...
                1e-3;
            testCase.verifyError(@() fsd.kinematics.validateSteeringResult( ...
                poseTampered, steering), ...
                "fsd:kinematics:InvalidSteeringResult");

            contactTampered = result;
            contactTampered.rightResult.geometricContact.point_m(2) = ...
                contactTampered.rightResult.geometricContact.point_m(2) + ...
                1e-3;
            testCase.verifyError(@() fsd.kinematics.validateSteeringResult( ...
                contactTampered, steering), ...
                "fsd:kinematics:InvalidSteeringResult");
        end
    end

    methods (Static, Access = private)
        function steering = system()
            steering = fsd.model.createSteeringSystem( ...
                analyticAxleFixture(false), 1.6, "m");
        end
    end
end
