function result = composeAxleTravelResult(axle, requested_m, left, right, elapsed_s)
%COMPOSEAXLETRAVELRESULT Compose one v0.6 asymmetric axle state.

converged = left.converged && right.converged;
if converged
    status = "CONVERGED";
    failureReason = "";
elseif string(left.status) == "NOT_ATTEMPTED" && ...
        string(right.status) == "NOT_ATTEMPTED"
    status = "NOT_ATTEMPTED";
    failureReason = "Neither corner target was attempted.";
else
    status = "NO_CONVERGENCE";
    failureReason = "At least one corner did not converge.";
end
result = struct( ...
    "schemaVersion", "0.6.0", ...
    "kind", "AxleTravelResult", ...
    "axleIdentity", fsd.model.axleIdentity(axle), ...
    "requestedWheelTravel_m", reshape(double(requested_m), 1, 2), ...
    "converged", logical(converged), ...
    "status", status, ...
    "failureReason", failureReason, ...
    "leftConverged", logical(left.converged), ...
    "rightConverged", logical(right.converged), ...
    "leftResult", left, ...
    "rightResult", right, ...
    "diagnostics", struct("left", left.diagnostics, ...
        "right", right.diagnostics, ...
        "bilateralConverged", logical(converged)), ...
    "elapsedTime_s", double(elapsed_s));
end
