function result = kinematicResultFromRaw(raw)
%KINEMATICRESULTFROMRAW Adapt a static-tie solve to the v0.3 contract.

result = struct( ...
    "schemaVersion", "0.3.0", ...
    "kind", "KinematicResult", ...
    "geometryIdentity", raw.geometryIdentity, ...
    "requestedWheelTravel_m", raw.requestedWheelTravel_m, ...
    "achievedWheelTravel_m", raw.achievedWheelTravel_m, ...
    "converged", raw.converged, ...
    "status", raw.status, ...
    "failureReason", raw.failureReason, ...
    "state", raw.state, ...
    "uprightPose", raw.uprightPose, ...
    "wheelAxis", raw.wheelAxis, ...
    "camber_rad", raw.camber_rad, ...
    "diagnostics", raw.diagnostics);
end
