function results = solveBumpPath(geometry, targets_m, settings)
%SOLVEBUMPPATH Solve ordered wheel-travel targets with continuation.

if exist("fsolve", "file") ~= 2 || ~license("test", "Optimization_Toolbox")
    error("fsd:kinematics:MissingOptimizationToolbox", ...
        "v0.2 bump kinematics requires Optimization Toolbox fsolve.");
end

mechanism = buildMechanism(geometry);
solverOptions = optimoptions("fsolve", ...
    "Display", "off", ...
    "Algorithm", "trust-region-dogleg", ...
    "FunctionTolerance", settings.FunctionTolerance, ...
    "StepTolerance", settings.StepTolerance, ...
    "OptimalityTolerance", settings.OptimalityTolerance, ...
    "MaxIterations", settings.MaxIterations, ...
    "MaxFunctionEvaluations", settings.MaxFunctionEvaluations);

targets_m = targets_m(:);
resultCells = cell(numel(targets_m), 1);
unknowns = zeros(5, 1);
currentTravel_m = 0;
branchAvailable = true;

for targetIndex = 1:numel(targets_m)
    target_m = targets_m(targetIndex);
    diagnostics = emptyDiagnostics(mechanism);

    if ~branchAvailable
        diagnostics.message = "Not attempted after an earlier continuation failure.";
        resultCells{targetIndex} = failureResult( ...
            mechanism, target_m, "NOT_ATTEMPTED", diagnostics);
        continue
    end

    diagnostics.attempted = true;

    travelIncrement_m = target_m - currentTravel_m;
    if travelIncrement_m == 0
        resultCells{targetIndex} = convergedResult( ...
            mechanism, target_m, unknowns, diagnostics);
        continue
    end

    stepCount = max(1, ceil(abs(travelIncrement_m) / ...
        settings.MaxContinuationStep_m));
    stepTargets_m = currentTravel_m + ...
        (1:stepCount)' / stepCount * travelIncrement_m;
    targetConverged = true;

    for stepIndex = 1:stepCount
        stepTarget_m = stepTargets_m(stepIndex);
        residualFunction = @(candidate) constraintResiduals( ...
            candidate, stepTarget_m, mechanism);
        [candidate, residual, exitFlag, output] = fsolve( ...
            residualFunction, unknowns, solverOptions);
        lengthErrors_m = constraintLengthErrors( ...
            candidate, stepTarget_m, mechanism);

        diagnostics.iterations = diagnostics.iterations + output.iterations;
        diagnostics.functionEvaluations = diagnostics.functionEvaluations + ...
            output.funcCount;
        diagnostics.continuationSteps = diagnostics.continuationSteps + 1;
        diagnostics.exitFlag = exitFlag;
        diagnostics.residualVector = residual(:);
        diagnostics.residualNorm = norm(residual, 2);
        diagnostics.maxResidual = max(abs(residual));
        diagnostics.lengthErrors_m = lengthErrors_m;
        diagnostics.maxConstraintError_m = max(abs(lengthErrors_m));
        diagnostics.message = string(output.message);

        constraintTolerance_m = mechanism.constraintTolerance_m;
        if exitFlag <= 0 || any(~isfinite(candidate)) || ...
                any(~isfinite(residual)) || ...
                diagnostics.maxConstraintError_m > constraintTolerance_m
            targetConverged = false;
            break
        end

        unknowns = candidate(:);
        currentTravel_m = stepTarget_m;
    end

    if targetConverged
        tolerances = fsd.model.numericTolerances();
        if target_m == 0 && norm(unknowns, 2) <= ...
                10 * tolerances.RelTol
            unknowns = zeros(5, 1);
        end
        currentTravel_m = target_m;
        resultCells{targetIndex} = convergedResult( ...
            mechanism, target_m, unknowns, diagnostics);
    else
        resultCells{targetIndex} = failureResult( ...
            mechanism, target_m, "NO_CONVERGENCE", diagnostics);
        branchAvailable = false;
    end
end
results = vertcat(resultCells{:});
end

function mechanism = buildMechanism(geometry)
prefix = geometry.cornerId + "_";
pointIds = prefix + [ ...
    "UBJ"; "LBJ"; "TIE_ROD_OUTBOARD"; ...
    "WHEEL_CENTER"; "CONTACT_PATCH"];
movingStatic_m = zeros(numel(pointIds), 3);
for index = 1:numel(pointIds)
    movingStatic_m(index, :) = fsd.model.getPoint(geometry, pointIds(index));
end

fixedIds = prefix + [ ...
    "UCA_FWD_CHASSIS"; "UCA_AFT_CHASSIS"; ...
    "LCA_FWD_CHASSIS"; "LCA_AFT_CHASSIS"; ...
    "TIE_ROD_INBOARD"];
fixed_m = zeros(numel(fixedIds), 3);
for index = 1:numel(fixedIds)
    fixed_m(index, :) = fsd.model.getPoint(geometry, fixedIds(index));
end

movingConstraintRows = [1; 1; 2; 2; 3];
staticConstraintPoints_m = movingStatic_m(movingConstraintRows, :);
linkLengths_m = sqrt(sum((staticConstraintPoints_m - fixed_m).^2, 2));
tolerances = fsd.model.numericTolerances();

mechanism = struct( ...
    "geometryIdentity", fsd.model.geometryIdentity(geometry), ...
    "cornerId", geometry.cornerId, ...
    "pointIds", pointIds, ...
    "movingStatic_m", movingStatic_m, ...
    "wheelCenterStatic_m", movingStatic_m(4, :), ...
    "wheelAxisStatic", geometry.wheel.wheelAxis, ...
    "fixedIds", fixedIds, ...
    "fixed_m", fixed_m, ...
    "movingConstraintRows", movingConstraintRows, ...
    "linkLengths_m", linkLengths_m, ...
    "constraintIds", [ ...
    "UCA_FWD"; "UCA_AFT"; "LCA_FWD"; "LCA_AFT"; "TIE_ROD"], ...
    "constraintTolerance_m", tolerances.AbsTol_m + ...
    tolerances.RelTol * max([linkLengths_m; 1]));
end

function residual = constraintResiduals(unknowns, wheelTravel_m, mechanism)
lengthErrors_m = constraintLengthErrors( ...
    unknowns, wheelTravel_m, mechanism);
residual = lengthErrors_m ./ mechanism.linkLengths_m;
end

function lengthErrors_m = constraintLengthErrors( ...
    unknowns, wheelTravel_m, mechanism)
[currentPoints_m, ~, ~, ~] = evaluatePose( ...
    unknowns, wheelTravel_m, mechanism);
constraintPoints_m = currentPoints_m(mechanism.movingConstraintRows, :);
currentLengths_m = sqrt(sum( ...
    (constraintPoints_m - mechanism.fixed_m).^2, 2));
lengthErrors_m = currentLengths_m - mechanism.linkLengths_m;
end

function [currentPoints_m, rotationMatrix, translation_m, wheelAxis] = ...
        evaluatePose(unknowns, wheelTravel_m, mechanism)
unknowns = unknowns(:);
translation_m = [unknowns(1), unknowns(2), wheelTravel_m];
rotationVector_rad = unknowns(3:5)';
rotationMatrix = fsd.geometry.rotationVectorToMatrix(rotationVector_rad);
currentPoints_m = fsd.geometry.transformPointsRigid( ...
    mechanism.movingStatic_m, mechanism.wheelCenterStatic_m, ...
    translation_m, rotationMatrix);
wheelAxis = (rotationMatrix * mechanism.wheelAxisStatic(:))';
wheelAxis = wheelAxis ./ norm(wheelAxis, 2);
end

function result = convergedResult(mechanism, target_m, unknowns, diagnostics)
[currentPoints_m, rotationMatrix, translation_m, wheelAxis] = ...
    evaluatePose(unknowns, target_m, mechanism);
achievedTravel_m = currentPoints_m(4, 3) - ...
    mechanism.wheelCenterStatic_m(3);
camber_rad = fsd.kinematics.camberFromWheelAxis( ...
    wheelAxis, mechanism.cornerId);

diagnostics.lengthErrors_m = constraintLengthErrors( ...
    unknowns, target_m, mechanism);
diagnostics.maxConstraintError_m = max(abs(diagnostics.lengthErrors_m));
diagnostics.residualVector = diagnostics.lengthErrors_m ./ ...
    mechanism.linkLengths_m;
diagnostics.residualNorm = norm(diagnostics.residualVector, 2);
diagnostics.maxResidual = max(abs(diagnostics.residualVector));
if diagnostics.exitFlag == 0
    diagnostics.exitFlag = 1;
    diagnostics.message = "Exact state reused without a nonlinear solve.";
end

state = stateStruct(mechanism, currentPoints_m, wheelAxis, achievedTravel_m);
pose = struct( ...
    "referencePointStatic_m", mechanism.wheelCenterStatic_m, ...
    "translation_m", translation_m, ...
    "rotationVector_rad", unknowns(3:5)', ...
    "rotationMatrix", rotationMatrix);
result = baseResult(mechanism, target_m, achievedTravel_m, true, ...
    "CONVERGED", "", state, pose, wheelAxis, camber_rad, diagnostics);
end

function result = failureResult(mechanism, target_m, status, diagnostics)
nanPoints = nan(size(mechanism.movingStatic_m));
state = stateStruct(mechanism, nanPoints, [NaN, NaN, NaN], NaN);
pose = struct( ...
    "referencePointStatic_m", mechanism.wheelCenterStatic_m, ...
    "translation_m", [NaN, NaN, NaN], ...
    "rotationVector_rad", [NaN, NaN, NaN], ...
    "rotationMatrix", nan(3));
failureReason = diagnostics.message;
result = baseResult(mechanism, target_m, NaN, false, status, ...
    failureReason, state, pose, [NaN, NaN, NaN], NaN, diagnostics);
end

function result = baseResult(mechanism, requested_m, achieved_m, ...
        converged, status, failureReason, state, pose, wheelAxis, ...
        camber_rad, diagnostics)
result = struct( ...
    "schemaVersion", "0.3.0", ...
    "kind", "KinematicResult", ...
    "geometryIdentity", mechanism.geometryIdentity, ...
    "requestedWheelTravel_m", requested_m, ...
    "achievedWheelTravel_m", achieved_m, ...
    "converged", converged, ...
    "status", status, ...
    "failureReason", failureReason, ...
    "state", state, ...
    "uprightPose", pose, ...
    "wheelAxis", wheelAxis, ...
    "camber_rad", camber_rad, ...
    "diagnostics", diagnostics);
end

function state = stateStruct(mechanism, points_m, wheelAxis, travel_m)
state = struct( ...
    "schemaVersion", "0.2.0", ...
    "kind", "SuspensionState", ...
    "pointIds", mechanism.pointIds, ...
    "xyz_m", points_m, ...
    "ubj_m", points_m(1, :), ...
    "lbj_m", points_m(2, :), ...
    "tieRodOutboard_m", points_m(3, :), ...
    "wheelCenter_m", points_m(4, :), ...
    "contactPatch_m", points_m(5, :), ...
    "wheelAxis", wheelAxis, ...
    "wheelTravel_m", travel_m);
end

function diagnostics = emptyDiagnostics(mechanism)
diagnostics = struct( ...
    "solver", "fsolve", ...
    "toolbox", "Optimization Toolbox", ...
    "attempted", false, ...
    "constraintIds", mechanism.constraintIds, ...
    "lengthErrors_m", zeros(5, 1), ...
    "maxConstraintError_m", 0, ...
    "residualVector", zeros(5, 1), ...
    "residualNorm", 0, ...
    "maxResidual", 0, ...
    "exitFlag", 0, ...
    "iterations", 0, ...
    "functionEvaluations", 0, ...
    "continuationSteps", 0, ...
    "message", "");
end
