function results = solveCornerPath(geometry, wheelTargets_m, ...
    tieInboardTargets_m, settings)
%SOLVECORNERPATH Solve prescribed wheel/tie-inboard targets continuously.

if exist("fsolve", "file") ~= 2 || ~license("test", "Optimization_Toolbox")
    error("fsd:kinematics:MissingOptimizationToolbox", ...
        "Suspension kinematics requires Optimization Toolbox fsolve.");
end
wheelTargets_m = double(wheelTargets_m(:));
if ~isnumeric(tieInboardTargets_m) || ~isreal(tieInboardTargets_m) || ...
        ~isequal(size(tieInboardTargets_m), [numel(wheelTargets_m), 3]) || ...
        any(~isfinite(tieInboardTargets_m), "all")
    error("fsd:kinematics:InvalidTieRodInboardPath", ...
        "tieInboardTargets_m must be a finite N-by-3 matrix.");
end

mechanism = buildMechanism(geometry);
solverOptions = optimoptions("fsolve", ...
    "Display", "off", ...
    "Algorithm", "trust-region-dogleg", ...
    "FunctionTolerance", settings.FunctionTolerance, ...
    "StepTolerance", settings.StepTolerance, ...
    "OptimalityTolerance", settings.OptimalityTolerance, ...
    "MaxIterations", settings.MaxIterations, ...
    "MaxFunctionEvaluations", settings.MaxFunctionEvaluations);

resultCells = cell(numel(wheelTargets_m), 1);
unknowns = zeros(5, 1);
currentTravel_m = 0;
currentTieInboard_m = mechanism.tieInboardStatic_m;
branchAvailable = true;
for targetIndex = 1:numel(wheelTargets_m)
    targetTravel_m = wheelTargets_m(targetIndex);
    targetTieInboard_m = double(tieInboardTargets_m(targetIndex, :));
    diagnostics = emptyDiagnostics(mechanism);
    if ~branchAvailable
        diagnostics.message = ...
            "Not attempted after an earlier continuation failure.";
        resultCells{targetIndex} = failureResult(mechanism, ...
            targetTravel_m, targetTieInboard_m, "NOT_ATTEMPTED", diagnostics);
        continue
    end

    diagnostics.attempted = true;
    travelIncrement_m = targetTravel_m - currentTravel_m;
    tieIncrement_m = targetTieInboard_m - currentTieInboard_m;
    pathMagnitude_m = max(abs(travelIncrement_m), norm(tieIncrement_m, 2));
    if pathMagnitude_m == 0
        resultCells{targetIndex} = convergedResult(mechanism, ...
            targetTravel_m, targetTieInboard_m, unknowns, diagnostics);
        continue
    end

    stepCount = max(1, ceil(pathMagnitude_m / ...
        settings.MaxContinuationStep_m));
    targetConverged = true;
    for stepIndex = 1:stepCount
        fraction = stepIndex / stepCount;
        stepTravel_m = currentTravel_m + fraction * travelIncrement_m;
        stepTieInboard_m = currentTieInboard_m + fraction * tieIncrement_m;
        residualFunction = @(candidate) constraintResiduals( ...
            candidate, stepTravel_m, stepTieInboard_m, mechanism);
        [candidate, residual, exitFlag, output] = fsolve( ...
            residualFunction, unknowns, solverOptions);
        lengthErrors_m = constraintLengthErrors(candidate, stepTravel_m, ...
            stepTieInboard_m, mechanism);
        diagnostics.iterations = diagnostics.iterations + output.iterations;
        diagnostics.functionEvaluations = diagnostics.functionEvaluations + ...
            output.funcCount;
        diagnostics.continuationSteps = diagnostics.continuationSteps + 1;
        diagnostics.exitFlag = exitFlag;
        diagnostics.residualVector = residual(:);
        diagnostics.residualNorm = norm(residual, 2);
        diagnostics.maxResidual = max(abs(residual));
        diagnostics.lengthErrors_m = lengthErrors_m;
        diagnostics.maxConstraintError_m = max(abs(lengthErrors_m));
        diagnostics.message = string(output.message);
        if exitFlag <= 0 || any(~isfinite(candidate)) || ...
                any(~isfinite(residual)) || ...
                diagnostics.maxConstraintError_m > ...
                mechanism.constraintTolerance_m
            targetConverged = false;
            break
        end
        unknowns = candidate(:);
    end

    if targetConverged
        tolerances = fsd.model.numericTolerances();
        if targetTravel_m == 0 && ...
                norm(targetTieInboard_m - mechanism.tieInboardStatic_m) <= ...
                tolerances.AbsTol_m && ...
                norm(unknowns, 2) <= 10 * tolerances.RelTol
            unknowns = zeros(5, 1);
        end
        currentTravel_m = targetTravel_m;
        currentTieInboard_m = targetTieInboard_m;
        resultCells{targetIndex} = convergedResult(mechanism, ...
            targetTravel_m, targetTieInboard_m, unknowns, diagnostics);
    else
        resultCells{targetIndex} = failureResult(mechanism, ...
            targetTravel_m, targetTieInboard_m, ...
            "NO_CONVERGENCE", diagnostics);
        branchAvailable = false;
    end
end
results = vertcat(resultCells{:});
end

function mechanism = buildMechanism(geometry)
prefix = string(geometry.cornerId) + "_";
pointIds = prefix + ["UBJ"; "LBJ"; "TIE_ROD_OUTBOARD"; ...
    "WHEEL_CENTER"; "CONTACT_PATCH"];
movingStatic_m = points(geometry, pointIds);
fixedIds = prefix + ["UCA_FWD_CHASSIS"; "UCA_AFT_CHASSIS"; ...
    "LCA_FWD_CHASSIS"; "LCA_AFT_CHASSIS"];
fixed_m = points(geometry, fixedIds);
tieInboardStatic_m = fsd.model.getPoint(geometry, ...
    prefix + "TIE_ROD_INBOARD");
movingConstraintRows = [1; 1; 2; 2];
staticConstraintPoints_m = movingStatic_m(movingConstraintRows, :);
armLengths_m = sqrt(sum((staticConstraintPoints_m - fixed_m).^2, 2));
tieLength_m = norm(movingStatic_m(3, :) - tieInboardStatic_m, 2);
linkLengths_m = [armLengths_m; tieLength_m];
tolerances = fsd.model.numericTolerances();
mechanism = struct( ...
    "geometryIdentity", fsd.model.geometryIdentity(geometry), ...
    "cornerId", string(geometry.cornerId), ...
    "pointIds", pointIds, ...
    "movingStatic_m", movingStatic_m, ...
    "wheelCenterStatic_m", movingStatic_m(4, :), ...
    "wheelAxisStatic", double(geometry.wheel.wheelAxis), ...
    "fixed_m", fixed_m, ...
    "tieInboardStatic_m", tieInboardStatic_m, ...
    "movingConstraintRows", movingConstraintRows, ...
    "linkLengths_m", linkLengths_m, ...
    "constraintIds", ["UCA_FWD"; "UCA_AFT"; "LCA_FWD"; ...
        "LCA_AFT"; "TIE_ROD"], ...
    "constraintTolerance_m", tolerances.AbsTol_m + ...
        tolerances.RelTol * max([linkLengths_m; 1]));
end

function output = points(geometry, ids)
output = zeros(numel(ids), 3);
for index = 1:numel(ids)
    output(index, :) = fsd.model.getPoint(geometry, ids(index));
end
end

function residual = constraintResiduals(unknowns, wheelTravel_m, ...
        tieInboard_m, mechanism)
lengthErrors_m = constraintLengthErrors(unknowns, wheelTravel_m, ...
    tieInboard_m, mechanism);
residual = lengthErrors_m ./ mechanism.linkLengths_m;
end

function lengthErrors_m = constraintLengthErrors(unknowns, wheelTravel_m, ...
        tieInboard_m, mechanism)
[currentPoints_m, ~, ~, ~] = evaluatePose( ...
    unknowns, wheelTravel_m, mechanism);
armPoints_m = currentPoints_m(mechanism.movingConstraintRows, :);
armLengths_m = sqrt(sum((armPoints_m - mechanism.fixed_m).^2, 2));
tieLength_m = norm(currentPoints_m(3, :) - tieInboard_m, 2);
lengthErrors_m = [armLengths_m; tieLength_m] - mechanism.linkLengths_m;
end

function [currentPoints_m, rotationMatrix, translation_m, wheelAxis] = ...
        evaluatePose(unknowns, wheelTravel_m, mechanism)
unknowns = unknowns(:);
translation_m = [unknowns(1), unknowns(2), wheelTravel_m];
rotationVector_rad = unknowns(3:5)';
rotationMatrix = fsd.geometry.rotationVectorToMatrix(rotationVector_rad);
currentPoints_m = fsd.geometry.transformPointsRigid( ...
    mechanism.movingStatic_m, mechanism.wheelCenterStatic_m, ...
    translation_m, rotationMatrix);
wheelAxis = (rotationMatrix * mechanism.wheelAxisStatic(:))';
wheelAxis = wheelAxis ./ norm(wheelAxis, 2);
end

function result = convergedResult(mechanism, target_m, tieInboard_m, ...
        unknowns, diagnostics)
[currentPoints_m, rotationMatrix, translation_m, wheelAxis] = ...
    evaluatePose(unknowns, target_m, mechanism);
achievedTravel_m = currentPoints_m(4, 3) - ...
    mechanism.wheelCenterStatic_m(3);
diagnostics.lengthErrors_m = constraintLengthErrors(unknowns, target_m, ...
    tieInboard_m, mechanism);
diagnostics.maxConstraintError_m = max(abs(diagnostics.lengthErrors_m));
diagnostics.residualVector = diagnostics.lengthErrors_m ./ ...
    mechanism.linkLengths_m;
diagnostics.residualNorm = norm(diagnostics.residualVector, 2);
diagnostics.maxResidual = max(abs(diagnostics.residualVector));
if diagnostics.exitFlag == 0
    diagnostics.exitFlag = 1;
    diagnostics.message = "Exact state reused without a nonlinear solve.";
end
state = stateStruct(mechanism, currentPoints_m, wheelAxis, achievedTravel_m);
pose = struct( ...
    "referencePointStatic_m", mechanism.wheelCenterStatic_m, ...
    "translation_m", translation_m, ...
    "rotationVector_rad", unknowns(3:5)', ...
    "rotationMatrix", rotationMatrix);
result = baseResult(mechanism, target_m, achievedTravel_m, tieInboard_m, ...
    true, "CONVERGED", "", state, pose, wheelAxis, diagnostics);
end

function result = failureResult(mechanism, target_m, tieInboard_m, ...
        status, diagnostics)
state = stateStruct(mechanism, nan(size(mechanism.movingStatic_m)), ...
    [NaN, NaN, NaN], NaN);
pose = struct( ...
    "referencePointStatic_m", mechanism.wheelCenterStatic_m, ...
    "translation_m", [NaN, NaN, NaN], ...
    "rotationVector_rad", [NaN, NaN, NaN], ...
    "rotationMatrix", nan(3));
result = baseResult(mechanism, target_m, NaN, tieInboard_m, false, status, ...
    diagnostics.message, state, pose, [NaN, NaN, NaN], diagnostics);
end

function result = baseResult(mechanism, requested_m, achieved_m, ...
        tieInboard_m, converged, status, failureReason, state, pose, ...
        wheelAxis, diagnostics)
camber_rad = NaN;
if converged
    camber_rad = fsd.kinematics.camberFromWheelAxis( ...
        wheelAxis, mechanism.cornerId);
end
result = struct( ...
    "geometryIdentity", mechanism.geometryIdentity, ...
    "cornerId", mechanism.cornerId, ...
    "requestedWheelTravel_m", requested_m, ...
    "achievedWheelTravel_m", achieved_m, ...
    "tieRodInboardStatic_m", mechanism.tieInboardStatic_m, ...
    "tieRodInboardCurrent_m", tieInboard_m, ...
    "converged", converged, ...
    "status", status, ...
    "failureReason", failureReason, ...
    "state", state, ...
    "uprightPose", pose, ...
    "wheelAxis", wheelAxis, ...
    "camber_rad", camber_rad, ...
    "diagnostics", diagnostics);
end

function state = stateStruct(mechanism, points_m, wheelAxis, travel_m)
state = struct( ...
    "schemaVersion", "0.2.0", ...
    "kind", "SuspensionState", ...
    "pointIds", mechanism.pointIds, ...
    "xyz_m", points_m, ...
    "ubj_m", points_m(1, :), ...
    "lbj_m", points_m(2, :), ...
    "tieRodOutboard_m", points_m(3, :), ...
    "wheelCenter_m", points_m(4, :), ...
    "contactPatch_m", points_m(5, :), ...
    "wheelAxis", wheelAxis, ...
    "wheelTravel_m", travel_m);
end

function diagnostics = emptyDiagnostics(mechanism)
diagnostics = struct( ...
    "solver", "fsolve", ...
    "toolbox", "Optimization Toolbox", ...
    "attempted", false, ...
    "constraintIds", mechanism.constraintIds, ...
    "lengthErrors_m", zeros(5, 1), ...
    "maxConstraintError_m", 0, ...
    "residualVector", zeros(5, 1), ...
    "residualNorm", 0, ...
    "maxResidual", 0, ...
    "exitFlag", 0, ...
    "iterations", 0, ...
    "functionEvaluations", 0, ...
    "continuationSteps", 0, ...
    "message", "");
end
