function result = solveActuationCore(actuation, sourceResult, referenceAngle_rad)
%SOLVEACTUATIONCORE Closed-form rocker solve for validated inputs.

if ~sourceResult.converged
    result = failedResult(actuation, sourceResult, ...
        "KINEMATICS_NOT_CONVERGED", ...
        "Source suspension kinematics did not converge.", false);
    result.diagnostics.sourceKinematicStatus = string(sourceResult.status);
    result.diagnostics.sourceKinematicFailureReason = ...
        string(sourceResult.failureReason);
    return
end

[suspensionPoint_m, attachmentDiagnostics] = ...
    actuationAttachmentCurrent(actuation, sourceResult);
axisPoint_m = actuation.rocker.axis.point_m;
axisDirection = actuation.rocker.axis.direction_unit;
rodPointStatic_m = actuation.rocker.actuationRodPoint.pointStatic_m;
offset_m = rodPointStatic_m - axisPoint_m;
parallel_m = dot(axisDirection, offset_m) .* axisDirection;
circleCenter_m = axisPoint_m + parallel_m;
radial_m = rodPointStatic_m - circleCenter_m;
tangent_m = cross(axisDirection, radial_m);
radius_m = norm(radial_m, 2);

tolerances = fsd.model.numericTolerances();
lengthScale_m = max([abs(actuation.identity.rockerRodPointStatic_m), ...
    abs(suspensionPoint_m), actuation.actuationRod.staticLength_m, 1]);
lengthTolerance_m = tolerances.AbsTol_m + ...
    tolerances.RelTol * lengthScale_m;
if radius_m <= lengthTolerance_m
    result = failedResult(actuation, sourceResult, ...
        "ROCKER_LEVER_ARM_DEGENERATE", ...
        "ACTUATION_ROD_ROCKER lies on the rocker axis.", true);
    result.diagnostics.attachmentTransform = attachmentDiagnostics;
    return
end

w_m = circleCenter_m - suspensionPoint_m;
rodLength_m = actuation.actuationRod.staticLength_m;
A_m2 = 2 * dot(w_m, radial_m);
B_m2 = 2 * dot(w_m, tangent_m);
D_m2 = rodLength_m^2 - dot(w_m, w_m) - dot(radial_m, radial_m);
R_m2 = hypot(A_m2, B_m2);
coefficientScale_m2 = max([abs(A_m2), abs(B_m2), abs(D_m2), ...
    rodLength_m^2, dot(w_m,w_m), dot(radial_m,radial_m), 1]);
baseDiagnostics = diagnosticStruct(referenceAngle_rad, attachmentDiagnostics, ...
    circleCenter_m, radius_m, A_m2, B_m2, D_m2, R_m2);
closure = rockerClosureSolution(A_m2, B_m2, D_m2, ...
    coefficientScale_m2, referenceAngle_rad);
if closure.constraintCase == "ALL_ANGLES"
        result = failedResult(actuation, sourceResult, ...
            "ROCKER_UNDERCONSTRAINED", ...
            "Rod closure permits all rocker angles at this state.", true);
        result.diagnostics = mergeDiagnostics(result.diagnostics, ...
            baseDiagnostics, "ALL_ANGLES");
    return
elseif closure.constraintCase == "NO_INTERSECTION_R_ZERO"
        result = failedResult(actuation, sourceResult, ...
            "NO_ROCKER_SOLUTION", ...
            "Rod closure has no rocker-circle intersection.", true);
        result.diagnostics = mergeDiagnostics(result.diagnostics, ...
            baseDiagnostics, "NO_INTERSECTION_R_ZERO");
    return
elseif closure.constraintCase == "NO_INTERSECTION"
    result = failedResult(actuation, sourceResult, "NO_ROCKER_SOLUTION", ...
        "Rod sphere and rocker circle do not intersect.", true);
    result.diagnostics = mergeDiagnostics(result.diagnostics, ...
        baseDiagnostics, "NO_INTERSECTION");
    return
end
candidateAngles_rad = closure.candidateAngles_rad;
selectedIndex = closure.selectedCandidateIndex;
theta_rad = closure.selectedAngle_rad;

rockerPoints_m = fsd.geometry.rotatePointsAboutAxis( ...
    [rodPointStatic_m; actuation.rocker.damperPoint.pointStatic_m], ...
    axisPoint_m, axisDirection, theta_rad);
rodPointCurrent_m = rockerPoints_m(1,:);
damperPointCurrent_m = rockerPoints_m(2,:);
actualRodLength_m = norm(rodPointCurrent_m - suspensionPoint_m, 2);
rodResidual_m = actualRodLength_m - rodLength_m;
damperLength_m = norm(damperPointCurrent_m - ...
    actuation.damper.chassisPoint.point_m, 2);
damperCompression_m = actuation.damper.staticLength_m - damperLength_m;
conditioning = closure.conditioning;
isIllConditioned = closure.isIllConditioned;
constraintCase = closure.constraintCase;
if abs(rodResidual_m) > 10 * lengthTolerance_m
    result = failedResult(actuation, sourceResult, "NO_ROCKER_SOLUTION", ...
        "Closed-form candidate failed rod-length post-validation.", true);
    result.diagnostics = mergeDiagnostics(result.diagnostics, ...
        baseDiagnostics, "POSTCHECK_FAILED");
    return
end

diagnostics = mergeDiagnostics(emptyDiagnostics(), baseDiagnostics, ...
    constraintCase);
diagnostics.attempted = true;
diagnostics.sourceKinematicStatus = string(sourceResult.status);
diagnostics.sourceKinematicFailureReason = string(sourceResult.failureReason);
diagnostics.candidateAngles_rad = candidateAngles_rad;
diagnostics.selectedCandidateIndex = selectedIndex;
diagnostics.acosRatio = closure.acosRatio;
diagnostics.alpha_rad = closure.alpha_rad;
diagnostics.coefficientTolerance_m2 = closure.coefficientTolerance_m2;
diagnostics.derivativeMagnitude_m2 = closure.derivativeMagnitude_m2;
result = baseResult(actuation, sourceResult, true, "CONVERGED", "", ...
    suspensionPoint_m, rodPointCurrent_m, damperPointCurrent_m, ...
    theta_rad, damperLength_m, damperCompression_m, actualRodLength_m, ...
    rodResidual_m, conditioning, isIllConditioned, diagnostics);
end

function diagnostics = diagnosticStruct(referenceAngle_rad, attachment, ...
        circleCenter_m, radius_m, A_m2, B_m2, D_m2, R_m2)
diagnostics = struct( ...
    "referenceRockerAngle_rad", referenceAngle_rad, ...
    "attachmentTransform", attachment, ...
    "rockerCircleCenter_m", circleCenter_m, ...
    "rockerCircleRadius_m", radius_m, ...
    "constraintA_m2", A_m2, ...
    "constraintB_m2", B_m2, ...
    "constraintD_m2", D_m2, ...
    "constraintR_m2", R_m2);
end

function output = mergeDiagnostics(output, addition, constraintCase)
names = fieldnames(addition);
for index = 1:numel(names)
    output.(names{index}) = addition.(names{index});
end
output.constraintCase = constraintCase;
output.attempted = true;
end

function result = failedResult(actuation, sourceResult, status, message, attempted)
diagnostics = emptyDiagnostics();
diagnostics.attempted = attempted;
diagnostics.sourceKinematicStatus = string(sourceResult.status);
diagnostics.sourceKinematicFailureReason = string(sourceResult.failureReason);
result = baseResult(actuation, sourceResult, false, status, message, ...
    [NaN, NaN, NaN], [NaN, NaN, NaN], [NaN, NaN, NaN], ...
    NaN, NaN, NaN, NaN, NaN, NaN, false, diagnostics);
end

function result = baseResult(actuation, sourceResult, converged, status, ...
        failureReason, suspensionPoint_m, rodPoint_m, damperPoint_m, ...
        theta_rad, damperLength_m, compression_m, rodLength_m, ...
        rodResidual_m, conditioning, isIllConditioned, diagnostics)
wrapped_rad = NaN;
if isfinite(theta_rad)
    wrapped_rad = fsd.geometry.wrapAngle(theta_rad);
end
result = struct( ...
    "schemaVersion", "0.7.0", ...
    "kind", "ActuationResult", ...
    "actuationIdentity", actuation.identity, ...
    "cornerId", string(actuation.cornerId), ...
    "actuationType", string(actuation.actuationType), ...
    "attachmentBody", string(actuation.suspensionAttachment.body), ...
    "sourceResultKind", string(sourceResult.kind), ...
    "sourceResult", sourceResult, ...
    "sourceGeometryIdentity", sourceResult.geometryIdentity, ...
    "sourceRequestedWheelTravel_m", sourceResult.requestedWheelTravel_m, ...
    "sourceAchievedWheelTravel_m", sourceResult.achievedWheelTravel_m, ...
    "sourceKinematicStatus", string(sourceResult.status), ...
    "sourceKinematicFailureReason", string(sourceResult.failureReason), ...
    "converged", logical(converged), ...
    "status", string(status), ...
    "failureReason", string(failureReason), ...
    "suspensionAttachmentCurrent_m", suspensionPoint_m, ...
    "rockerRodPointCurrent_m", rodPoint_m, ...
    "rockerDamperPointCurrent_m", damperPoint_m, ...
    "rockerAngle_rad", theta_rad, ...
    "rockerAngleWrapped_rad", wrapped_rad, ...
    "damperLength_m", damperLength_m, ...
    "damperCompression_m", compression_m, ...
    "actuationRodLength_m", rodLength_m, ...
    "actuationRodLengthResidual_m", rodResidual_m, ...
    "conditioning", conditioning, ...
    "isIllConditioned", logical(isIllConditioned), ...
    "diagnostics", diagnostics);
end

function diagnostics = emptyDiagnostics()
diagnostics = struct( ...
    "solver", "CLOSED_FORM_CIRCLE_SPHERE", ...
    "attempted", false, ...
    "sourceKinematicStatus", "", ...
    "sourceKinematicFailureReason", "", ...
    "constraintCase", "NOT_ATTEMPTED", ...
    "referenceRockerAngle_rad", NaN, ...
    "candidateAngles_rad", NaN(1,0), ...
    "selectedCandidateIndex", NaN, ...
    "acosRatio", NaN, ...
    "alpha_rad", NaN, ...
    "coefficientTolerance_m2", NaN, ...
    "derivativeMagnitude_m2", NaN, ...
    "attachmentTransform", struct(), ...
    "rockerCircleCenter_m", [NaN, NaN, NaN], ...
    "rockerCircleRadius_m", NaN, ...
    "constraintA_m2", NaN, ...
    "constraintB_m2", NaN, ...
    "constraintD_m2", NaN, ...
    "constraintR_m2", NaN);
end
