function result = steeringCornerResultFromRaw(geometry, raw, ...
    baselineRaw, requestedRackTravel_m)
%STEERINGCORNERRESULTFROMRAW Build one v0.5 corner result.

baseline = kinematicResultFromRaw(baselineRaw);
if raw.converged
    radius_m = norm(fsd.model.getPoint(geometry, ...
        string(geometry.cornerId) + "_CONTACT_PATCH") - ...
        fsd.model.getPoint(geometry, ...
        string(geometry.cornerId) + "_WHEEL_CENTER"));
    ideal = fsd.geometry.geometricWheelContact( ...
        raw.state.wheelCenter_m, raw.wheelAxis, radius_m);
    contact = struct( ...
        "status", string(ideal.status), ...
        "point_m", double(ideal.point_m), ...
        "geometricRadius_m", radius_m, ...
        "diagnostic", string(ideal.diagnostic));
    achievedRackTravel_m = requestedRackTravel_m;
else
    contact = struct( ...
        "status", "KINEMATICS_NOT_CONVERGED", ...
        "point_m", [NaN, NaN, NaN], ...
        "geometricRadius_m", NaN, ...
        "diagnostic", string(raw.failureReason));
    achievedRackTravel_m = NaN;
end
result = struct( ...
    "schemaVersion", "0.5.0", ...
    "kind", "SteeringCornerResult", ...
    "geometryIdentity", raw.geometryIdentity, ...
    "cornerId", raw.cornerId, ...
    "requestedWheelTravel_m", raw.requestedWheelTravel_m, ...
    "achievedWheelTravel_m", raw.achievedWheelTravel_m, ...
    "requestedRackTravel_m", requestedRackTravel_m, ...
    "achievedRackTravel_m", achievedRackTravel_m, ...
    "tieRodInboardStatic_m", raw.tieRodInboardStatic_m, ...
    "tieRodInboardCurrent_m", raw.tieRodInboardCurrent_m, ...
    "state", raw.state, ...
    "uprightPose", raw.uprightPose, ...
    "wheelAxis", raw.wheelAxis, ...
    "camber_rad", raw.camber_rad, ...
    "geometricContact", contact, ...
    "rackZeroKinematicResult", baseline, ...
    "converged", raw.converged, ...
    "status", raw.status, ...
    "failureReason", raw.failureReason, ...
    "diagnostics", raw.diagnostics);
end
