function sweepAnalysis = analyzeAxleHeaveSweep(axle, sweep)
%ANALYZEAXLEHEAVESWEEP Compute roll-center migration for symmetric heave.

fsd.model.validateAxleGeometry(axle);
try
    fsd.kinematics.validateAxleHeaveSweepResult(sweep);
catch cause
    exception = MException("fsd:analysis:InvalidAxleHeaveSweep", ...
        "sweep violates the AxleHeaveSweepResult contract.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
if ~isequal(fsd.model.axleIdentity(axle), sweep.axleIdentity)
    error("fsd:analysis:AxleGeometryMismatch", ...
        "The axle sweep belongs to a different axle geometry.");
end

timer = tic;
count = numel(sweep.results);
leftRadius_m = wheelContactRadius(axle.leftGeometry);
rightRadius_m = wheelContactRadius(axle.rightGeometry);
axleIdentity = fsd.model.axleIdentity(axle);
states = repmat(failedState(axle, axleIdentity, sweep.results(1)), ...
    count, 1);
for index = 1:count
    if sweep.results(index).converged
        states(index) = analyzeAxleStateCore(axle, ...
            sweep.results(index).leftResult, ...
            sweep.results(index).rightResult, ...
            sweep.results(index).requestedWheelTravel_m, ...
            leftRadius_m, rightRadius_m, axleIdentity);
    else
        states(index) = failedState(axle, axleIdentity, ...
            sweep.results(index));
    end
end
sweepAnalysis = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "AxleHeaveRollCenterAnalysis", ...
    "axleIdentity", sweep.axleIdentity, ...
    "axleId", string(axle.axleId), ...
    "requestedWheelTravel_m", double(sweep.requestedWheelTravel_m), ...
    "converged", logical(sweep.converged), ...
    "status", reshape(string({states.status}), [], 1), ...
    "rollCenterY_m", reshape([states.rollCenterY_m], [], 1), ...
    "rollCenterZ_m", reshape([states.rollCenterZ_m], [], 1), ...
    "rollCenterHeight_m", ...
        reshape([states.rollCenterHeight_m], [], 1), ...
    "rollCenterHeightStatus", ...
        reshape(string({states.rollCenterHeightStatus}), [], 1), ...
    "rollCenterHomogeneousPoint", ...
        reshape([states.rollCenterHomogeneousPoint], 3, []).', ...
    "rollCenterDirection_yz", ...
        reshape([states.rollCenterDirection_yz], 2, []).', ...
    "rollCenterConditioning", ...
        reshape([states.rollCenterConditioning], [], 1), ...
    "rollCenterIllConditioned", ...
        reshape([states.rollCenterIllConditioned], [], 1), ...
    "allConverged", all(sweep.converged), ...
    "solverElapsedTime_s", double(sweep.elapsedTime_s), ...
    "analysisElapsedTime_s", toc(timer), ...
    "states", states);
end

function state = failedState(axle, axleIdentity, result)
diagnostic = "The kinematic state did not converge; no analysis " + ...
    "payload was constructed.";
state = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "AxleRollCenterAnalysis", ...
    "axleIdentity", axleIdentity, ...
    "axleId", string(axle.axleId), ...
    "requestedWheelTravel_m", result.requestedWheelTravel_m, ...
    "status", "KINEMATICS_NOT_CONVERGED", ...
    "rollCenterY_m", NaN, ...
    "rollCenterZ_m", NaN, ...
    "rollCenterHeight_m", NaN, ...
    "rollCenterHeightStatus", "KINEMATICS_NOT_CONVERGED", ...
    "roadReferenceZ_m", NaN, ...
    "rollCenterHomogeneousPoint", [NaN, NaN, NaN], ...
    "rollCenterDirection_yz", [NaN, NaN], ...
    "rollCenterConditioning", NaN, ...
    "rollCenterIllConditioned", false, ...
    "diagnostic", diagnostic, ...
    "left", failedSide(axle.leftGeometry.cornerId, diagnostic), ...
    "right", failedSide(axle.rightGeometry.cornerId, diagnostic), ...
    "analysisElapsedTime_s", 0);
end

function side = failedSide(cornerId, diagnostic)
line = invalidLine(diagnostic);
constraint = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "FrontViewKinematicConstraint", ...
    "status", "DEGENERATE", ...
    "degeneracy", "KINEMATICS_NOT_CONVERGED", ...
    "pivotAxisPoint_m", [NaN, NaN, NaN], ...
    "pivotAxisDirection", [NaN, NaN, NaN], ...
    "radialVector_m", [NaN, NaN, NaN], ...
    "velocityDirection3d", [NaN, NaN, NaN], ...
    "projectedVelocityDirection_yz", [NaN, NaN], ...
    "line", line, ...
    "diagnostic", diagnostic);
instantCenter = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "FrontViewInstantCenter", ...
    "cornerId", string(cornerId), ...
    "status", "KINEMATICS_NOT_CONVERGED", ...
    "instantCenterY_m", NaN, ...
    "instantCenterZ_m", NaN, ...
    "point_yz_m", [NaN, NaN], ...
    "homogeneousPoint", [NaN, NaN, NaN], ...
    "direction_yz", [NaN, NaN], ...
    "conditioning", NaN, ...
    "isIllConditioned", false, ...
    "upperConstraint", constraint, ...
    "lowerConstraint", constraint, ...
    "upperLine", line, ...
    "lowerLine", line, ...
    "diagnostic", diagnostic);
contact = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "IdealRigidWheelContact", ...
    "cornerId", string(cornerId), ...
    "status", "KINEMATICS_NOT_CONVERGED", ...
    "geometricRadius_m", NaN, ...
    "wheelCenter_m", [NaN, NaN, NaN], ...
    "wheelAxis", [NaN, NaN, NaN], ...
    "point_m", [NaN, NaN, NaN], ...
    "staticDatum_m", [NaN, NaN, NaN], ...
    "diagnostic", diagnostic);
side = struct( ...
    "cornerId", string(cornerId), ...
    "instantCenter", instantCenter, ...
    "geometricContact", contact, ...
    "rollCenterConstructionLine", line);
end

function line = invalidLine(diagnostic)
line = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "LineYZ", ...
    "status", "DEGENERATE", ...
    "homogeneousLine", [NaN, NaN, NaN], ...
    "coefficients", [NaN, NaN, NaN], ...
    "point_yz_m", [NaN, NaN], ...
    "direction_yz", [NaN, NaN], ...
    "diagnostic", diagnostic);
end
