function analysis = analyzeActuationSweep(actuation, sweep)
%ANALYZEACTUATIONSWEEP Compute geometric ranges and local gains.

fsd.model.validateActuationGeometry(actuation);
fsd.kinematics.validateActuationSweepResult(sweep, actuation);
timer = tic;
count = numel(sweep.results);
stateCells = cell(count, 1);
for index = 1:count
    stateCells{index} = analyzeActuationCore( ...
        actuation, sweep.results(index));
end
states = vertcat(stateCells{:});

motionRatio = nan(count, 1);
installationRatio = nan(count, 1);
angularGain = nan(count, 1);
motionRatioMigration = nan(count, 1);
staticReferenceIndex = NaN;
staticMotionRatio = NaN;
staticReferenceAvailable = false;
if ~sweep.allConverged
    motionRatioStatus = "UNAVAILABLE_ACTUATION_FAILURE";
elseif count < 3
    motionRatioStatus = "UNAVAILABLE_INVALID_WHEEL_TRAVEL";
elseif ~isStrictlyMonotonic(sweep.requestedWheelTravel_m) || ...
        ~isStrictlyMonotonic(sweep.achievedWheelTravel_m)
    motionRatioStatus = "UNAVAILABLE_NONMONOTONIC_WHEEL_TRAVEL";
else
    motionRatio = secondOrderDerivative( ...
        sweep.achievedWheelTravel_m, sweep.damperCompression_m);
    angularGain = secondOrderDerivative( ...
        sweep.achievedWheelTravel_m, sweep.rockerAngle_rad);
    installationRatio = abs(motionRatio);
    zeroIndices = find(sweep.requestedWheelTravel_m == 0);
    if isscalar(zeroIndices)
        staticReferenceIndex = zeroIndices;
        staticMotionRatio = motionRatio(zeroIndices);
        motionRatioMigration = motionRatio - staticMotionRatio;
        staticReferenceAvailable = true;
        motionRatioStatus = "AVAILABLE";
    else
        motionRatioStatus = "AVAILABLE_STATIC_REFERENCE_MISSING";
    end
end

if sweep.allConverged
    analysisStatus = "CONVERGED";
    minDamperLength_m = min(sweep.damperLength_m);
    maxDamperLength_m = max(sweep.damperLength_m);
    maximumCompression_m = max([sweep.damperCompression_m; 0]);
    maximumExtension_m = max([-sweep.damperCompression_m; 0]);
    totalRequiredStroke_m = maxDamperLength_m - minDamperLength_m;
    minRockerAngle_rad = min(sweep.rockerAngle_rad);
    maxRockerAngle_rad = max(sweep.rockerAngle_rad);
    rockerAngularExcursion_rad = maxRockerAngle_rad - minRockerAngle_rad;
else
    analysisStatus = "ACTUATION_NOT_CONVERGED";
    minDamperLength_m = NaN;
    maxDamperLength_m = NaN;
    maximumCompression_m = NaN;
    maximumExtension_m = NaN;
    totalRequiredStroke_m = NaN;
    minRockerAngle_rad = NaN;
    maxRockerAngle_rad = NaN;
    rockerAngularExcursion_rad = NaN;
end

analysis = struct( ...
    "schemaVersion", "0.7.0", ...
    "kind", "ActuationSweepAnalysis", ...
    "actuationIdentity", actuation.identity, ...
    "requestedWheelTravel_m", sweep.requestedWheelTravel_m, ...
    "achievedWheelTravel_m", sweep.achievedWheelTravel_m, ...
    "converged", sweep.converged, ...
    "actuationStatus", reshape(string({states.actuationStatus}), [], 1), ...
    "analysisStatus", analysisStatus, ...
    "rockerAngle_rad", sweep.rockerAngle_rad, ...
    "damperLength_m", sweep.damperLength_m, ...
    "damperCompression_m", sweep.damperCompression_m, ...
    "conditioning", sweep.conditioning, ...
    "damperMotionRatio", motionRatio, ...
    "installationRatio", installationRatio, ...
    "rockerAngularGain_rad_per_m", angularGain, ...
    "motionRatioMigration", motionRatioMigration, ...
    "motionRatioStatus", motionRatioStatus, ...
    "staticReferenceAvailable", logical(staticReferenceAvailable), ...
    "staticReferenceIndex", staticReferenceIndex, ...
    "staticDamperMotionRatio", staticMotionRatio, ...
    "minimumDamperLength_m", minDamperLength_m, ...
    "maximumDamperLength_m", maxDamperLength_m, ...
    "maximumCompression_m", maximumCompression_m, ...
    "maximumExtension_m", maximumExtension_m, ...
    "totalRequiredStroke_m", totalRequiredStroke_m, ...
    "minimumRockerAngle_rad", minRockerAngle_rad, ...
    "maximumRockerAngle_rad", maxRockerAngle_rad, ...
    "rockerAngularExcursion_rad", rockerAngularExcursion_rad, ...
    "states", states, ...
    "elapsedTime_s", toc(timer));
fsd.analysis.validateActuationSweepAnalysis(analysis, actuation, sweep);
end

function tf = isStrictlyMonotonic(value)
steps = diff(value);
tf = all(steps > 0) || all(steps < 0);
end
