function analysis = analyzeRackSweep(steering, sweep)
%ANALYZERACKSWEEP Derive steering metrics for each rack target.

fsd.kinematics.validateRackSweepResult(sweep, steering);
timer = tic;
count = numel(sweep.results);
stateCells = cell(count, 1);
for index = 1:count
    stateCells{index} = analyzeSteeringCore(steering, sweep.results(index));
end
states = vertcat(stateCells{:});
analysis = struct( ...
    "schemaVersion", "0.5.0", ...
    "kind", "RackSweepAnalysis", ...
    "steeringSystemIdentity", steering.identity, ...
    "requestedRackTravel_m", sweep.requestedRackTravel_m, ...
    "requestedWheelTravel_m", sweep.requestedWheelTravel_m, ...
    "converged", sweep.converged, ...
    "status", sweep.status, ...
    "roadWheelAngleLeft_rad", values(states, "left", "roadWheelAngle_rad"), ...
    "roadWheelAngleRight_rad", values(states, "right", "roadWheelAngle_rad"), ...
    "steerDeflectionLeft_rad", ...
        values(states, "left", "steerDeflectionFromStatic_rad"), ...
    "steerDeflectionRight_rad", ...
        values(states, "right", "steerDeflectionFromStatic_rad"), ...
    "rackInducedSteerLeft_rad", ...
        values(states, "left", "rackInducedSteer_rad"), ...
    "rackInducedSteerRight_rad", ...
        values(states, "right", "rackInducedSteer_rad"), ...
    "toeLeft_rad", values(states, "left", "toe_rad"), ...
    "toeRight_rad", values(states, "right", "toe_rad"), ...
    "scrubRadiusLeft_m", values(states, "left", "scrubRadius_m"), ...
    "scrubRadiusRight_m", values(states, "right", "scrubRadius_m"), ...
    "mechanicalTrailLeft_m", ...
        values(states, "left", "mechanicalTrail_m"), ...
    "mechanicalTrailRight_m", ...
        values(states, "right", "mechanicalTrail_m"), ...
    "ackermannAngleError_rad", ackermannValues(states, ...
        "ackermannAngleError_rad"), ...
    "ackermannStatus", ackermannStatuses(states), ...
    "allConverged", sweep.allConverged, ...
    "solverElapsedTime_s", sweep.elapsedTime_s, ...
    "analysisElapsedTime_s", toc(timer), ...
    "states", states);
end

function output = values(states, side, field)
output = reshape(arrayfun(@(item) item.(side).(field), states), [], 1);
end

function output = ackermannValues(states, field)
output = reshape(arrayfun(@(item) item.ackermann.(field), states), [], 1);
end

function output = ackermannStatuses(states)
output = strings(numel(states), 1);
for index = 1:numel(states)
    output(index) = string(states(index).ackermann.status);
end
end
