function analysis = analyzeAxleRollSweep(axle, sweep)
%ANALYZEAXLEROLLSWEEP Analyze an ordered body-roll sweep.

fsd.model.validateAxleGeometry(axle);
try
    fsd.kinematics.validateAxleRollSweepResult(sweep);
catch cause
    exception = MException("fsd:analysis:InvalidAxleRollSweepResult", ...
        "sweep violates the AxleRollSweepResult contract.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
identity = fsd.model.axleIdentity(axle);
if ~isequal(identity, sweep.axleIdentity)
    error("fsd:analysis:AxleGeometryMismatch", ...
        "The roll sweep belongs to a different axle geometry.");
end

timer = tic;
leftRadius_m = wheelContactRadius(axle.leftGeometry);
rightRadius_m = wheelContactRadius(axle.rightGeometry);
reference = staticReference(axle, leftRadius_m, rightRadius_m, identity);
cells = cell(numel(sweep.results), 1);
for index = 1:numel(sweep.results)
    cells{index} = analyzeAxleRollCore(axle, sweep.results(index), ...
        reference, leftRadius_m, rightRadius_m, identity);
end
states = vertcat(cells{:});
analysis = struct( ...
    "schemaVersion", "0.6.0", "kind", "AxleRollSweepAnalysis", ...
    "axleIdentity", identity, "axleId", string(axle.axleId), ...
    "bodyRollAngle_rad", sweep.requestedBodyRollAngle_rad, ...
    "axleHeave_m", sweep.requestedAxleHeave_m, ...
    "converged", sweep.converged, ...
    "kinematicStatus", sweep.status, ...
    "analysisStatus", stringsOf(states, "status"), ...
    "kinematicFailureReason", ...
        reshape(string({sweep.results.failureReason}), [], 1), ...
    "wheelTravel_m", rows(states, "wheelTravel_m", 2), ...
    "wheelTravelDifferential_m", column(states, ...
        "wheelTravelDifferential_m"), ...
    "chassisCamber_rad", rows(states, "chassisCamber_rad", 2), ...
    "roadCamber_rad", rows(states, "roadCamber_rad", 2), ...
    "toe_rad", rows(states, "toe_rad", 2), ...
    "leftInstantCenterY_m", column(states, "leftInstantCenterY_m"), ...
    "leftInstantCenterZ_m", column(states, "leftInstantCenterZ_m"), ...
    "rightInstantCenterY_m", column(states, "rightInstantCenterY_m"), ...
    "rightInstantCenterZ_m", column(states, "rightInstantCenterZ_m"), ...
    "rollCenterStatus", stringsOf(states, "rollCenterStatus"), ...
    "rollCenterY_m", column(states, "rollCenterY_m"), ...
    "rollCenterZ_m", column(states, "rollCenterZ_m"), ...
    "rollCenterHeight_m", column(states, "rollCenterHeight_m"), ...
    "rollCenterRoadHeight_m", column(states, "rollCenterRoadHeight_m"), ...
    "rollCenterRoadHeightStatus", stringsOf(states, ...
        "rollCenterRoadHeightStatus"), ...
    "wheelCenterTrack_m", column(states, "wheelCenterTrack_m"), ...
    "geometricContactTrack_m", column(states, "geometricContactTrack_m"), ...
    "wheelCenterTrackChange_m", column(states, ...
        "wheelCenterTrackChange_m"), ...
    "geometricContactTrackChange_m", column(states, ...
        "geometricContactTrackChange_m"), ...
    "reference", reference, "allConverged", sweep.allConverged, ...
    "solverElapsedTime_s", sweep.elapsedTime_s, ...
    "analysisElapsedTime_s", toc(timer), "states", states);
fsd.analysis.validateAxleRollSweepAnalysis(analysis);
end

function reference = staticReference(axle, leftRadius_m, rightRadius_m, identity)
base = analyzeAxleStateCore(axle, [], [], 0, leftRadius_m, ...
    rightRadius_m, identity);
leftCenter = fsd.model.getPoint(axle.leftGeometry, ...
    string(axle.leftGeometry.cornerId) + "_WHEEL_CENTER");
rightCenter = fsd.model.getPoint(axle.rightGeometry, ...
    string(axle.rightGeometry.cornerId) + "_WHEEL_CENTER");
leftContact = base.left.geometricContact.point_m;
rightContact = base.right.geometricContact.point_m;
reference = struct("bodyRollAngle_rad", 0, "axleHeave_m", 0, ...
    "wheelCenterTrack_m", rightCenter(2) - leftCenter(2), ...
    "geometricContactTrack_m", rightContact(2) - leftContact(2));
end

function value = column(states, field)
value = reshape([states.(field)], [], 1);
end

function value = rows(states, field, width)
value = reshape([states.(field)], width, []).';
end

function value = stringsOf(states, field)
value = reshape(string({states.(field)}), [], 1);
end
