function sweepAnalysis = analyzeBumpSweep(geometry, sweep)
%ANALYZEBUMPSWEEP Derive ordered single-corner metrics without interpolation.

validateGeometry(geometry);
validateSweep(sweep);
assertGeometryIdentity(geometry, sweep.geometryIdentity);

timer = tic;
resultCount = numel(sweep.results);
stateAnalyses = repmat(emptyStateTemplate(), resultCount, 1);
for index = 1:resultCount
    stateAnalyses(index) = analyzeCornerStateCore( ...
        geometry, sweep.results(index));
end

requestedTravel_m = reshape([stateAnalyses.requestedWheelTravel_m], [], 1);
if ~isequal(requestedTravel_m, double(sweep.requestedWheelTravel_m))
    error("fsd:analysis:InvalidBumpSweep", ...
        "Sweep targets and contained KinematicResult targets must match.");
end
wheelTravel_m = reshape([stateAnalyses.wheelTravel_m], [], 1);
camber_rad = reshape([stateAnalyses.camber_rad], [], 1);
toe_rad = reshape([stateAnalyses.toe_rad], [], 1);
caster_rad = reshape([stateAnalyses.caster_rad], [], 1);
kingpinInclination_rad = reshape( ...
    [stateAnalyses.kingpinInclination_rad], [], 1);
steeringAxes = vertcat(stateAnalyses.steeringAxis);
converged = reshape([stateAnalyses.converged], [], 1);
status = reshape(string({stateAnalyses.status}), [], 1);
failureReason = reshape(string({stateAnalyses.failureReason}), [], 1);

staticToe_rad = fsd.analysis.toeFromWheelAxis( ...
    geometry.wheel.wheelAxis, geometry.cornerId);
bumpSteer_rad = toe_rad - staticToe_rad;
analysisElapsedTime_s = toc(timer);

sweepAnalysis = struct( ...
    "schemaVersion", "0.3.0", ...
    "kind", "BumpSweepAnalysis", ...
    "geometryIdentity", sweep.geometryIdentity, ...
    "cornerId", geometry.cornerId, ...
    "requestedWheelTravel_m", requestedTravel_m, ...
    "wheelTravel_m", wheelTravel_m, ...
    "camber_rad", camber_rad, ...
    "staticToe_rad", staticToe_rad, ...
    "toe_rad", toe_rad, ...
    "bumpSteer_rad", bumpSteer_rad, ...
    "caster_rad", caster_rad, ...
    "kingpinInclination_rad", kingpinInclination_rad, ...
    "steeringAxis", steeringAxes, ...
    "converged", converged, ...
    "allConverged", all(converged), ...
    "status", status, ...
    "failureReason", failureReason, ...
    "solverElapsedTime_s", double(sweep.elapsedTime_s), ...
    "analysisElapsedTime_s", analysisElapsedTime_s, ...
    "states", stateAnalyses);
end

function validateSweep(sweep)
try
    fsd.kinematics.validateBumpSweepResult(sweep);
catch cause
    exception = MException("fsd:analysis:InvalidBumpSweep", ...
        "sweep must satisfy the complete BumpSweepResult contract.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
end

function template = emptyStateTemplate()
template = struct( ...
    "schemaVersion", "", "kind", "", "geometryIdentity", struct(), ...
    "cornerId", "", ...
    "requestedWheelTravel_m", NaN, "wheelTravel_m", NaN, ...
    "camber_rad", NaN, "toe_rad", NaN, "caster_rad", NaN, ...
    "kingpinInclination_rad", NaN, ...
    "steeringAxis", [NaN, NaN, NaN], ...
    "converged", false, "status", "", "failureReason", "", ...
    "solverDiagnostics", struct());
end

function validateGeometry(geometry)
try
    fsd.model.validateDoubleWishboneGeometry(geometry);
catch cause
    exception = MException("fsd:analysis:InvalidGeometry", ...
        "geometry must be a valid DoubleWishboneGeometry.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
end
