function report = benchmarkGlobalStaticEquilibrium(system, q, solverOptions)
%BENCHMARKGLOBALSTATICEQUILIBRIUM Warmed stage timings, no arbitrary speed targets.
q = globalCoordinateInput(q); o = globalSolverOptions(solverOptions);
t = tic; p = fsd.analysis.prepareGlobalStaticSystem(system); prepare = toc(t);
samples = zeros(3,3);
for i = 1:4
    [~,times] = globalStateCore(p,q);
    if i > 1
        samples(i-1,:) = [times.stateEvaluationTime_s,times.energyAssemblyTime_s, ...
            times.gradientAndHessianAssemblyTime_s];
    end
end
result = fsd.analysis.solveGlobalStaticEquilibrium(system,q,o);
t = tic; fsd.analysis.validateGlobalStaticEquilibrium(result,system); validation = toc(t);
profile clear; profile on;
globalStateCore(p,q);
profile off; info = profile("info"); names = string({info.FunctionTable.FunctionName});
assert(~any(contains(names,["solveBump","solveSteering","solveActuation","create", ...
    "validate","analyzeSpringDamperSweep","fsolve","fzero"])), ...
    "Energy core must not validate/create models, analyze sweeps or solve mechanisms.");
d = result.attempts{1}.diagnostics;
report = struct("preparationTime_s",prepare,"sourceValidationTime_s",p.performance.sourceValidationTime_s, ...
    "interpolationTime_s",p.performance.interpolationTime_s,"medianStateEvaluationTime_s",median(samples(:,1)), ...
    "medianEnergyAssemblyTime_s",median(samples(:,2)), ...
    "medianGradientAndHessianAssemblyTime_s",median(samples(:,3)), ...
    "solveTime_s",d.solveTime_s,"resultValidationTime_s",validation, ...
    "residualEvaluations",d.residualEvaluations,"iterations",d.iterations, ...
    "meanSolveTimePerResidualEvaluation_s",d.solveTime_s/d.residualEvaluations, ...
    "sourceRevalidationsDuringSolve",d.sourceRevalidationsDuringSolve, ...
    "jacobianReciprocalCondition",result.attempts{1}.solution.jacobianReciprocalCondition, ...
    "hiddenMechanismSolves",0);
end
