function comparison = compareStaticVehicleCases(vehicleA, loadsA, vehicleB, loadsB, equilibriumA, equilibriumB)
%COMPARESTATICVEHICLECASES Signed B-A differences, not a handling recommendation.
fsd.analysis.validateStaticVehicleLoads(loadsA,vehicleA);
fsd.analysis.validateStaticVehicleLoads(loadsB,vehicleB);
travel = NaN;
if nargin >= 6 && ~isempty(equilibriumA) && ~isempty(equilibriumB)
    fsd.analysis.validateCornerStaticEquilibrium(equilibriumA);
    fsd.analysis.validateCornerStaticEquilibrium(equilibriumB);
    if equilibriumA.cornerId ~= equilibriumB.cornerId
        error("fsd:analysis:InvalidCornerEquilibrium","Comparison must use the same corner.");
    end
    index = find(vehicleA.cornerIds == equilibriumA.cornerId);
    if ~isfinite(loadsA.supportForce_N(index)) || ~isfinite(loadsB.supportForce_N(index)) || ...
            abs(equilibriumA.targetSupport_N-loadsA.supportForce_N(index)) > loadsA.forceTolerance_N || ...
            abs(equilibriumB.targetSupport_N-loadsB.supportForce_N(index)) > loadsB.forceTolerance_N
        error("fsd:analysis:InvalidCornerEquilibrium","Equilibrium demand does not match compared load case.");
    end
    travel = equilibriumB.equilibriumWheelTravel_m-equilibriumA.equilibriumWheelTravel_m;
end
comparison = struct("kind","StaticVehicleCaseComparison","schemaVersion","0.9.0", ...
    "vehicleIdentityA",vehicleA.identity,"vehicleIdentityB",vehicleB.identity, ...
    "loadCaseIdentityA",loadsA.loadCase.identity,"loadCaseIdentityB",loadsB.loadCase.identity, ...
    "deltaTotalMass_kg",vehicleB.totalMass_kg-vehicleA.totalMass_kg, ...
    "deltaCG_m",vehicleB.cg_m-vehicleA.cg_m, ...
    "deltaFrontAxleLoad_N",loadsB.frontAxleLoad_N-loadsA.frontAxleLoad_N, ...
    "deltaRearAxleLoad_N",loadsB.rearAxleLoad_N-loadsA.rearAxleLoad_N, ...
    "deltaCornerLoads_N",loadsB.cornerLoads_N-loadsA.cornerLoads_N, ...
    "deltaCornerLoadBounds_N",loadsB.family.cornerLoadBounds_N-loadsA.family.cornerLoadBounds_N, ...
    "deltaSupportForce_N",loadsB.supportForce_N-loadsA.supportForce_N, ...
    "deltaLocalEquilibriumTravel_m",travel,"globalChassisEquilibriumSolved",false);
end
