function metrics = scrubAndMechanicalTrail(lbj_m, ubj_m, ...
    contact_m, cornerId)
%SCRUBANDMECHANICALTRAIL Compute geometric scrub and mechanical trail.

cornerId = upper(strtrim(string(cornerId)));
if ~isscalar(cornerId) || ~ismember(cornerId, ["FL", "FR"])
    error("fsd:analysis:InvalidCorner", ...
        "cornerId must be FL or FR.");
end
if ~isnumeric(contact_m) || ~isreal(contact_m) || ...
        ~isequal(size(contact_m), [1, 3]) || any(~isfinite(contact_m))
    error("fsd:analysis:InvalidPoint", ...
        "contact_m must be a finite real 1-by-3 point.");
end
intersection = fsd.geometry.intersectSteeringAxisWithHorizontalPlane( ...
    lbj_m, ubj_m, contact_m(3));
scrubRadius_m = NaN;
mechanicalTrail_m = NaN;
if string(intersection.status) == "FINITE"
    sideSign = 1;
    if cornerId == "FL"
        sideSign = -1;
    end
    scrubRadius_m = sideSign * ...
        (double(contact_m(2)) - intersection.point_m(2));
    mechanicalTrail_m = double(contact_m(1)) - intersection.point_m(1);
end
metrics = struct( ...
    "schemaVersion", "0.5.0", ...
    "kind", "ScrubAndMechanicalTrail", ...
    "cornerId", cornerId, ...
    "status", string(intersection.status), ...
    "steeringAxisRoadIntersection", intersection, ...
    "contact_m", double(contact_m), ...
    "scrubRadius_m", scrubRadius_m, ...
    "mechanicalTrail_m", mechanicalTrail_m, ...
    "diagnostic", string(intersection.diagnostic));
end
