function isValid = validateActuationSweepAnalysis(analysis, actuation, sweep)
%VALIDATEACTUATIONSWEEPANALYSIS Validate aggregate actuation metrics.

if ~isstruct(analysis) || ~isscalar(analysis)
    invalid("ActuationSweepAnalysis must be a scalar struct.");
end
required = ["schemaVersion", "kind", "actuationIdentity", ...
    "requestedWheelTravel_m", "achievedWheelTravel_m", "converged", ...
    "actuationStatus", "analysisStatus", "rockerAngle_rad", ...
    "damperLength_m", "damperCompression_m", "conditioning", ...
    "damperMotionRatio", "installationRatio", ...
    "rockerAngularGain_rad_per_m", "motionRatioMigration", ...
    "motionRatioStatus", "staticReferenceAvailable", ...
    "staticReferenceIndex", "staticDamperMotionRatio", ...
    "minimumDamperLength_m", "maximumDamperLength_m", ...
    "maximumCompression_m", "maximumExtension_m", ...
    "totalRequiredStroke_m", "minimumRockerAngle_rad", ...
    "maximumRockerAngle_rad", "rockerAngularExcursion_rad", ...
    "states", "elapsedTime_s"];
if any(~isfield(analysis, required)) || ...
        string(analysis.schemaVersion) ~= "0.7.0" || ...
        string(analysis.kind) ~= "ActuationSweepAnalysis"
    invalid("Unsupported or incomplete ActuationSweepAnalysis schema.");
end
fsd.model.validateActuationGeometry(actuation);
fsd.kinematics.validateActuationSweepResult(sweep, actuation);
count = numel(sweep.results);
columnFields = ["requestedWheelTravel_m", "achievedWheelTravel_m", ...
    "rockerAngle_rad", "damperLength_m", "damperCompression_m", ...
    "conditioning", "damperMotionRatio", "installationRatio", ...
    "rockerAngularGain_rad_per_m", "motionRatioMigration"];
for index = 1:numel(columnFields)
    value = analysis.(columnFields(index));
    if ~isnumeric(value) || ~isreal(value) || ...
            ~isequal(size(value), [count, 1])
        invalid("Analysis curve fields must be real N-by-1 arrays.");
    end
end
if ~isequal(analysis.actuationIdentity, actuation.identity) || ...
        ~isequal(analysis.requestedWheelTravel_m, ...
        sweep.requestedWheelTravel_m) || ...
        ~isequaln(analysis.achievedWheelTravel_m, ...
        sweep.achievedWheelTravel_m) || ...
        ~isequal(analysis.converged, sweep.converged) || ...
        ~isequaln(analysis.rockerAngle_rad, sweep.rockerAngle_rad) || ...
        ~isequaln(analysis.damperLength_m, sweep.damperLength_m) || ...
        ~isequaln(analysis.damperCompression_m, ...
        sweep.damperCompression_m) || ...
        ~isequaln(analysis.conditioning, sweep.conditioning) || ...
        ~isstruct(analysis.states) || ~iscolumn(analysis.states) || ...
        numel(analysis.states) ~= count
    invalid("Analysis identity or source aggregates are inconsistent.");
end
for index = 1:count
    fsd.analysis.validateActuationAnalysis( ...
        analysis.states(index), actuation, sweep.results(index));
end
expectedStatuses = reshape(string({analysis.states.actuationStatus}), [], 1);
if ~isequal(analysis.actuationStatus, expectedStatuses) || ...
        any(analysis.installationRatio(~isnan(analysis.installationRatio)) < 0) || ...
        any(abs(analysis.installationRatio - ...
        abs(analysis.damperMotionRatio)) > 100*eps, "all")
    invalid("Analysis status or installation ratio is inconsistent.");
end
strictlyMonotonic = isStrictlyMonotonic(sweep.requestedWheelTravel_m) && ...
    isStrictlyMonotonic(sweep.achievedWheelTravel_m);
if sweep.allConverged && count >= 3 && strictlyMonotonic
    zeroIndices = find(sweep.requestedWheelTravel_m == 0);
    if isscalar(zeroIndices)
        expectedMotionRatioStatus = "AVAILABLE";
    else
        expectedMotionRatioStatus = "AVAILABLE_STATIC_REFERENCE_MISSING";
    end
    if string(analysis.motionRatioStatus) ~= expectedMotionRatioStatus
        invalid("A valid monotonic sweep must publish derivative curves.");
    end
    expectedMotionRatio = secondOrderDerivative( ...
        sweep.achievedWheelTravel_m, sweep.damperCompression_m);
    expectedAngularGain = secondOrderDerivative( ...
        sweep.achievedWheelTravel_m, sweep.rockerAngle_rad);
    if ~isequaln(analysis.damperMotionRatio, expectedMotionRatio) || ...
            ~isequaln(analysis.rockerAngularGain_rad_per_m, ...
            expectedAngularGain)
        invalid("Motion ratio or rocker angular gain is inconsistent.");
    end
else
    if ~sweep.allConverged
        expectedMotionRatioStatus = "UNAVAILABLE_ACTUATION_FAILURE";
    elseif count < 3
        expectedMotionRatioStatus = "UNAVAILABLE_INVALID_WHEEL_TRAVEL";
    else
        expectedMotionRatioStatus = ...
            "UNAVAILABLE_NONMONOTONIC_WHEEL_TRAVEL";
    end
    if string(analysis.motionRatioStatus) ~= expectedMotionRatioStatus
        invalid("Unavailable derivative status is inconsistent.");
    end
    if ~all(isnan(analysis.damperMotionRatio)) || ...
            ~all(isnan(analysis.installationRatio)) || ...
            ~all(isnan(analysis.rockerAngularGain_rad_per_m))
        invalid("Unavailable derivative curves must use NaN.");
    end
end
if analysis.staticReferenceAvailable
    index = analysis.staticReferenceIndex;
    if ~isnumeric(index) || ~isscalar(index) || ~isfinite(index) || ...
            index < 1 || index > count || index ~= round(index) || ...
            analysis.requestedWheelTravel_m(index) ~= 0 || ...
            analysis.staticDamperMotionRatio ~= ...
            analysis.damperMotionRatio(index) || ...
            any(abs(analysis.motionRatioMigration - ...
            (analysis.damperMotionRatio - ...
            analysis.staticDamperMotionRatio)) > 100*eps)
        invalid("Static motion-ratio reference is inconsistent.");
    end
else
    if ~isnan(analysis.staticReferenceIndex) || ...
            ~isnan(analysis.staticDamperMotionRatio) || ...
            ~all(isnan(analysis.motionRatioMigration))
        invalid("Unavailable static reference must use NaN fields.");
    end
end
if sweep.allConverged
    if string(analysis.analysisStatus) ~= "CONVERGED" || ...
            analysis.minimumDamperLength_m ~= min(sweep.damperLength_m) || ...
            analysis.maximumDamperLength_m ~= max(sweep.damperLength_m) || ...
            analysis.totalRequiredStroke_m ~= ...
            max(sweep.damperLength_m)-min(sweep.damperLength_m) || ...
            analysis.maximumCompression_m ~= ...
            max([sweep.damperCompression_m;0]) || ...
            analysis.maximumExtension_m ~= ...
            max([-sweep.damperCompression_m;0]) || ...
            analysis.minimumRockerAngle_rad ~= min(sweep.rockerAngle_rad) || ...
            analysis.maximumRockerAngle_rad ~= max(sweep.rockerAngle_rad) || ...
            analysis.rockerAngularExcursion_rad ~= ...
            max(sweep.rockerAngle_rad)-min(sweep.rockerAngle_rad)
        invalid("Converged sweep range metrics are inconsistent.");
    end
else
    rangeFields = ["minimumDamperLength_m", "maximumDamperLength_m", ...
        "maximumCompression_m", "maximumExtension_m", ...
        "totalRequiredStroke_m", "minimumRockerAngle_rad", ...
        "maximumRockerAngle_rad", "rockerAngularExcursion_rad"];
    for index = 1:numel(rangeFields)
        if ~isnan(analysis.(rangeFields(index)))
            invalid("Failed sweep range metrics must be NaN.");
        end
    end
end
isValid = true;
end

function tf = isStrictlyMonotonic(value)
steps = diff(value);
tf = all(steps > 0) || all(steps < 0);
end

function invalid(message, varargin)
error("fsd:analysis:InvalidActuationSweepAnalysis", message, varargin{:});
end
