function isValid = validateAxleRollAnalysis(value)
%VALIDATEAXLEROLLANALYSIS Validate the v0.6 scalar roll analysis contract.

required = ["schemaVersion", "kind", "axleIdentity", "axleId", ...
    "bodyRollAngle_rad", "axleHeave_m", "wheelTravel_m", ...
    "wheelTravelDifferential_m", "converged", "status", ...
    "kinematicStatus", "failureReason", "chassisCamber_rad", ...
    "roadCamber_rad", "toe_rad", "leftInstantCenterY_m", ...
    "leftInstantCenterZ_m", "rightInstantCenterY_m", ...
    "rightInstantCenterZ_m", "rollCenterStatus", "rollCenterY_m", ...
    "rollCenterZ_m", "rollCenterHeight_m", ...
    "rollCenterHeightStatus", "rollCenterRoadHeight_m", ...
    "rollCenterRoadHeightStatus", "wheelCenterTrack_m", ...
    "geometricContactTrack_m", "wheelCenterTrackChange_m", ...
    "geometricContactTrackChange_m", "reference", "roadLine", ...
    "axleStateAnalysis", "left", "right", "analysisElapsedTime_s"];
if ~isstruct(value) || ~isscalar(value) || ~all(isfield(value, required)) || ...
        string(value.schemaVersion) ~= "0.6.0" || ...
        string(value.kind) ~= "AxleRollAnalysis" || ...
        ~isFiniteScalar(value.bodyRollAngle_rad) || ...
        abs(value.bodyRollAngle_rad) >= pi/2 || ...
        ~isFiniteScalar(value.axleHeave_m) || ...
        ~islogical(value.converged) || ~isscalar(value.converged) || ...
        ~isFiniteScalar(value.analysisElapsedTime_s) || ...
        value.analysisElapsedTime_s < 0
    invalid("AxleRollAnalysis has an invalid aggregate contract.");
end
try
    fsd.model.validateAxleIdentity(value.axleIdentity);
catch cause
    exception = MException("fsd:analysis:InvalidAxleRollAnalysis", ...
        "AxleRollAnalysis contains an invalid axle identity.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
if string(value.axleId) ~= string(value.axleIdentity.axleId)
    invalid("AxleRollAnalysis axleId contradicts its identity.");
end
validateReference(value.reference);
if value.converged
    finitePairs = [value.wheelTravel_m; value.chassisCamber_rad; ...
        value.roadCamber_rad; value.toe_rad];
    finiteScalars = [value.wheelTravelDifferential_m, ...
        value.wheelCenterTrack_m, value.geometricContactTrack_m, ...
        value.wheelCenterTrackChange_m, ...
        value.geometricContactTrackChange_m];
    if string(value.status) ~= "CONVERGED" || ...
            string(value.kinematicStatus) ~= "CONVERGED" || ...
            strlength(string(value.failureReason)) ~= 0 || ...
            ~isequal(size(finitePairs), [4,2]) || ...
            any(~isfinite(finitePairs), "all") || ...
            any(~isfinite(finiteScalars)) || ...
            ~isFiniteScalar(value.reference.wheelCenterTrack_m) || ...
            ~isFiniteScalar(value.reference.geometricContactTrack_m) || ...
            value.geometricContactTrack_m <= 0 || ...
            abs(value.wheelTravelDifferential_m - ...
            (value.wheelTravel_m(1)-value.wheelTravel_m(2))) > tolerance()
        invalid("Converged roll analysis metrics are inconsistent.");
    end
    if ~isstruct(value.axleStateAnalysis) || ...
            string(value.axleStateAnalysis.kind) ~= "AxleRollCenterAnalysis" || ...
            ~isequal(value.axleStateAnalysis.axleIdentity, value.axleIdentity) || ...
            ~isstruct(value.roadLine) || string(value.roadLine.status) ~= "FINITE"
        invalid("Converged roll analysis lacks valid nested geometry.");
    end
    validateDerivedMetrics(value);
    if string(value.rollCenterStatus) == "FINITE"
        if ~isFiniteScalar(value.rollCenterY_m) || ...
                ~isFiniteScalar(value.rollCenterZ_m) || ...
                ~isFiniteScalar(value.rollCenterRoadHeight_m) || ...
                string(value.rollCenterRoadHeightStatus) ~= "DEFINED"
            invalid("Finite roll center metrics are inconsistent.");
        end
    elseif ~isnan(value.rollCenterRoadHeight_m) || ...
            string(value.rollCenterRoadHeightStatus) == "DEFINED"
        invalid("Non-finite roll centers cannot publish a road height.");
    end
else
    metrics = [value.wheelTravel_m, value.wheelTravelDifferential_m, ...
        value.chassisCamber_rad, value.roadCamber_rad, value.toe_rad, ...
        value.leftInstantCenterY_m, value.leftInstantCenterZ_m, ...
        value.rightInstantCenterY_m, value.rightInstantCenterZ_m, ...
        value.rollCenterY_m, value.rollCenterZ_m, ...
        value.rollCenterHeight_m, value.rollCenterRoadHeight_m, ...
        value.wheelCenterTrack_m, value.geometricContactTrack_m, ...
        value.wheelCenterTrackChange_m, ...
        value.geometricContactTrackChange_m];
    if string(value.status) ~= "KINEMATICS_NOT_CONVERGED" || ...
            ~ismember(string(value.kinematicStatus), ["NOT_ATTEMPTED", ...
            "ROOT_NOT_BRACKETED", "KINEMATIC_NONCONVERGENCE", ...
            "SCALAR_NO_CONVERGENCE", "CONTACT_DEGENERATE", ...
            "COINCIDENT_CONTACTS", "INVERTED_CONTACT_ORDER"]) || ...
            strlength(string(value.failureReason)) == 0 || ...
            any(~isnan(metrics)) || ~isempty(fieldnames(value.roadLine)) || ...
            ~isempty(fieldnames(value.axleStateAnalysis))
        invalid("Failed roll analysis must not publish valid metrics.");
    end
end
isValid = true;
end

function validateReference(value)
required = ["bodyRollAngle_rad", "axleHeave_m", ...
    "wheelCenterTrack_m", "geometricContactTrack_m"];
if ~isstruct(value) || ~isscalar(value) || ~all(isfield(value, required)) || ...
        value.bodyRollAngle_rad ~= 0 || value.axleHeave_m ~= 0
    invalid("Roll analysis reference must be the static zero-roll state.");
end
end

function validateDerivedMetrics(value)
base = value.axleStateAnalysis;
leftAxis = base.left.geometricContact.wheelAxis;
rightAxis = base.right.geometricContact.wheelAxis;
leftId = value.axleIdentity.leftGeometryIdentity.cornerId;
rightId = value.axleIdentity.rightGeometryIdentity.cornerId;
expectedChassis = [fsd.analysis.camberFromWheelAxis(leftAxis, leftId), ...
    fsd.analysis.camberFromWheelAxis(rightAxis, rightId)];
expectedRoad = [fsd.analysis.roadRelativeCamber( ...
    leftAxis, leftId, value.bodyRollAngle_rad), ...
    fsd.analysis.roadRelativeCamber( ...
    rightAxis, rightId, value.bodyRollAngle_rad)];
expectedToe = [fsd.analysis.toeFromWheelAxis(leftAxis, leftId), ...
    fsd.analysis.toeFromWheelAxis(rightAxis, rightId)];
leftCenter = base.left.geometricContact.wheelCenter_m;
rightCenter = base.right.geometricContact.wheelCenter_m;
leftContact = base.left.geometricContact.point_m;
rightContact = base.right.geometricContact.point_m;
expectedWheelTrack = rightCenter(2)-leftCenter(2);
expectedContactTrack = dot(value.roadLine.direction_yz, ...
    rightContact(2:3)-leftContact(2:3));
if max(abs(value.chassisCamber_rad-expectedChassis)) > tolerance() || ...
        max(abs(value.roadCamber_rad-expectedRoad)) > tolerance() || ...
        max(abs(value.toe_rad-expectedToe)) > tolerance() || ...
        abs(value.wheelCenterTrack_m-expectedWheelTrack) > tolerance() || ...
        abs(value.geometricContactTrack_m-expectedContactTrack) > tolerance() || ...
        abs(value.wheelCenterTrackChange_m - ...
        (expectedWheelTrack-value.reference.wheelCenterTrack_m)) > tolerance() || ...
        abs(value.geometricContactTrackChange_m - ...
        (expectedContactTrack-value.reference.geometricContactTrack_m)) > tolerance() || ...
        ~isequaln([value.leftInstantCenterY_m,value.leftInstantCenterZ_m], ...
        [base.left.instantCenter.instantCenterY_m, ...
        base.left.instantCenter.instantCenterZ_m]) || ...
        ~isequaln([value.rightInstantCenterY_m,value.rightInstantCenterZ_m], ...
        [base.right.instantCenter.instantCenterY_m, ...
        base.right.instantCenter.instantCenterZ_m]) || ...
        ~isequaln([value.rollCenterY_m,value.rollCenterZ_m, ...
        value.rollCenterHeight_m], [base.rollCenterY_m,base.rollCenterZ_m, ...
        base.rollCenterHeight_m])
    invalid("Roll analysis derived metrics contradict nested geometry.");
end
if string(value.rollCenterStatus) == "FINITE"
    expectedHeight = fsd.geometry.signedDistanceToRoadLine( ...
        [value.rollCenterY_m,value.rollCenterZ_m], value.roadLine);
    if abs(value.rollCenterRoadHeight_m-expectedHeight) > tolerance()
        invalid("Road-relative roll-center height is inconsistent.");
    end
end
end

function value = tolerance()
t = fsd.model.numericTolerances();
value = 10 * (t.AbsTol_m + t.RelTol);
end

function tf = isFiniteScalar(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && isfinite(value);
end

function invalid(message)
error("fsd:analysis:InvalidAxleRollAnalysis", message);
end
