function isValid = validateAxleRollSweepAnalysis(value)
%VALIDATEAXLEROLLSWEEPANALYSIS Validate v0.6 body-roll sweep analysis.

required = ["schemaVersion", "kind", "axleIdentity", "axleId", ...
    "bodyRollAngle_rad", "axleHeave_m", "converged", ...
    "kinematicStatus", "analysisStatus", "kinematicFailureReason", ...
    "wheelTravel_m", "wheelTravelDifferential_m", ...
    "chassisCamber_rad", "roadCamber_rad", "toe_rad", ...
    "leftInstantCenterY_m", "leftInstantCenterZ_m", ...
    "rightInstantCenterY_m", "rightInstantCenterZ_m", ...
    "rollCenterStatus", "rollCenterY_m", "rollCenterZ_m", ...
    "rollCenterHeight_m", "rollCenterRoadHeight_m", ...
    "rollCenterRoadHeightStatus", "wheelCenterTrack_m", ...
    "geometricContactTrack_m", "wheelCenterTrackChange_m", ...
    "geometricContactTrackChange_m", "reference", "allConverged", ...
    "solverElapsedTime_s", "analysisElapsedTime_s", "states"];
if ~isstruct(value) || ~isscalar(value) || ~all(isfield(value, required)) || ...
        string(value.schemaVersion) ~= "0.6.0" || ...
        string(value.kind) ~= "AxleRollSweepAnalysis" || ...
        ~isnumeric(value.bodyRollAngle_rad) || ...
        ~iscolumn(value.bodyRollAngle_rad) || isempty(value.bodyRollAngle_rad) || ...
        any(~isfinite(value.bodyRollAngle_rad)) || ...
        any(abs(value.bodyRollAngle_rad) >= pi/2) || ...
        ~isnumeric(value.axleHeave_m) || ~isscalar(value.axleHeave_m) || ...
        ~isfinite(value.axleHeave_m) || ...
        ~isstruct(value.states) || ~iscolumn(value.states) || ...
        numel(value.states) ~= numel(value.bodyRollAngle_rad) || ...
        ~islogical(value.converged) || ~iscolumn(value.converged) || ...
        ~isstring(value.kinematicStatus) || ...
        ~iscolumn(value.kinematicStatus) || ...
        ~isstring(value.analysisStatus) || ~iscolumn(value.analysisStatus) || ...
        ~isstring(value.kinematicFailureReason) || ...
        ~iscolumn(value.kinematicFailureReason) || ...
        ~islogical(value.allConverged) || ~isscalar(value.allConverged) || ...
        ~isFiniteNonnegativeScalar(value.solverElapsedTime_s) || ...
        ~isFiniteNonnegativeScalar(value.analysisElapsedTime_s)
    invalid("AxleRollSweepAnalysis has an invalid aggregate contract.");
end
count = numel(value.states);
if numel(value.converged) ~= count || ...
        numel(value.kinematicStatus) ~= count || ...
        numel(value.analysisStatus) ~= count || ...
        numel(value.kinematicFailureReason) ~= count || ...
        ~isequal(size(value.wheelTravel_m), [count,2]) || ...
        ~isequal(size(value.chassisCamber_rad), [count,2]) || ...
        ~isequal(size(value.roadCamber_rad), [count,2]) || ...
        ~isequal(size(value.toe_rad), [count,2])
    invalid("Sweep analysis aggregate arrays have invalid dimensions.");
end
try
    fsd.model.validateAxleIdentity(value.axleIdentity);
catch cause
    exception = MException("fsd:analysis:InvalidAxleRollSweepAnalysis", ...
        "Sweep analysis contains an invalid axle identity.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
for index = 1:numel(value.states)
    fsd.analysis.validateAxleRollAnalysis(value.states(index));
    if ~isequal(value.states(index).axleIdentity, value.axleIdentity) || ...
            value.states(index).bodyRollAngle_rad ~= ...
            value.bodyRollAngle_rad(index) || ...
            value.states(index).axleHeave_m ~= value.axleHeave_m
        invalid("A contained roll analysis does not match its sweep.");
    end
end
expectedConverged = reshape([value.states.converged], [], 1);
if ~isequal(value.converged, expectedConverged) || ...
        value.allConverged ~= all(expectedConverged) || ...
        ~isequal(value.kinematicStatus, ...
        stringsOf(value.states, "kinematicStatus")) || ...
        ~isequal(value.analysisStatus, stringsOf(value.states, "status")) || ...
        ~isequal(value.kinematicFailureReason, ...
        stringsOf(value.states, "failureReason")) || ...
        ~isequaln(value.wheelTravel_m, rows(value.states, "wheelTravel_m", 2)) || ...
        ~isequaln(value.wheelTravelDifferential_m, ...
        column(value.states, "wheelTravelDifferential_m")) || ...
        ~isequaln(value.chassisCamber_rad, ...
        rows(value.states, "chassisCamber_rad", 2)) || ...
        ~isequaln(value.roadCamber_rad, ...
        rows(value.states, "roadCamber_rad", 2)) || ...
        ~isequaln(value.toe_rad, rows(value.states, "toe_rad", 2)) || ...
        ~isequaln(value.leftInstantCenterY_m, ...
        column(value.states, "leftInstantCenterY_m")) || ...
        ~isequaln(value.leftInstantCenterZ_m, ...
        column(value.states, "leftInstantCenterZ_m")) || ...
        ~isequaln(value.rightInstantCenterY_m, ...
        column(value.states, "rightInstantCenterY_m")) || ...
        ~isequaln(value.rightInstantCenterZ_m, ...
        column(value.states, "rightInstantCenterZ_m")) || ...
        ~isequal(value.rollCenterStatus, ...
        stringsOf(value.states, "rollCenterStatus")) || ...
        ~isequaln(value.rollCenterY_m, column(value.states, "rollCenterY_m")) || ...
        ~isequaln(value.rollCenterZ_m, column(value.states, "rollCenterZ_m")) || ...
        ~isequaln(value.rollCenterHeight_m, ...
        column(value.states, "rollCenterHeight_m")) || ...
        ~isequaln(value.rollCenterRoadHeight_m, ...
        column(value.states, "rollCenterRoadHeight_m")) || ...
        ~isequaln(value.wheelCenterTrack_m, ...
        column(value.states, "wheelCenterTrack_m")) || ...
        ~isequaln(value.geometricContactTrack_m, ...
        column(value.states, "geometricContactTrack_m")) || ...
        ~isequaln(value.wheelCenterTrackChange_m, ...
        column(value.states, "wheelCenterTrackChange_m")) || ...
        ~isequaln(value.geometricContactTrackChange_m, ...
        column(value.states, "geometricContactTrackChange_m"))
    invalid("Sweep aggregates contradict their contained analyses.");
end
isValid = true;
end

function value = column(states, field)
value = reshape([states.(field)], [], 1);
end

function value = rows(states, field, width)
value = reshape([states.(field)], width, []).';
end

function value = stringsOf(states, field)
value = reshape(string({states.(field)}), [], 1);
end

function tf = isFiniteNonnegativeScalar(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0;
end

function invalid(message)
error("fsd:analysis:InvalidAxleRollSweepAnalysis", message);
end
