function isValid = validateActuationAnalysis(analysis, actuation, result)
%VALIDATEACTUATIONANALYSIS Validate a scalar actuation analysis.

if ~isstruct(analysis) || ~isscalar(analysis)
    invalid("ActuationAnalysis must be a scalar struct.");
end
required = ["schemaVersion", "kind", "actuationIdentity", ...
    "cornerId", "actuationType", "attachmentBody", ...
    "sourceResultKind", "wheelTravel_m", "converged", ...
    "actuationStatus", "failureReason", "rockerAngle_rad", ...
    "damperLength_m", "damperCompression_m", ...
    "actuationRodLengthResidual_m", "conditioning", ...
    "isIllConditioned"];
if any(~isfield(analysis, required)) || ...
        string(analysis.schemaVersion) ~= "0.7.0" || ...
        string(analysis.kind) ~= "ActuationAnalysis"
    invalid("Unsupported or incomplete ActuationAnalysis schema.");
end
fsd.model.validateActuationGeometry(actuation);
fsd.kinematics.validateActuationResult(result, actuation);
if ~isequal(analysis.actuationIdentity, actuation.identity) || ...
        string(analysis.cornerId) ~= string(result.cornerId) || ...
        string(analysis.actuationType) ~= string(result.actuationType) || ...
        string(analysis.attachmentBody) ~= string(result.attachmentBody) || ...
        string(analysis.sourceResultKind) ~= string(result.sourceResultKind) || ...
        ~isequaln(analysis.wheelTravel_m, ...
        result.sourceAchievedWheelTravel_m) || ...
        analysis.converged ~= result.converged || ...
        string(analysis.actuationStatus) ~= string(result.status) || ...
        string(analysis.failureReason) ~= string(result.failureReason) || ...
        ~isequaln(analysis.rockerAngle_rad, result.rockerAngle_rad) || ...
        ~isequaln(analysis.damperLength_m, result.damperLength_m) || ...
        ~isequaln(analysis.damperCompression_m, ...
        result.damperCompression_m) || ...
        ~isequaln(analysis.actuationRodLengthResidual_m, ...
        result.actuationRodLengthResidual_m) || ...
        ~isequaln(analysis.conditioning, result.conditioning) || ...
        analysis.isIllConditioned ~= result.isIllConditioned
    invalid("ActuationAnalysis contradicts its result or geometry.");
end
isValid = true;
end

function invalid(message, varargin)
error("fsd:analysis:InvalidActuationAnalysis", message, varargin{:});
end
