function output = actuationKinematicsExample(showPlots)
%ACTUATIONKINEMATICSEXAMPLE Demonstrate v0.7 geometric actuation.
%   Example geometry only -- not a Formula Student design recommendation.

if nargin < 1
    showPlots = true;
end
geometry = exampleGeometry();
definition = exampleDefinition("YZ_PLANE", "PUSHROD");
actuation = fsd.model.createActuationGeometry( ...
    geometry, definition, "m");

staticKinematics = fsd.kinematics.solveBump(geometry, 0, "mm");
bumpKinematics = fsd.kinematics.solveBump(geometry, 15, "mm");
reboundKinematics = fsd.kinematics.solveBump(geometry, -15, "mm");
staticActuation = fsd.kinematics.solveActuation( ...
    actuation, staticKinematics);
bumpActuation = fsd.kinematics.solveActuation( ...
    actuation, bumpKinematics);
reboundActuation = fsd.kinematics.solveActuation( ...
    actuation, reboundKinematics);

bumpSweep = fsd.kinematics.solveBumpSweep( ...
    geometry, (-20:2:20)', "mm");
actuationSweep = fsd.kinematics.solveActuationSweep( ...
    actuation, bumpSweep);
analysis = fsd.analysis.analyzeActuationSweep( ...
    actuation, actuationSweep);

customDefinition = exampleDefinition("CUSTOM", "PULLROD");
customActuation = fsd.model.createActuationGeometry( ...
    geometry, customDefinition, "m");
customResult = fsd.kinematics.solveActuation( ...
    customActuation, bumpKinematics);

fprintf("Actuation type: %s; rocker preset: %s\n", ...
    actuation.actuationType, actuation.rocker.orientationMode);
fprintf("Bump rocker angle: %.4f deg; damper compression: %.4f mm\n", ...
    bumpActuation.rockerAngle_rad*180/pi, ...
    bumpActuation.damperCompression_m*1000);
fprintf("Required geometric damper stroke: %.4f mm\n", ...
    analysis.totalRequiredStroke_m*1000);
fprintf("Rocker angular excursion: %.4f deg\n", ...
    analysis.rockerAngularExcursion_rad*180/pi);
fprintf("Example geometry only -- not a Formula Student design recommendation.\n");

figures = gobjects(0);
if showPlots
    figures(1) = figure("Name", "Actuation state");
    fsd.kinematics.plotActuationResult( ...
        actuation, bumpActuation, axes(figures(1)));
    figures(2) = figure("Name", "Actuation curves");
    fsd.analysis.plotActuationSweep(analysis, figures(2));
    figures(3) = figure("Name", "CUSTOM tilted rocker");
    fsd.kinematics.plotActuationResult( ...
        customActuation, customResult, axes(figures(3)));
end

output = struct( ...
    "geometry", geometry, ...
    "actuation", actuation, ...
    "static", staticActuation, ...
    "bump", bumpActuation, ...
    "rebound", reboundActuation, ...
    "bumpSweep", bumpSweep, ...
    "actuationSweep", actuationSweep, ...
    "analysis", analysis, ...
    "customActuation", customActuation, ...
    "customResult", customResult, ...
    "figures", figures);
end

function geometry = exampleGeometry()
corner = "FL";
ids = corner + "_" + fsd.model.requiredHardpointRoles();
xyz_m = [ ...
    -0.10,-0.30,0.40; 0.10,-0.30,0.40; 0,-0.60,0.40; ...
    -0.10,-0.30,0.10; 0.10,-0.30,0.10; 0,-0.60,0.10; ...
    0.05,-0.30,0.25; 0.05,-0.60,0.25; ...
    0,-0.65,0.25; 0,-0.65,0];
provenance = struct( ...
    "sourceKind", repmat("ASSUMED",10,3), ...
    "sourceNote", repmat("Example-only analytic geometry",10,3));
geometry = fsd.model.createDoubleWishboneGeometry( ...
    corner, ids, xyz_m, "m", [0,-1,0], provenance);
end

function definition = exampleDefinition(mode, actuationType)
if mode == "YZ_PLANE"
    axis = struct("point", [0,0,0]);
    radial = [0,0.1,0];
    tangent = [0,0,0.1];
else
    direction = [1,2,3];
    direction = direction/norm(direction);
    radial = cross(direction,[0,0,1]);
    radial = 0.1*radial/norm(radial);
    tangent = cross(direction,radial);
    axis = struct("point", [0,0,0], "direction", direction);
end
definition = struct( ...
    "actuationType", actuationType, ...
    "suspensionAttachment", struct( ...
        "body", "UPRIGHT", "point", 1.5*radial+tangent), ...
    "rocker", struct( ...
        "orientationMode", mode, "axis", axis, ...
        "actuationRodPoint", radial, "damperPoint", tangent), ...
    "damper", struct( ...
        "chassisPoint", tangent+[0.12,-0.08,0.06]), ...
    "metadata", struct("purpose", "EXAMPLE_ONLY"));
end
