function output = bodyRollKinematicsExample(showPlots)
%BODYROLLKINEMATICSEXAMPLE Demonstrate v0.6 axle body-roll kinematics.
%   Example geometry only -- not a Formula Student setup recommendation.

if nargin < 1
    showPlots = true;
end
base = axleRollCenterExample(false);
axle = base.axle;
zero = fsd.kinematics.solveAxleRoll(axle, 0, 0, "deg", "mm");
positive = fsd.kinematics.solveAxleRoll(axle, 2, 0, "deg", "mm");
negative = fsd.kinematics.solveAxleRoll(axle, -2, 0, "deg", "mm");
if ~(zero.converged && positive.converged && negative.converged)
    error("fsd:example:BodyRollKinematicsDidNotConverge", ...
        "The fictitious v0.6 scalar roll cases did not converge.");
end

roll_deg = (-3:0.25:3)';
sweep = fsd.kinematics.solveAxleRollSweep( ...
    axle, roll_deg, 0, "deg", "mm");
if ~sweep.allConverged
    error("fsd:example:BodyRollKinematicsDidNotConverge", ...
        "The fictitious v0.6 roll sweep did not converge.");
end
zeroAnalysis = fsd.analysis.analyzeAxleRoll(axle, zero);
positiveAnalysis = fsd.analysis.analyzeAxleRoll(axle, positive);
negativeAnalysis = fsd.analysis.analyzeAxleRoll(axle, negative);
sweepAnalysis = fsd.analysis.analyzeAxleRollSweep(axle, sweep);

% Existing steering accepts the solved asymmetric wheel travels. This is a
% kinematically closed steering state, but it is not exact body-roll closure
% after steering because steering changes the geometric wheel contacts.
steering = fsd.model.createSteeringSystem(axle, 1600, "mm");
steered = fsd.kinematics.solveSteering( ...
    steering, 5, positive.wheelTravel_m * 1000, "mm");
if ~steered.converged
    error("fsd:example:SteeringIntegrationDidNotConverge", ...
        "The demonstration steering integration did not converge.");
end

summary = table([0;2;-2], ...
    1000*[zero.wheelTravel_m(1); positive.wheelTravel_m(1); ...
    negative.wheelTravel_m(1)], ...
    1000*[zero.wheelTravel_m(2); positive.wheelTravel_m(2); ...
    negative.wheelTravel_m(2)], ...
    VariableNames=["BodyRoll_deg", "LeftTravel_mm", "RightTravel_mm"]);
disp(summary);

plotHandles = struct();
if showPlots
    frontFigure = figure("Name", "v0.6 body-roll front view");
    plotHandles.frontView = fsd.analysis.plotAxleRollFrontView( ...
        positiveAnalysis, axes(frontFigure));
    sweepFigure = figure("Name", "v0.6 body-roll curves");
    plotHandles.sweep = fsd.analysis.plotAxleRollSweep( ...
        sweepAnalysis, sweepFigure);
end

output = struct( ...
    "axle", axle, "zeroResult", zero, "positiveResult", positive, ...
    "negativeResult", negative, "zeroAnalysis", zeroAnalysis, ...
    "positiveAnalysis", positiveAnalysis, ...
    "negativeAnalysis", negativeAnalysis, "sweep", sweep, ...
    "sweepAnalysis", sweepAnalysis, "steeringSystem", steering, ...
    "steeredResult", steered, "summary", summary, ...
    "timing", struct("solver_s", sweep.elapsedTime_s, ...
        "analysis_s", sweepAnalysis.analysisElapsedTime_s), ...
    "steeringLimitation", ...
        "Wheel travels are reused, but road closure is not re-solved after steering.", ...
    "plotHandles", plotHandles);
end
