function output = globalStaticEquilibriumExample(showPlots)
%GLOBALSTATICEQUILIBRIUMEXAMPLE Four real solved mechanisms; illustrative ASSUMED inputs.
if nargin < 1, showPlots = true; end
corners = ["FL";"FR";"RL";"RR"]; sources = cell(4,1); tires = cell(4,1);
base = [ -.1,-.3,.4;.1,-.3,.4;0,-.6,.4;-.1,-.3,.1;.1,-.3,.1;0,-.6,.1; ...
    .05,-.3,.25;.05,-.6,.25;0,-.65,.25;0,-.65,0];
provenance = struct("sourceKind","ASSUMED","sourceNote","Illustrative four-corner geometry only");
for i = 1:4
    mirror = diag([1,1-2*mod(i+1,2),1]); shift = [2*floor((i-1)/2),0,0];
    geometry = fsd.model.createDoubleWishboneGeometry(corners(i), ...
        corners(i)+"_"+fsd.model.requiredHardpointRoles(),base*mirror+shift,"m",[0,-1,0]*mirror,provenance);
    definition = struct("actuationType","PUSHROD", ...
        "suspensionAttachment",struct("body","UPRIGHT","point",[0,.15,.1]*mirror+shift), ...
        "rocker",struct("orientationMode","YZ_PLANE","axis",struct("point",shift), ...
        "actuationRodPoint",[0,.1,0]*mirror+shift,"damperPoint",[0,0,.1]*mirror+shift), ...
        "damper",struct("chassisPoint",[.12,-.08,.16]*mirror+shift));
    actuation = fsd.model.createActuationGeometry(geometry,definition,"m");
    md = struct("configuration","COILOVER", ...
        "spring",struct("modelType","LINEAR_COMPRESSION","rate",20000,"freeLength",.2,"preloadCompression",.045), ...
        "damper",struct("modelType","LINEAR_ASYMMETRIC","compressionCoefficient",1500,"reboundCoefficient",2500), ...
        "metadata",struct("sourceKind","ASSUMED","sourceNote","Illustrative mechanics"));
    model = fsd.model.createSpringDamperModel(actuation,md,struct("length","m", ...
        "springRate","N/m","dampingCoefficient","N*s/m","velocity","m/s"));
    bump = fsd.kinematics.solveBumpSweep(geometry,(-.025:.0005:.025)',"m");
    sweep = fsd.kinematics.solveActuationSweep(actuation,bump);
    analysis = fsd.analysis.analyzeActuationSweep(actuation,sweep);
    mechanical = fsd.analysis.analyzeSpringDamperSweep(model,actuation,sweep,analysis,0,"m/s");
    sources{i} = struct("geometry",geometry,"actuation",actuation,"springDamper",model, ...
        "mechanical",mechanical,"pathKind","ACTUATION_BUMP_3D");
    tires{i} = fsd.model.createVerticalTireModel(struct("cornerId",corners(i), ...
        "modelType","LINEAR_VERTICAL_UNILATERAL","stiffness",100000,"unloadedRadius",.25, ...
        "sourceKind","ASSUMED","sourceNote","Illustrative vertical stiffness, not measured tire data"), ...
        struct("length","m","stiffness","N/m"));
end
vehicle = fsd.model.createVehicleParameters(struct("wheelbase",2,"frontTrack",1.3,"rearTrack",1.3, ...
    "gravity_mps2",10,"operatingConfiguration","GLOBAL_EXAMPLE","massMode","TOTAL_MASS", ...
    "sourceKind","ASSUMED","totalMass",200,"cg",[1,0,.3], ...
    "includes","ILLUSTRATIVE_COMPLETE_VEHICLE","unsprungMass",repmat(5,4,1)), ...
    struct("length","m","mass","kg","gravity","m/s^2"));
loadCase = fsd.model.createVehicleLoadCase(vehicle, ...
    struct("mode","CROSSWEIGHT_SPECIFIED","crossweight",.5,"sourceKind","ASSUMED"));
system = fsd.model.createGlobalStaticSystem(vehicle,loadCase,sources,tires, ...
    struct("massApproximation","KNOWN_UNSPRUNG_MASSES", ...
    "unsprungPositionAssumption","UNSPRUNG_MASS_AT_WHEEL_CENTER", ...
    "rideHeightPointsBody_m",[.4,0,.12;1.6,0,.12],"rideHeightPointIds",["FRONT_REFERENCE";"REAR_REFERENCE"]));
options = struct("bounds",[-.06,.06;-.1,.1;-.1,.1;repmat([-.02,.02],4,1)], ...
    "coordinateScales",[.02;.05;.05;repmat(.02,4,1)], ...
    "forceTolerance_N",1e-5,"momentTolerance_Nm",1e-6,"positionTolerance_m",1e-9, ...
    "angleTolerance_rad",1e-9,"stabilityTolerance_J",1e-8);
result = fsd.analysis.solveGlobalStaticEquilibrium(system,[-.005;zeros(6,1)],options);
figures = gobjects(0);
fprintf("Global sampled-path result: %s; alternatives %d\n",result.status,numel(result.alternatives));
if isfinite(result.selectedIndex)
    a = result.alternatives{result.selectedIndex}; state = a.state;
    fprintf("h %.6f m; pitch %.6f rad; roll %.6f rad; CW %.6f\n",state.q(1:3),state.crossweightActualSumFraction);
    fprintf("Travels [m]: "); fprintf("%.6f ",state.q(4:7)); fprintf("\nNormals [N]: ");
    fprintf("%.6f ",state.normalForces_N); fprintf("\nMoments [Nm]: ");
    fprintf("%.3g ",state.worldMomentResidual_Nm); fprintf("\n");
    for i = 1:4
        fprintf("%s %s; Fs %.6f N\n",corners(i),state.corners{i}.tire.contactStatus, ...
            state.corners{i}.spring.springAxialForce_N);
    end
    fprintf("Defined reference heights [m]: "); fprintf("%.6f ",state.rideHeights_m); fprintf("\n");
    if showPlots, figures = fsd.analysis.plotGlobalStaticEquilibrium(system,result); end
else
    fprintf("No alternative selected under %s; retained roots are diagnostics, not a selected setup.\n", ...
        result.solverOptions.selection);
end
fprintf("ASSUMED example only; vertical ideal tire; sampled paths; not an FS setup recommendation.\n");
output = struct("system",system,"result",result,"options",options,"figures",figures);
end
