function output = springDamperWheelRateExample(showPlots)
%SPRINGDAMPERWHEELRATEEXAMPLE v0.8 ideal coilover on existing rocker geometry.
% Example geometry and mechanical parameters only — not a Formula Student
% setup recommendation. Parameters are assumed demonstration inputs.
if nargin < 1, showPlots = true; end
base = actuationKinematicsExample(false);
definition = struct("configuration","COILOVER", ...
    "spring",struct("modelType","LINEAR_COMPRESSION","rate",30, ...
    "freeLength",200,"preloadCompression",10,"solidHeight",120), ...
    "damper",struct("modelType","LINEAR_ASYMMETRIC", ...
    "compressionCoefficient",1.5,"reboundCoefficient",2.5, ...
    "minimumLength",100,"maximumLength",200), ...
    "metadata",struct("sourceKind","ASSUMED","sourceNote","Example-only mechanical parameters"));
units = struct("length","mm","springRate","N/mm", ...
    "dampingCoefficient","N/(mm/s)","velocity","mm/s");
model = fsd.model.createSpringDamperModel(base.actuation,definition,units);
velocities = linspace(-100,100,numel(base.actuationSweep.results))';
analysis = fsd.analysis.analyzeSpringDamperSweep(model,base.actuation, ...
    base.actuationSweep,base.analysis,velocities,"mm/s");
fsd.analysis.validateSpringDamperSweepAnalysis(analysis,model,base.actuation);
nominal = fsd.analysis.analyzeSpringDamperState(model,base.static);
% Narrow explicit bounds demonstrate infeasibility without inventing stops.
limitedDefinition = definition;
length0_mm = fsd.model.convertMechanicalUnits(base.actuation.damper.staticLength_m,"length","m","mm");
limitedDefinition.damper.minimumLength = length0_mm-4;
limitedDefinition.damper.maximumLength = length0_mm+4;
limitedDefinition.spring.solidHeight = 189;
limitedModel = fsd.model.createSpringDamperModel(base.actuation,limitedDefinition,units);
limitedAnalysis = fsd.analysis.analyzeSpringDamperSweep(limitedModel,base.actuation, ...
    base.actuationSweep,base.analysis,velocities,"mm/s");
fprintf("Nominal axial preload force: %.3f N (not corner load or sag).\n",nominal.state.springAxialForce_N);
fprintf("Nominal tangent rate: %.4f N/mm; geometric contribution: %.4f N/mm.\n", ...
    analysis.nominalWheelRate_N_per_m/1000,analysis.nominalGeometricWheelRate_N_per_m/1000);
fprintf("Limited-path infeasible samples: %d; coil-bind boundary/exceeded: %d.\n", ...
    sum(~limitedAnalysis.feasibleRelativeToProvidedLimits), ...
    sum(ismember(limitedAnalysis.springSolidStatus,["COIL_BIND_LIMIT","COIL_BIND_EXCEEDED"])));
fprintf("Example geometry and mechanical parameters only — not a Formula Student setup recommendation.\n");
figures = gobjects(0);
if showPlots
    figures(1) = figure("Name","v0.8 mechanical response");
    fsd.analysis.plotSpringDamperSweep(analysis,model,base.actuation,figures(1));
    figures(2) = figure("Name","v0.8 explicit limits");
    fsd.analysis.plotSpringDamperSweep(limitedAnalysis,limitedModel,base.actuation,figures(2));
end
output = struct("geometry",base.geometry,"actuation",base.actuation, ...
    "bumpSweep",base.bumpSweep,"actuationSweep",base.actuationSweep, ...
    "actuationAnalysis",base.analysis,"model",model,"analysis",analysis, ...
    "nominal",nominal,"limitedModel",limitedModel,"limitedAnalysis",limitedAnalysis, ...
    "figures",figures);
end
