function output = steeringKinematicsExample(showPlots)
%STEERINGKINEMATICSEXAMPLE Demonstrate v0.5 rack steering and analysis.
%   All geometry is fictitious and is not a Formula Student recommendation.

if nargin < 1
    showPlots = true;
end
base = axleRollCenterExample(false);
steering = fsd.model.createSteeringSystem(base.axle, 1600, "mm");
zero = fsd.kinematics.solveSteering(steering, 0, 0, "mm");
positive = fsd.kinematics.solveSteering(steering, 10, 0, "mm");
negative = fsd.kinematics.solveSteering(steering, -10, 0, "mm");
combined = fsd.kinematics.solveSteering( ...
    steering, 8, [15, 10], "mm");
rackTravel_mm = (-20:2:20)';
sweep = fsd.kinematics.solveRackSweep( ...
    steering, rackTravel_mm, 0, "mm");
analysisZero = fsd.analysis.analyzeSteering(steering, zero);
analysisPositive = fsd.analysis.analyzeSteering(steering, positive);
analysisNegative = fsd.analysis.analyzeSteering(steering, negative);
analysisCombined = fsd.analysis.analyzeSteering(steering, combined);
sweepAnalysis = fsd.analysis.analyzeRackSweep(steering, sweep);
if ~(zero.converged && positive.converged && negative.converged && ...
        combined.converged && sweep.allConverged)
    error("fsd:example:SteeringKinematicsDidNotConverge", ...
        "The fictitious v0.5 steering example did not converge.");
end
plotHandles = struct();
if showPlots
    geometryFigure = figure("Name", "v0.5 steering geometry");
    plotHandles.geometry = fsd.analysis.plotSteeringSystem( ...
        steering, positive, analysisPositive, axes(geometryFigure));
    curvesFigure = figure("Name", "v0.5 steering curves");
    plotHandles.curves = fsd.analysis.plotSteeringSweep( ...
        sweepAnalysis, curvesFigure);
end
output = struct( ...
    "steeringSystem", steering, ...
    "rackAxis", steering.rackGeometry.axisDirection, ...
    "zeroResult", zero, ...
    "positiveResult", positive, ...
    "negativeResult", negative, ...
    "combinedResult", combined, ...
    "zeroAnalysis", analysisZero, ...
    "positiveAnalysis", analysisPositive, ...
    "negativeAnalysis", analysisNegative, ...
    "combinedAnalysis", analysisCombined, ...
    "sweep", sweep, ...
    "sweepAnalysis", sweepAnalysis, ...
    "timing", struct("solver_s", sweep.elapsedTime_s, ...
        "analysis_s", sweepAnalysis.analysisElapsedTime_s), ...
    "plotHandles", plotHandles);
end
