function output = vehicleStaticEquilibriumExample(showPlots)
%VEHICLESTATICEQUILIBRIUMEXAMPLE Illustrative masses/loads and local path equilibrium.
% All example parameters ASSUMED; not an optimized FS setup or fabrication data.
if nargin < 1, showPlots = true; end
components = [struct("id","BASE","mass",200,"cg",[0.8,0,0.3], ...
    "includes",["CHASSIS_AND_SYSTEMS","ALL_UNSPRUNG_ASSEMBLIES"],"sourceKind","ASSUMED"); ...
    struct("id","DRIVER","mass",60,"cg",[0.9,0.03,0.5], ...
    "includes","DRIVER","sourceKind","ASSUMED"); ...
    struct("id","FUEL","mass",5,"cg",[1.1,0,0.25], ...
    "includes","FUEL","sourceKind","ASSUMED")];
definition = struct("wheelbase",1.6,"frontTrack",1.2,"rearTrack",1.15, ...
    "gravity_mps2",9.81,"operatingConfiguration","DRIVER_AND_FUEL", ...
    "massMode","COMPONENT_MASSES","components",components,"sourceKind","ASSUMED", ...
    "unsprungMass",[8,8,9,9],"metadata",struct("note","Illustrative static FS concept only"));
units = struct("length","m","mass","kg","gravity","m/s^2");
vehicle = fsd.model.createVehicleParameters(definition,units);
aloneDefinition = definition; aloneDefinition.components = components(1);
aloneDefinition.operatingConfiguration = "VEHICLE_ALONE";
alone = fsd.model.createVehicleParameters(aloneDefinition,units);
openCase = fsd.model.createVehicleLoadCase(vehicle,struct("mode","UNDERDETERMINED","sourceKind","DERIVED"));
openLoads = fsd.analysis.analyzeStaticVehicleLoads(vehicle,openCase);
closedCase = fsd.model.createVehicleLoadCase(vehicle, ...
    struct("mode","CROSSWEIGHT_SPECIFIED","crossweight",50,"sourceKind","TARGET"), ...
    struct("force","N","crossweight","%"));
loads = fsd.analysis.analyzeStaticVehicleLoads(vehicle,closedCase);
aloneCase = fsd.model.createVehicleLoadCase(alone, ...
    struct("mode","CROSSWEIGHT_SPECIFIED","crossweight",0.5,"sourceKind","TARGET"));
aloneLoads = fsd.analysis.analyzeStaticVehicleLoads(alone,aloneCase);
base = springDamperWheelRateExample(false);
mechanicalDefinition = struct("configuration","COILOVER", ...
    "spring",struct("modelType","LINEAR_COMPRESSION","rate",60000, ...
    "freeLength",0.2,"preloadCompression",0.02,"solidHeight",0.12), ...
    "damper",struct("modelType","LINEAR_ASYMMETRIC","compressionCoefficient",1500, ...
    "reboundCoefficient",2500,"minimumLength",0.10,"maximumLength",0.20), ...
    "metadata",struct("sourceKind","ASSUMED","sourceNote","Demonstration only"));
mechanicalUnits = struct("length","m","springRate","N/m","dampingCoefficient","N*s/m","velocity","m/s");
model = fsd.model.createSpringDamperModel(base.actuation,mechanicalDefinition,mechanicalUnits);
mechanical = fsd.analysis.analyzeSpringDamperSweep(model,base.actuation, ...
    base.actuationSweep,base.actuationAnalysis,0,"m/s");
options = struct("rootSelection","NEAREST_REFERENCE","referenceTravel_m",0, ...
    "demandSourceKind","DERIVED","demandSourceNote","FL normal minus explicitly assumed unsprung weight");
equilibrium = fsd.analysis.solveCornerStaticEquilibrium(model,base.actuation,mechanical,loads.supportForce_N(1),options);
aloneEquilibrium = fsd.analysis.solveCornerStaticEquilibrium(model,base.actuation,mechanical,aloneLoads.supportForce_N(1),options);
comparison = fsd.analysis.compareStaticVehicleCases(alone,aloneLoads,vehicle,loads,aloneEquilibrium,equilibrium);
fprintf("Mass %.3f kg; CG [%.4f %.4f %.4f] m; F/R %.3f/%.3f N\n", ...
    vehicle.totalMass_kg,vehicle.cg_m,loads.frontAxleLoad_N,loads.rearAxleLoad_N);
fprintf("Open case: %s; closed CW %.3f%%; corner normals [N]:\n",openLoads.status,100*loads.crossweightFraction);
disp(loads.cornerLoads_N');
fprintf("FL prescribed support %.3f N; local roots %d; selected travel %.4f mm\n", ...
    equilibrium.targetSupport_N,equilibrium.rootCount,1000*equilibrium.equilibriumWheelTravel_m);
fprintf("Local sampled-path estimate only; NOT coupled chassis equilibrium or real ride height.\n");
figures = gobjects(0);
if showPlots
    figures(1) = figure("Name","v0.9 indeterminate loads");
    fsd.analysis.plotStaticVehicleLoads(vehicle,openLoads,figures(1));
    figures(2) = figure("Name","v0.9 crossweight closure");
    fsd.analysis.plotStaticVehicleLoads(vehicle,loads,figures(2));
    figures(3) = figure("Name","v0.9 local corner equilibrium");
    fsd.analysis.plotCornerStaticEquilibrium(equilibrium,figures(3));
end
output = struct("vehicle",vehicle,"aloneVehicle",alone,"loadCase",closedCase, ...
    "loads",loads,"openLoads",openLoads,"aloneLoads",aloneLoads,"model",model, ...
    "actuation",base.actuation,"mechanical",mechanical,"equilibrium",equilibrium, ...
    "aloneEquilibrium",aloneEquilibrium,"comparison",comparison,"figures",figures);
end
