function settings = rollSolverSettings(overrides)
%ROLLSOLVERSETTINGS Numerical settings for v0.6 body-roll closure.

settings = struct( ...
    "MaxRollStep_rad", pi / 720, ...
    "InitialBracketHalfWidth_m", 0.005, ...
    "MaxBracketExpansions", 10, ...
    "MaxBoundaryRefinements", 20, ...
    "BoundaryRefinementTolerance_m", 1e-8, ...
    "MaxRootIterations", 50, ...
    "MaxRootEvaluations", 100, ...
    "RootStepTolerance_m", 1e-10, ...
    "RollResidualTolerance_m", 1e-9, ...
    "RollAngleTolerance_rad", 1e-9, ...
    "CornerSolverOptions", struct());
if nargin < 1 || isempty(overrides)
    settings.CornerSolverOptions = fsd.kinematics.solverSettings(struct());
    return
end
if ~isstruct(overrides) || ~isscalar(overrides)
    error("fsd:kinematics:InvalidRollOptions", ...
        "Roll solver options must be a scalar struct.");
end
requested = string(fieldnames(overrides));
allowed = string(fieldnames(settings));
unknown = requested(~ismember(requested, allowed));
if ~isempty(unknown)
    error("fsd:kinematics:InvalidRollOptions", ...
        "Unknown roll solver option: %s", unknown(1));
end
for index = 1:numel(requested)
    settings.(requested(index)) = overrides.(requested(index));
end
positive = ["MaxRollStep_rad", "InitialBracketHalfWidth_m", ...
    "MaxBracketExpansions", "MaxBoundaryRefinements", ...
    "BoundaryRefinementTolerance_m", ...
    "MaxRootIterations", "MaxRootEvaluations", ...
    "RootStepTolerance_m", "RollResidualTolerance_m", ...
    "RollAngleTolerance_rad"];
for name = positive
    value = settings.(name);
    if ~isnumeric(value) || ~isreal(value) || ~isscalar(value) || ...
            ~isfinite(value) || value <= 0
        error("fsd:kinematics:InvalidRollOptions", ...
            "%s must be a positive finite scalar.", name);
    end
end
settings.MaxBracketExpansions = floor(settings.MaxBracketExpansions);
settings.MaxBoundaryRefinements = floor(settings.MaxBoundaryRefinements);
settings.MaxRootIterations = floor(settings.MaxRootIterations);
settings.MaxRootEvaluations = floor(settings.MaxRootEvaluations);
settings.CornerSolverOptions = fsd.kinematics.solverSettings( ...
    settings.CornerSolverOptions);
end
