function sweep = solveActuationSweep(actuation, bumpSweep)
%SOLVEACTUATIONSWEEP Solve an ordered BumpSweepResult with continuation.

fsd.model.validateActuationGeometry(actuation);
fsd.kinematics.validateBumpSweepResult(bumpSweep);
if ~isequal(bumpSweep.geometryIdentity, ...
        actuation.cornerGeometryIdentity)
    error("fsd:kinematics:ActuationGeometryMismatch", ...
        "Bump sweep belongs to another corner geometry.");
end

timer = tic;
count = numel(bumpSweep.results);
resultCells = cell(count, 1);
referenceAngle_rad = 0;
branchAvailable = true;
rockerClosureSolveCount = 0;
notAttemptedCount = 0;
for index = 1:count
    source = bumpSweep.results(index);
    if ~branchAvailable
        resultCells{index} = notAttemptedResult(actuation, source, ...
            "Not attempted after an earlier actuation continuation failure.");
        notAttemptedCount = notAttemptedCount + 1;
        continue
    end
    resultCells{index} = solveActuationCore( ...
        actuation, source, referenceAngle_rad);
    rockerClosureSolveCount = rockerClosureSolveCount + ...
        double(resultCells{index}.diagnostics.attempted);
    if resultCells{index}.converged
        referenceAngle_rad = resultCells{index}.rockerAngle_rad;
    else
        branchAvailable = false;
    end
end
results = vertcat(resultCells{:});
converged = reshape([results.converged], [], 1);
sweep = struct( ...
    "schemaVersion", "0.7.0", ...
    "kind", "ActuationSweepResult", ...
    "actuationIdentity", actuation.identity, ...
    "sourceGeometryIdentity", bumpSweep.geometryIdentity, ...
    "sourceSweepKind", string(bumpSweep.kind), ...
    "requestedWheelTravel_m", bumpSweep.requestedWheelTravel_m, ...
    "achievedWheelTravel_m", reshape( ...
        [results.sourceAchievedWheelTravel_m], [], 1), ...
    "rockerAngle_rad", reshape([results.rockerAngle_rad], [], 1), ...
    "damperLength_m", reshape([results.damperLength_m], [], 1), ...
    "damperCompression_m", reshape( ...
        [results.damperCompression_m], [], 1), ...
    "conditioning", reshape([results.conditioning], [], 1), ...
    "converged", converged, ...
    "allConverged", all(converged), ...
    "elapsedTime_s", toc(timer), ...
    "performance", struct( ...
        "rockerClosureSolveCount", rockerClosureSolveCount, ...
        "notAttemptedCount", notAttemptedCount), ...
    "results", results);
fsd.kinematics.validateActuationSweepResult(sweep, actuation);
end

function result = notAttemptedResult(actuation, source, message)
diagnostics = struct( ...
    "solver", "CLOSED_FORM_CIRCLE_SPHERE", "attempted", false, ...
    "sourceKinematicStatus", string(source.status), ...
    "sourceKinematicFailureReason", string(source.failureReason), ...
    "constraintCase", "NOT_ATTEMPTED", ...
    "referenceRockerAngle_rad", NaN, ...
    "candidateAngles_rad", NaN(1,0), ...
    "selectedCandidateIndex", NaN, "acosRatio", NaN, ...
    "alpha_rad", NaN, "coefficientTolerance_m2", NaN, ...
    "derivativeMagnitude_m2", NaN, ...
    "attachmentTransform", struct(), ...
    "rockerCircleCenter_m", [NaN,NaN,NaN], ...
    "rockerCircleRadius_m", NaN, ...
    "constraintA_m2", NaN, "constraintB_m2", NaN, ...
    "constraintD_m2", NaN, "constraintR_m2", NaN);
result = struct( ...
    "schemaVersion", "0.7.0", "kind", "ActuationResult", ...
    "actuationIdentity", actuation.identity, ...
    "cornerId", string(actuation.cornerId), ...
    "actuationType", string(actuation.actuationType), ...
    "attachmentBody", string(actuation.suspensionAttachment.body), ...
    "sourceResultKind", string(source.kind), "sourceResult", source, ...
    "sourceGeometryIdentity", source.geometryIdentity, ...
    "sourceRequestedWheelTravel_m", source.requestedWheelTravel_m, ...
    "sourceAchievedWheelTravel_m", source.achievedWheelTravel_m, ...
    "sourceKinematicStatus", string(source.status), ...
    "sourceKinematicFailureReason", string(source.failureReason), ...
    "converged", false, "status", "NOT_ATTEMPTED", ...
    "failureReason", string(message), ...
    "suspensionAttachmentCurrent_m", [NaN,NaN,NaN], ...
    "rockerRodPointCurrent_m", [NaN,NaN,NaN], ...
    "rockerDamperPointCurrent_m", [NaN,NaN,NaN], ...
    "rockerAngle_rad", NaN, "rockerAngleWrapped_rad", NaN, ...
    "damperLength_m", NaN, "damperCompression_m", NaN, ...
    "actuationRodLength_m", NaN, ...
    "actuationRodLengthResidual_m", NaN, "conditioning", NaN, ...
    "isIllConditioned", false, "diagnostics", diagnostics);
end
