function sweep = solveAxleRollSweep(axle, bodyRollAngle, axleHeave, ...
    angleUnit, lengthUnit, options)
%SOLVEAXLEROLLSWEEP Solve an ordered body-roll path at constant axle heave.

if nargin < 6
    options = struct();
end
fsd.model.validateAxleGeometry(axle);
angles_rad = fsd.model.convertAngleToRadians(bodyRollAngle, angleUnit);
heave_m = fsd.model.convertLengthToMetres(axleHeave, lengthUnit);
if ~isvector(angles_rad) || isempty(angles_rad) || ~isscalar(heave_m)
    error("fsd:kinematics:InvalidAxleRollTarget", ...
        "Roll sweep must be a nonempty angle vector and scalar axle heave.");
end
angles_rad = double(angles_rad(:));
for angle = angles_rad.'
    fsd.geometry.bodyRollRoadFrame(angle);
end
settings = fsd.kinematics.rollSolverSettings(options);
timer = tic;
results = solveAxleRollPath(axle, angles_rad, heave_m, settings);
converged = reshape([results.converged], [], 1);
elapsed_s = toc(timer);
performance = aggregatePerformance(results, elapsed_s);
sweep = struct( ...
    "schemaVersion", "0.6.0", ...
    "kind", "AxleRollSweepResult", ...
    "axleIdentity", fsd.model.axleIdentity(axle), ...
    "requestedBodyRollAngle_rad", angles_rad, ...
    "requestedAxleHeave_m", double(heave_m), ...
    "converged", converged, ...
    "status", reshape(string({results.status}), [], 1), ...
    "allConverged", all(converged), ...
    "elapsedTime_s", elapsed_s, ...
    "performance", performance, ...
    "results", results);
fsd.kinematics.validateAxleRollSweepResult(sweep);
end

function value = aggregatePerformance(results, wallTime_s)
paths = arrayfun(@(result) result.diagnostics.path, results);
value = struct( ...
    "wallTime_s", wallTime_s, ...
    "internalScalarStates", sum([paths.scalarSolves]), ...
    "heaveStates", sum([paths.heaveStates]), ...
    "rollStates", sum([paths.rollStates]), ...
    "uniqueFunctionEvaluations", sum([paths.uniqueFunctionEvaluations]), ...
    "cornerSolves", sum([paths.cornerSolves]), ...
    "objectiveRequests", sum([paths.objectiveRequests]), ...
    "cacheHits", sum([paths.cacheHits]), ...
    "boundaryRefinements", sum([paths.boundaryRefinements]), ...
    "bracketElapsedTime_s", sum([paths.bracketElapsedTime_s]), ...
    "rootElapsedTime_s", sum([paths.rootElapsedTime_s]));
end
