function sweep = solveAxleHeaveSweep(axle, wheelTravel, inputUnit, options)
%SOLVEAXLEHEAVESWEEP Compatibility wrapper for equal axle travel paths.

if nargin < 4
    options = struct();
end
requested_m = fsd.model.convertLengthToMetres(wheelTravel, inputUnit);
if ~isvector(requested_m) || isempty(requested_m)
    error("fsd:kinematics:InvalidWheelTravel", ...
        "Axle heave wheelTravel must be a nonempty finite real vector.");
end
requested_m = double(requested_m(:));
general = fsd.kinematics.solveAxleTravelSweep( ...
    axle, [requested_m, requested_m], "m", options);
count = numel(requested_m);
cells = cell(count, 1);
for index = 1:count
    cells{index} = historicalResult(general.results(index), ...
        requested_m(index));
end
results = vertcat(cells{:});
sweep = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "AxleHeaveSweepResult", ...
    "axleIdentity", general.axleIdentity, ...
    "requestedWheelTravel_m", requested_m, ...
    "converged", general.converged, ...
    "leftConverged", general.leftConverged, ...
    "rightConverged", general.rightConverged, ...
    "status", general.status, ...
    "allConverged", general.allConverged, ...
    "elapsedTime_s", general.elapsedTime_s, ...
    "leftSweep", general.leftSweep, ...
    "rightSweep", general.rightSweep, ...
    "results", results);
fsd.kinematics.validateAxleHeaveSweepResult(sweep);
end

function result = historicalResult(general, requested_m)
result = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "AxleKinematicResult", ...
    "axleIdentity", general.axleIdentity, ...
    "requestedWheelTravel_m", double(requested_m), ...
    "converged", general.converged, ...
    "status", general.status, ...
    "failureReason", general.failureReason, ...
    "leftConverged", general.leftConverged, ...
    "rightConverged", general.rightConverged, ...
    "leftResult", general.leftResult, ...
    "rightResult", general.rightResult, ...
    "elapsedTime_s", 0);
end
