function sweep = solveRackSweep(steering, rackTravel, wheelTravel, ...
    inputUnit, options)
%SOLVERACKSWEEP Solve an ordered rack path after prescribed wheel travel.

if nargin < 5
    options = struct();
end
fsd.model.validateSteeringSystemGeometry(steering);
rackTravel_m = fsd.model.convertLengthToMetres(rackTravel, inputUnit);
wheelTravel_m = fsd.model.convertLengthToMetres(wheelTravel, inputUnit);
if ~isvector(rackTravel_m) || isempty(rackTravel_m)
    error("fsd:kinematics:InvalidRackTravel", ...
        "rackTravel must be a nonempty finite real vector.");
end
rackTravel_m = double(rackTravel_m(:));
wheelTravel_m = normalizeWheelTravel(wheelTravel_m);
settings = fsd.kinematics.solverSettings(options);
timer = tic;
rack = steering.rackGeometry;
leftRaw = solvePath(steering.frontAxleGeometry.leftGeometry, ...
    rack.leftInnerStatic_m, rack.axisDirection, rackTravel_m, ...
    wheelTravel_m(1), settings);
rightRaw = solvePath(steering.frontAxleGeometry.rightGeometry, ...
    rack.rightInnerStatic_m, rack.axisDirection, rackTravel_m, ...
    wheelTravel_m(2), settings);
count = numel(rackTravel_m);
resultCells = cell(count, 1);
for index = 1:count
    left = steeringCornerResultFromRaw(steering, ...
        steering.frontAxleGeometry.leftGeometry, leftRaw(index + 1), ...
        leftRaw(1), rackTravel_m(index));
    right = steeringCornerResultFromRaw(steering, ...
        steering.frontAxleGeometry.rightGeometry, rightRaw(index + 1), ...
        rightRaw(1), rackTravel_m(index));
    resultCells{index} = composeResult(steering, rackTravel_m(index), ...
        wheelTravel_m, left, right);
end
results = vertcat(resultCells{:});
sweep = struct( ...
    "schemaVersion", "0.5.0", ...
    "kind", "RackSweepResult", ...
    "steeringSystemIdentity", steering.identity, ...
    "requestedRackTravel_m", rackTravel_m, ...
    "requestedWheelTravel_m", wheelTravel_m, ...
    "converged", reshape([results.converged], [], 1), ...
    "status", reshape(string({results.status}), [], 1), ...
    "allConverged", all([results.converged]), ...
    "elapsedTime_s", toc(timer), ...
    "results", results);
fsd.kinematics.validateRackSweepResult(sweep, steering);
end

function wheelTravel_m = normalizeWheelTravel(value)
if isscalar(value)
    wheelTravel_m = [value, value];
elseif isvector(value) && numel(value) == 2
    wheelTravel_m = reshape(double(value), 1, 2);
else
    error("fsd:kinematics:InvalidWheelTravel", ...
        "wheelTravel must be a scalar or a two-element [left,right] vector.");
end
end

function raw = solvePath(geometry, staticInner_m, rackAxis, ...
        rackTravel_m, wheelTravel_m, settings)
wheelPath_m = [wheelTravel_m; repmat(wheelTravel_m, ...
    numel(rackTravel_m), 1)];
tiePath_m = [staticInner_m; staticInner_m + rackTravel_m .* rackAxis];
raw = solveCornerPath(geometry, wheelPath_m, tiePath_m, settings);
end

function result = composeResult(steering, rackTravel_m, wheelTravel_m, ...
        left, right)
converged = left.converged && right.converged;
if converged
    status = "CONVERGED";
    failureReason = "";
    achievedRackTravel_m = rackTravel_m;
elseif string(left.status) == "NOT_ATTEMPTED" && ...
        string(right.status) == "NOT_ATTEMPTED"
    status = "NOT_ATTEMPTED";
    failureReason = "Neither steering corner was attempted.";
    achievedRackTravel_m = NaN;
else
    status = "NO_CONVERGENCE";
    failureReason = "At least one steering corner did not converge.";
    achievedRackTravel_m = NaN;
end
result = struct( ...
    "schemaVersion", "0.5.0", ...
    "kind", "SteeringAxleResult", ...
    "steeringSystemIdentity", steering.identity, ...
    "requestedRackTravel_m", rackTravel_m, ...
    "achievedRackTravel_m", achievedRackTravel_m, ...
    "requestedWheelTravel_m", wheelTravel_m, ...
    "leftResult", left, ...
    "rightResult", right, ...
    "leftConverged", logical(left.converged), ...
    "rightConverged", logical(right.converged), ...
    "converged", logical(converged), ...
    "status", status, ...
    "failureReason", failureReason, ...
    "diagnostics", struct( ...
        "left", left.diagnostics, ...
        "right", right.diagnostics, ...
        "bilateralConverged", logical(converged)), ...
    "elapsedTime_s", 0);
end
