function result = solveSteering(steering, rackTravel, wheelTravel, ...
    inputUnit, options)
%SOLVESTEERING Solve one front-axle rack and prescribed wheel-travel state.

if nargin < 5
    options = struct();
end
fsd.model.validateSteeringSystemGeometry(steering);
rackTravel_m = fsd.model.convertLengthToMetres(rackTravel, inputUnit);
wheelTravel_m = fsd.model.convertLengthToMetres(wheelTravel, inputUnit);
if ~isscalar(rackTravel_m)
    error("fsd:kinematics:InvalidRackTravel", ...
        "rackTravel must be a finite real scalar.");
end
wheelTravel_m = normalizeWheelTravel(wheelTravel_m);
settings = fsd.kinematics.solverSettings(options);
timer = tic;
[leftResult, rightResult] = solvePair(steering, rackTravel_m, ...
    wheelTravel_m, settings);
result = composeResult(steering, rackTravel_m, wheelTravel_m, ...
    leftResult, rightResult, toc(timer));
fsd.kinematics.validateSteeringResult(result, steering);
end

function wheelTravel_m = normalizeWheelTravel(value)
if isscalar(value)
    wheelTravel_m = [value, value];
elseif isvector(value) && numel(value) == 2
    wheelTravel_m = reshape(double(value), 1, 2);
else
    error("fsd:kinematics:InvalidWheelTravel", ...
        "wheelTravel must be a scalar or a two-element [left,right] vector.");
end
end

function [leftResult, rightResult] = solvePair(steering, rackTravel_m, ...
        wheelTravel_m, settings)
rack = steering.rackGeometry;
[leftResult, ~] = solveSide(steering, ...
    steering.frontAxleGeometry.leftGeometry, ...
    rack.leftInnerStatic_m, rack.axisDirection, rackTravel_m, ...
    wheelTravel_m(1), settings);
[rightResult, ~] = solveSide(steering, ...
    steering.frontAxleGeometry.rightGeometry, ...
    rack.rightInnerStatic_m, rack.axisDirection, rackTravel_m, ...
    wheelTravel_m(2), settings);
end

function [result, raw] = solveSide(steering, geometry, staticInner_m, rackAxis, ...
        rackTravel_m, wheelTravel_m, settings)
targetInner_m = staticInner_m + rackTravel_m * rackAxis;
wheelPath_m = [wheelTravel_m; wheelTravel_m];
tiePath_m = [staticInner_m; targetInner_m];
raw = solveCornerPath(geometry, wheelPath_m, tiePath_m, settings);
result = steeringCornerResultFromRaw(steering, geometry, raw(2), raw(1), ...
    rackTravel_m);
end

function result = composeResult(steering, rackTravel_m, wheelTravel_m, ...
        left, right, elapsed_s)
converged = left.converged && right.converged;
if converged
    status = "CONVERGED";
    failureReason = "";
    achievedRackTravel_m = rackTravel_m;
elseif string(left.status) == "NOT_ATTEMPTED" && ...
        string(right.status) == "NOT_ATTEMPTED"
    status = "NOT_ATTEMPTED";
    failureReason = "Neither steering corner was attempted.";
    achievedRackTravel_m = NaN;
else
    status = "NO_CONVERGENCE";
    failureReason = "At least one steering corner did not converge.";
    achievedRackTravel_m = NaN;
end
result = struct( ...
    "schemaVersion", "0.5.0", ...
    "kind", "SteeringAxleResult", ...
    "steeringSystemIdentity", steering.identity, ...
    "requestedRackTravel_m", rackTravel_m, ...
    "achievedRackTravel_m", achievedRackTravel_m, ...
    "requestedWheelTravel_m", wheelTravel_m, ...
    "leftResult", left, ...
    "rightResult", right, ...
    "leftConverged", logical(left.converged), ...
    "rightConverged", logical(right.converged), ...
    "converged", logical(converged), ...
    "status", status, ...
    "failureReason", failureReason, ...
    "diagnostics", struct( ...
        "left", left.diagnostics, ...
        "right", right.diagnostics, ...
        "bilateralConverged", logical(converged)), ...
    "elapsedTime_s", elapsed_s);
end
