function sweep = solveAxleTravelSweep(axle, wheelTravel, inputUnit, options)
%SOLVEAXLETRAVELSWEEP Solve an ordered N-by-2 axle travel path.

if nargin < 4
    options = struct();
end
fsd.model.validateAxleGeometry(axle);
requested_m = fsd.model.convertLengthToMetres(wheelTravel, inputUnit);
if ~isnumeric(requested_m) || ~isreal(requested_m) || ...
        size(requested_m, 2) ~= 2 || isempty(requested_m)
    error("fsd:kinematics:InvalidWheelTravel", ...
        "Axle travel sweep must be a nonempty N-by-2 matrix.");
end
requested_m = double(requested_m);
timer = tic;
leftSweep = fsd.kinematics.solveBumpSweep( ...
    axle.leftGeometry, requested_m(:,1), "m", options);
rightSweep = fsd.kinematics.solveBumpSweep( ...
    axle.rightGeometry, requested_m(:,2), "m", options);
count = size(requested_m, 1);
cells = cell(count, 1);
for index = 1:count
    cells{index} = composeAxleTravelResult(axle, requested_m(index,:), ...
        leftSweep.results(index), rightSweep.results(index), 0);
end
results = vertcat(cells{:});
converged = reshape([results.converged], [], 1);
sweep = struct( ...
    "schemaVersion", "0.6.0", ...
    "kind", "AxleTravelSweepResult", ...
    "axleIdentity", fsd.model.axleIdentity(axle), ...
    "requestedWheelTravel_m", requested_m, ...
    "converged", converged, ...
    "leftConverged", reshape([results.leftConverged], [], 1), ...
    "rightConverged", reshape([results.rightConverged], [], 1), ...
    "status", reshape(string({results.status}), [], 1), ...
    "allConverged", all(converged), ...
    "elapsedTime_s", toc(timer), ...
    "leftSweep", leftSweep, ...
    "rightSweep", rightSweep, ...
    "results", results);
fsd.kinematics.validateAxleTravelSweepResult(sweep);
end
