function result = solveAxleHeave(axle, wheelTravel, inputUnit, options)
%SOLVEAXLEHEAVE Compatibility wrapper for equal left/right axle travel.

if nargin < 4
    options = struct();
end
requested_m = fsd.model.convertLengthToMetres(wheelTravel, inputUnit);
if ~isscalar(requested_m)
    error("fsd:kinematics:InvalidWheelTravel", ...
        "Axle heave wheelTravel must be a finite real scalar.");
end
general = fsd.kinematics.solveAxleTravel( ...
    axle, [requested_m, requested_m], "m", options);
result = historicalResult(general, requested_m);
fsd.kinematics.validateAxleKinematicResult(result);
end

function result = historicalResult(general, requested_m)
result = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "AxleKinematicResult", ...
    "axleIdentity", general.axleIdentity, ...
    "requestedWheelTravel_m", double(requested_m), ...
    "converged", general.converged, ...
    "status", general.status, ...
    "failureReason", general.failureReason, ...
    "leftConverged", general.leftConverged, ...
    "rightConverged", general.rightConverged, ...
    "leftResult", general.leftResult, ...
    "rightResult", general.rightResult, ...
    "elapsedTime_s", general.elapsedTime_s);
end
