function result = solveAxleHeave(axle, wheelTravel, inputUnit, options)
%SOLVEAXLEHEAVE Solve equal left/right wheel travel for one axle state.

if nargin < 4
    options = struct();
end
fsd.model.validateAxleGeometry(axle);
requested_m = fsd.model.convertLengthToMetres(wheelTravel, inputUnit);
if ~isscalar(requested_m)
    error("fsd:kinematics:InvalidWheelTravel", ...
        "Axle heave wheelTravel must be a finite real scalar.");
end

timer = tic;
leftResult = fsd.kinematics.solveBump( ...
    axle.leftGeometry, requested_m, "m", options);
rightResult = fsd.kinematics.solveBump( ...
    axle.rightGeometry, requested_m, "m", options);
elapsedTime_s = toc(timer);
result = composeResult(axle, requested_m, leftResult, rightResult, ...
    elapsedTime_s);
fsd.kinematics.validateAxleKinematicResult(result);
end

function result = composeResult(axle, requested_m, leftResult, ...
        rightResult, elapsedTime_s)
[converged, status, failureReason] = aggregateStatus( ...
    leftResult, rightResult);
result = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "AxleKinematicResult", ...
    "axleIdentity", fsd.model.axleIdentity(axle), ...
    "requestedWheelTravel_m", double(requested_m), ...
    "converged", converged, ...
    "status", status, ...
    "failureReason", failureReason, ...
    "leftConverged", logical(leftResult.converged), ...
    "rightConverged", logical(rightResult.converged), ...
    "leftResult", leftResult, ...
    "rightResult", rightResult, ...
    "elapsedTime_s", double(elapsedTime_s));
end

function [converged, status, failureReason] = aggregateStatus(left, right)
converged = left.converged && right.converged;
if converged
    status = "CONVERGED";
    failureReason = "";
elseif string(left.status) == "NOT_ATTEMPTED" && ...
        string(right.status) == "NOT_ATTEMPTED"
    status = "NOT_ATTEMPTED";
    failureReason = "Neither corner target was attempted.";
else
    status = "NO_CONVERGENCE";
    failureReason = "At least one corner did not converge.";
end
end
