function sweep = solveAxleHeaveSweep( ...
    axle, wheelTravel, inputUnit, options)
%SOLVEAXLEHEAVESWEEP Solve equal ordered travel targets on both corners.

if nargin < 4
    options = struct();
end
fsd.model.validateAxleGeometry(axle);
requested_m = fsd.model.convertLengthToMetres(wheelTravel, inputUnit);
if ~isvector(requested_m) || isempty(requested_m)
    error("fsd:kinematics:InvalidWheelTravel", ...
        "Axle heave wheelTravel must be a nonempty finite real vector.");
end
requested_m = requested_m(:);

timer = tic;
leftSweep = fsd.kinematics.solveBumpSweep( ...
    axle.leftGeometry, requested_m, "m", options);
rightSweep = fsd.kinematics.solveBumpSweep( ...
    axle.rightGeometry, requested_m, "m", options);
count = numel(requested_m);
results = repmat(emptyResult(), count, 1);
for index = 1:count
    results(index) = composeResult(axle, requested_m(index), ...
        leftSweep.results(index), rightSweep.results(index));
end
elapsedTime_s = toc(timer);
converged = reshape([results.converged], [], 1);
leftConverged = reshape([results.leftConverged], [], 1);
rightConverged = reshape([results.rightConverged], [], 1);
status = reshape(string({results.status}), [], 1);
sweep = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "AxleHeaveSweepResult", ...
    "axleIdentity", fsd.model.axleIdentity(axle), ...
    "requestedWheelTravel_m", requested_m, ...
    "converged", converged, ...
    "leftConverged", leftConverged, ...
    "rightConverged", rightConverged, ...
    "status", status, ...
    "allConverged", all(converged), ...
    "elapsedTime_s", elapsedTime_s, ...
    "leftSweep", leftSweep, ...
    "rightSweep", rightSweep, ...
    "results", results);
fsd.kinematics.validateAxleHeaveSweepResult(sweep);
end

function result = composeResult(axle, requested_m, leftResult, rightResult)
converged = leftResult.converged && rightResult.converged;
if converged
    status = "CONVERGED";
    failureReason = "";
elseif string(leftResult.status) == "NOT_ATTEMPTED" && ...
        string(rightResult.status) == "NOT_ATTEMPTED"
    status = "NOT_ATTEMPTED";
    failureReason = "Neither corner target was attempted.";
else
    status = "NO_CONVERGENCE";
    failureReason = "At least one corner did not converge.";
end
result = struct( ...
    "schemaVersion", "0.4.0", ...
    "kind", "AxleKinematicResult", ...
    "axleIdentity", fsd.model.axleIdentity(axle), ...
    "requestedWheelTravel_m", double(requested_m), ...
    "converged", converged, ...
    "status", status, ...
    "failureReason", failureReason, ...
    "leftConverged", logical(leftResult.converged), ...
    "rightConverged", logical(rightResult.converged), ...
    "leftResult", leftResult, ...
    "rightResult", rightResult, ...
    "elapsedTime_s", 0);
end

function result = emptyResult()
result = struct( ...
    "schemaVersion", "", "kind", "", "axleIdentity", struct(), ...
    "requestedWheelTravel_m", NaN, "converged", false, ...
    "status", "", "failureReason", "", ...
    "leftConverged", false, "rightConverged", false, ...
    "leftResult", struct(), "rightResult", struct(), ...
    "elapsedTime_s", 0);
end
