function isValid = validateAxleKinematicResult(result)
%VALIDATEAXLEKINEMATICRESULT Validate a composed two-corner axle result.

if ~isstruct(result) || ~isscalar(result)
    invalid("AxleKinematicResult must be a scalar struct.");
end
required = ["schemaVersion", "kind", "axleIdentity", ...
    "requestedWheelTravel_m", "converged", "status", ...
    "failureReason", "leftConverged", "rightConverged", ...
    "leftResult", "rightResult", "elapsedTime_s"];
for index = 1:numel(required)
    if ~isfield(result, required(index))
        invalid("AxleKinematicResult is missing field '%s'.", ...
            required(index));
    end
end
if ~isTextScalar(result.schemaVersion) || ...
        string(result.schemaVersion) ~= "0.4.0" || ...
        ~isTextScalar(result.kind) || ...
        string(result.kind) ~= "AxleKinematicResult"
    invalid("Unsupported or invalid AxleKinematicResult schema.");
end
try
    fsd.model.validateAxleIdentity(result.axleIdentity);
    fsd.kinematics.validateKinematicResult(result.leftResult);
    fsd.kinematics.validateKinematicResult(result.rightResult);
catch cause
    exception = MException("fsd:kinematics:InvalidAxleKinematicResult", ...
        "AxleKinematicResult contains an invalid identity or corner result.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
if ~isequal(result.leftResult.geometryIdentity, ...
        result.axleIdentity.leftGeometryIdentity) || ...
        ~isequal(result.rightResult.geometryIdentity, ...
        result.axleIdentity.rightGeometryIdentity)
    invalid("Corner results do not belong to the declared axle identity.");
end
if ~isnumeric(result.requestedWheelTravel_m) || ...
        ~isreal(result.requestedWheelTravel_m) || ...
        ~isscalar(result.requestedWheelTravel_m) || ...
        ~isfinite(result.requestedWheelTravel_m) || ...
        ~islogical(result.converged) || ~isscalar(result.converged) || ...
        ~islogical(result.leftConverged) || ...
        ~isscalar(result.leftConverged) || ...
        ~islogical(result.rightConverged) || ...
        ~isscalar(result.rightConverged) || ...
        ~isTextScalar(result.status) || ...
        ~isTextScalar(result.failureReason) || ...
        ~isnumeric(result.elapsedTime_s) || ~isreal(result.elapsedTime_s) || ...
        ~isscalar(result.elapsedTime_s) || ~isfinite(result.elapsedTime_s) || ...
        result.elapsedTime_s < 0
    invalid("AxleKinematicResult fields have invalid types or dimensions.");
end
if result.requestedWheelTravel_m ~= ...
        result.leftResult.requestedWheelTravel_m || ...
        result.requestedWheelTravel_m ~= ...
        result.rightResult.requestedWheelTravel_m || ...
        result.leftConverged ~= result.leftResult.converged || ...
        result.rightConverged ~= result.rightResult.converged || ...
        result.converged ~= ...
        (result.leftResult.converged && result.rightResult.converged)
    invalid("Axle result aggregate fields contradict corner results.");
end
expectedStatus = aggregateStatus(result.leftResult, result.rightResult);
if string(result.status) ~= expectedStatus || ...
        (result.converged && strlength(string(result.failureReason)) ~= 0) || ...
        (~result.converged && strlength(string(result.failureReason)) == 0)
    invalid("Axle result status or failure reason is inconsistent.");
end
isValid = true;
end

function status = aggregateStatus(left, right)
if left.converged && right.converged
    status = "CONVERGED";
elseif string(left.status) == "NOT_ATTEMPTED" && ...
        string(right.status) == "NOT_ATTEMPTED"
    status = "NOT_ATTEMPTED";
else
    status = "NO_CONVERGENCE";
end
end

function tf = isTextScalar(value)
tf = (ischar(value) && isrow(value)) || ...
    (isstring(value) && isscalar(value) && ~ismissing(value));
end

function invalid(message, varargin)
error("fsd:kinematics:InvalidAxleKinematicResult", ...
    message, varargin{:});
end
