function isValid = validateAxleTravelResult(result)
%VALIDATEAXLETRAVELRESULT Validate a v0.6 asymmetric axle result.

required = ["schemaVersion", "kind", "axleIdentity", ...
    "requestedWheelTravel_m", "converged", "status", "failureReason", ...
    "leftConverged", "rightConverged", "leftResult", "rightResult", ...
    "diagnostics", "elapsedTime_s"];
if ~isstruct(result) || ~isscalar(result) || ...
        ~all(isfield(result, required)) || ...
        string(result.schemaVersion) ~= "0.6.0" || ...
        string(result.kind) ~= "AxleTravelResult" || ...
        ~isnumeric(result.requestedWheelTravel_m) || ...
        ~isreal(result.requestedWheelTravel_m) || ...
        ~isequal(size(result.requestedWheelTravel_m), [1, 2]) || ...
        any(~isfinite(result.requestedWheelTravel_m)) || ...
        ~islogical(result.converged) || ~isscalar(result.converged) || ...
        ~islogical(result.leftConverged) || ~isscalar(result.leftConverged) || ...
        ~islogical(result.rightConverged) || ...
        ~isscalar(result.rightConverged) || ...
        ~isnumeric(result.elapsedTime_s) || ~isreal(result.elapsedTime_s) || ...
        ~isscalar(result.elapsedTime_s) || ~isfinite(result.elapsedTime_s) || ...
        result.elapsedTime_s < 0
    invalid("AxleTravelResult has an invalid aggregate contract.");
end
try
    fsd.model.validateAxleIdentity(result.axleIdentity);
    fsd.kinematics.validateKinematicResult(result.leftResult);
    fsd.kinematics.validateKinematicResult(result.rightResult);
catch cause
    exception = MException("fsd:kinematics:InvalidAxleTravelResult", ...
        "AxleTravelResult contains an invalid identity or corner result.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
expectedConverged = result.leftResult.converged && result.rightResult.converged;
if ~isequal(result.leftResult.geometryIdentity, ...
        result.axleIdentity.leftGeometryIdentity) || ...
        ~isequal(result.rightResult.geometryIdentity, ...
        result.axleIdentity.rightGeometryIdentity) || ...
        result.leftResult.requestedWheelTravel_m ~= ...
        result.requestedWheelTravel_m(1) || ...
        result.rightResult.requestedWheelTravel_m ~= ...
        result.requestedWheelTravel_m(2) || ...
        result.leftConverged ~= result.leftResult.converged || ...
        result.rightConverged ~= result.rightResult.converged || ...
        result.converged ~= expectedConverged
    invalid("AxleTravelResult contradicts its corner results.");
end
if ~isstruct(result.diagnostics) || ~isscalar(result.diagnostics) || ...
        ~all(isfield(result.diagnostics, ...
        ["left", "right", "bilateralConverged"])) || ...
        ~isequal(result.diagnostics.left, result.leftResult.diagnostics) || ...
        ~isequal(result.diagnostics.right, result.rightResult.diagnostics) || ...
        result.diagnostics.bilateralConverged ~= expectedConverged
    invalid("AxleTravelResult diagnostics contradict corner diagnostics.");
end
if expectedConverged
    if string(result.status) ~= "CONVERGED" || ...
            strlength(string(result.failureReason)) ~= 0
        invalid("Converged axle travel aggregates are inconsistent.");
    end
else
    if ~ismember(string(result.status), ...
            ["NO_CONVERGENCE", "NOT_ATTEMPTED"]) || ...
            strlength(string(result.failureReason)) == 0
        invalid("Failed axle travel aggregates are inconsistent.");
    end
end
isValid = true;
end

function invalid(message)
error("fsd:kinematics:InvalidAxleTravelResult", message);
end
