function isValid = validateRackSweepResult(sweep, steering)
%VALIDATERACKSWEEPRESULT Validate an ordered v0.5 rack sweep.

fsd.model.validateSteeringSystemGeometry(steering);
required = ["schemaVersion", "kind", "steeringSystemIdentity", ...
    "requestedRackTravel_m", "requestedWheelTravel_m", "converged", ...
    "status", "allConverged", "elapsedTime_s", "results"];
if ~isstruct(sweep) || ~isscalar(sweep) || ~all(isfield(sweep, required)) || ...
        string(sweep.schemaVersion) ~= "0.5.0" || ...
        string(sweep.kind) ~= "RackSweepResult" || ...
        ~isequal(sweep.steeringSystemIdentity, steering.identity) || ...
        ~isnumeric(sweep.requestedRackTravel_m) || ...
        ~iscolumn(sweep.requestedRackTravel_m) || ...
        any(~isfinite(sweep.requestedRackTravel_m)) || ...
        isempty(sweep.requestedRackTravel_m) || ...
        ~isequal(size(sweep.requestedWheelTravel_m), [1, 2]) || ...
        numel(sweep.results) ~= numel(sweep.requestedRackTravel_m)
    invalid("RackSweepResult has an invalid aggregate contract.");
end
for index = 1:numel(sweep.results)
    fsd.kinematics.validateSteeringResult(sweep.results(index), steering);
    if sweep.results(index).requestedRackTravel_m ~= ...
            sweep.requestedRackTravel_m(index)
        invalid("A contained steering target does not match the sweep.");
    end
end
expectedConverged = reshape([sweep.results.converged], [], 1);
expectedStatus = reshape(string({sweep.results.status}), [], 1);
if ~isequal(sweep.converged, expectedConverged) || ...
        ~isequal(string(sweep.status), expectedStatus) || ...
        sweep.allConverged ~= all(expectedConverged)
    invalid("Rack sweep aggregate fields contradict contained results.");
end
isValid = true;
end

function invalid(message)
error("fsd:kinematics:InvalidRackSweepResult", message);
end
