function isValid = validateActuationResult(result, actuation)
%VALIDATEACTUATIONRESULT Validate identity, source and physical payload.

if nargin < 2
    actuation = [];
end
if ~isstruct(result) || ~isscalar(result)
    invalid("ActuationResult must be a scalar struct.");
end
required = ["schemaVersion", "kind", "actuationIdentity", ...
    "cornerId", "actuationType", "attachmentBody", ...
    "sourceResultKind", "sourceResult", "sourceGeometryIdentity", ...
    "sourceRequestedWheelTravel_m", "sourceAchievedWheelTravel_m", ...
    "sourceKinematicStatus", "sourceKinematicFailureReason", ...
    "converged", "status", "failureReason", ...
    "suspensionAttachmentCurrent_m", "rockerRodPointCurrent_m", ...
    "rockerDamperPointCurrent_m", "rockerAngle_rad", ...
    "rockerAngleWrapped_rad", "damperLength_m", ...
    "damperCompression_m", "actuationRodLength_m", ...
    "actuationRodLengthResidual_m", "conditioning", ...
    "isIllConditioned", "diagnostics"];
if any(~isfield(result, required)) || ...
        string(result.schemaVersion) ~= "0.7.0" || ...
        string(result.kind) ~= "ActuationResult"
    invalid("Unsupported or incomplete ActuationResult schema.");
end
try
    fsd.model.validateActuationIdentity(result.actuationIdentity);
    validateActuationSource(result.sourceResult);
catch cause
    exception = MException("fsd:kinematics:InvalidActuationResult", ...
        "ActuationResult contains an invalid identity or source.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
if ~isempty(actuation)
    try
        fsd.model.validateActuationGeometry(actuation);
    catch cause
        exception = MException("fsd:kinematics:InvalidActuationResult", ...
            "Supplied ActuationGeometry is invalid.");
        exception = addCause(exception, cause);
        throwAsCaller(exception);
    end
    if ~isequal(result.actuationIdentity, actuation.identity)
        error("fsd:kinematics:ActuationIdentityMismatch", ...
            "ActuationResult belongs to another ActuationGeometry.");
    end
else
    actuation = geometryFromIdentity(result.actuationIdentity);
end

source = result.sourceResult;
if ~isequal(result.sourceGeometryIdentity, source.geometryIdentity) || ...
        ~isequal(result.sourceGeometryIdentity, ...
        result.actuationIdentity.cornerGeometryIdentity) || ...
        string(result.cornerId) ~= string(result.actuationIdentity.cornerId) || ...
        string(result.actuationType) ~= ...
        string(result.actuationIdentity.actuationType) || ...
        string(result.attachmentBody) ~= ...
        string(result.actuationIdentity.suspensionAttachmentBody) || ...
        string(result.sourceResultKind) ~= string(source.kind) || ...
        result.sourceRequestedWheelTravel_m ~= ...
        source.requestedWheelTravel_m || ...
        ~isequaln(result.sourceAchievedWheelTravel_m, ...
        source.achievedWheelTravel_m) || ...
        string(result.sourceKinematicStatus) ~= string(source.status) || ...
        string(result.sourceKinematicFailureReason) ~= ...
        string(source.failureReason)
    invalid("ActuationResult source or identity fields are inconsistent.");
end
if ~islogical(result.converged) || ~isscalar(result.converged) || ...
        ~islogical(result.isIllConditioned) || ...
        ~isscalar(result.isIllConditioned) || ...
        ~isstruct(result.diagnostics) || ~isscalar(result.diagnostics)
    invalid("ActuationResult flags or diagnostics are invalid.");
end
validateDiagnosticsShape(result.diagnostics);
if result.converged
    validateConverged(result, actuation);
else
    validateFailed(result);
end
isValid = true;
end

function validateConverged(result, actuation)
if string(result.status) ~= "CONVERGED" || ...
        strlength(string(result.failureReason)) ~= 0 || ...
        ~result.sourceResult.converged
    invalid("A converged actuation result has inconsistent status.");
end
pointFields = ["suspensionAttachmentCurrent_m", ...
    "rockerRodPointCurrent_m", "rockerDamperPointCurrent_m"];
for index = 1:numel(pointFields)
    if ~isPoint(result.(pointFields(index)), true)
        invalid("A converged actuation result requires finite points.");
    end
end
scalarFields = ["rockerAngle_rad", "rockerAngleWrapped_rad", ...
    "damperLength_m", "damperCompression_m", ...
    "actuationRodLength_m", "actuationRodLengthResidual_m", ...
    "conditioning"];
for index = 1:numel(scalarFields)
    if ~isFiniteScalar(result.(scalarFields(index)))
        invalid("A converged actuation result requires finite scalars.");
    end
end

tolerance_m = comparisonTolerance([ ...
    result.actuationIdentity.suspensionAttachmentPointStatic_m, ...
    result.actuationIdentity.rockerRodPointStatic_m, ...
    result.actuationIdentity.rockerDamperPointStatic_m]);
[expectedAttachment_m, ~] = actuationAttachmentCurrent( ...
    actuation, result.sourceResult);
expectedRockerPoints_m = fsd.geometry.rotatePointsAboutAxis( ...
    [actuation.rocker.actuationRodPoint.pointStatic_m; ...
    actuation.rocker.damperPoint.pointStatic_m], ...
    actuation.rocker.axis.point_m, ...
    actuation.rocker.axis.direction_unit, result.rockerAngle_rad);
expectedRodLength_m = norm(expectedRockerPoints_m(1,:) - ...
    expectedAttachment_m, 2);
expectedDamperLength_m = norm(expectedRockerPoints_m(2,:) - ...
    actuation.damper.chassisPoint.point_m, 2);
expectedCompression_m = actuation.damper.staticLength_m - ...
    expectedDamperLength_m;
expectedResidual_m = expectedRodLength_m - ...
    actuation.actuationRod.staticLength_m;
if max(abs(expectedAttachment_m - ...
        result.suspensionAttachmentCurrent_m)) > tolerance_m || ...
        max(abs(expectedRockerPoints_m(1,:) - ...
        result.rockerRodPointCurrent_m)) > tolerance_m || ...
        max(abs(expectedRockerPoints_m(2,:) - ...
        result.rockerDamperPointCurrent_m)) > tolerance_m || ...
        abs(expectedRodLength_m-result.actuationRodLength_m) > tolerance_m || ...
        abs(expectedDamperLength_m-result.damperLength_m) > tolerance_m || ...
        abs(expectedCompression_m-result.damperCompression_m) > tolerance_m || ...
        abs(expectedResidual_m-result.actuationRodLengthResidual_m) > ...
        tolerance_m || abs(result.actuationRodLengthResidual_m) > ...
        10*tolerance_m || ...
        abs(fsd.geometry.wrapAngle(result.rockerAngle_rad) - ...
        result.rockerAngleWrapped_rad) > 10*eps
    invalid("ActuationResult contradicts rigid geometry or rod closure.");
end

axisPoint_m = actuation.rocker.axis.point_m;
axisDirection = actuation.rocker.axis.direction_unit;
rodStatic_m = actuation.rocker.actuationRodPoint.pointStatic_m;
offset_m = rodStatic_m-axisPoint_m;
circleCenter_m = axisPoint_m + dot(axisDirection,offset_m)*axisDirection;
radial_m = rodStatic_m-circleCenter_m;
tangent_m = cross(axisDirection,radial_m);
w_m = circleCenter_m-expectedAttachment_m;
expectedCoefficients = [2*dot(w_m,radial_m), ...
    2*dot(w_m,tangent_m), ...
    actuation.actuationRod.staticLength_m^2-dot(w_m,w_m)-dot(radial_m,radial_m)];
actualCoefficients = [result.diagnostics.constraintA_m2, ...
    result.diagnostics.constraintB_m2, result.diagnostics.constraintD_m2];
coefficientTolerance_m2 = 100*eps(max([abs(expectedCoefficients),1]));
if max(abs(expectedCoefficients-actualCoefficients)) > ...
        coefficientTolerance_m2 || ...
        abs(hypot(expectedCoefficients(1),expectedCoefficients(2)) - ...
        result.diagnostics.constraintR_m2) > coefficientTolerance_m2 || ...
        max(abs(circleCenter_m-result.diagnostics.rockerCircleCenter_m)) > ...
        tolerance_m || abs(norm(radial_m)- ...
        result.diagnostics.rockerCircleRadius_m) > tolerance_m
    invalid("ActuationResult closure diagnostics contradict the geometry.");
end

coefficientScale_m2 = max([abs(expectedCoefficients), ...
    actuation.actuationRod.staticLength_m^2, dot(w_m,w_m), ...
    dot(radial_m,radial_m), 1]);
referenceAngle_rad = result.diagnostics.referenceRockerAngle_rad;
if ~isFiniteScalar(referenceAngle_rad)
    invalid("ActuationResult reference angle is invalid.");
end
closure = rockerClosureSolution(expectedCoefficients(1), ...
    expectedCoefficients(2), expectedCoefficients(3), ...
    coefficientScale_m2, referenceAngle_rad);
angleTolerance_rad = 100*eps(max([abs(closure.candidateAngles_rad), ...
    abs(result.rockerAngle_rad), 1]));
if closure.constraintCase ~= string(result.diagnostics.constraintCase) || ...
        ~isequal(size(closure.candidateAngles_rad), ...
        size(result.diagnostics.candidateAngles_rad)) || ...
        any(abs(closure.candidateAngles_rad - ...
        result.diagnostics.candidateAngles_rad) > angleTolerance_rad) || ...
        closure.selectedCandidateIndex ~= ...
        result.diagnostics.selectedCandidateIndex || ...
        abs(closure.selectedAngle_rad-result.rockerAngle_rad) > ...
        angleTolerance_rad || ...
        abs(closure.acosRatio-result.diagnostics.acosRatio) > ...
        100*eps || ...
        abs(closure.alpha_rad-result.diagnostics.alpha_rad) > ...
        angleTolerance_rad || ...
        closure.coefficientTolerance_m2 ~= ...
        result.diagnostics.coefficientTolerance_m2 || ...
        abs(closure.derivativeMagnitude_m2 - ...
        result.diagnostics.derivativeMagnitude_m2) > ...
        coefficientTolerance_m2 || ...
        abs(closure.conditioning-result.conditioning) > ...
        100*eps(max(1,abs(closure.conditioning))) || ...
        result.isIllConditioned ~= closure.isIllConditioned || ...
        ~result.diagnostics.attempted
    invalid("ActuationResult branch reconstruction is inconsistent.");
end
end

function validateFailed(result)
allowed = ["KINEMATICS_NOT_CONVERGED", "NO_ROCKER_SOLUTION", ...
    "ROCKER_AXIS_DEGENERATE", "ROCKER_LEVER_ARM_DEGENERATE", ...
    "ROCKER_UNDERCONSTRAINED", "ROCKER_SINGULAR", ...
    "INVALID_ATTACHMENT_BODY", "NOT_ATTEMPTED"];
if ~ismember(string(result.status), allowed) || ...
        strlength(string(result.failureReason)) == 0
    invalid("A failed actuation result has an invalid status.");
end
pointFields = ["suspensionAttachmentCurrent_m", ...
    "rockerRodPointCurrent_m", "rockerDamperPointCurrent_m"];
for index = 1:numel(pointFields)
    if ~all(isnan(result.(pointFields(index))))
        invalid("A failed result must not publish derived points.");
    end
end
scalarFields = ["rockerAngle_rad", ...
    "rockerAngleWrapped_rad", "damperLength_m", ...
    "damperCompression_m", "actuationRodLength_m", ...
    "actuationRodLengthResidual_m", "conditioning"];
for index = 1:numel(scalarFields)
    if ~isnan(result.(scalarFields(index)))
        invalid("A failed result must use NaN derived scalars.");
    end
end
if result.status == "KINEMATICS_NOT_CONVERGED" && ...
        result.sourceResult.converged
    invalid("KINEMATICS_NOT_CONVERGED requires a failed source.");
elseif result.status ~= "KINEMATICS_NOT_CONVERGED" && ...
        result.status ~= "NOT_ATTEMPTED" && ~result.sourceResult.converged
    invalid("Actuation failure status contradicts the source state.");
end
if ismember(string(result.status), ...
        ["KINEMATICS_NOT_CONVERGED", "NOT_ATTEMPTED"]) && ...
        result.diagnostics.attempted
    invalid("Unattempted actuation status reports solver activity.");
elseif ~ismember(string(result.status), ...
        ["KINEMATICS_NOT_CONVERGED", "NOT_ATTEMPTED"]) && ...
        ~result.diagnostics.attempted
    invalid("Attempted actuation failure lacks attempted diagnostics.");
end
if string(result.status) == "NOT_ATTEMPTED"
    diagnosticScalars = [result.diagnostics.referenceRockerAngle_rad, ...
        result.diagnostics.selectedCandidateIndex, ...
        result.diagnostics.acosRatio, result.diagnostics.alpha_rad, ...
        result.diagnostics.coefficientTolerance_m2, ...
        result.diagnostics.derivativeMagnitude_m2, ...
        result.diagnostics.rockerCircleRadius_m, ...
        result.diagnostics.constraintA_m2, ...
        result.diagnostics.constraintB_m2, ...
        result.diagnostics.constraintD_m2, ...
        result.diagnostics.constraintR_m2];
    if string(result.diagnostics.constraintCase) ~= "NOT_ATTEMPTED" || ...
            ~isempty(result.diagnostics.candidateAngles_rad) || ...
            ~all(isnan(diagnosticScalars)) || ...
            ~all(isnan(result.diagnostics.rockerCircleCenter_m)) || ...
            ~isempty(fieldnames(result.diagnostics.attachmentTransform))
        invalid("NOT_ATTEMPTED must not carry solver state forward.");
    end
end
end

function validateDiagnosticsShape(value)
required = ["solver", "attempted", "sourceKinematicStatus", ...
    "sourceKinematicFailureReason", "constraintCase", ...
    "referenceRockerAngle_rad", "candidateAngles_rad", ...
    "selectedCandidateIndex", "acosRatio", ...
    "alpha_rad", "coefficientTolerance_m2", ...
    "derivativeMagnitude_m2", "attachmentTransform", ...
    "rockerCircleCenter_m", "rockerCircleRadius_m", ...
    "constraintA_m2", "constraintB_m2", "constraintD_m2", ...
    "constraintR_m2"];
if any(~isfield(value, required)) || ...
        ~islogical(value.attempted) || ~isscalar(value.attempted) || ...
        string(value.solver) ~= "CLOSED_FORM_CIRCLE_SPHERE"
    invalid("Actuation diagnostics have an invalid schema.");
end
end

function actuation = geometryFromIdentity(identity)
actuation = struct( ...
    "schemaVersion", identity.actuationSchemaVersion, ...
    "kind", "ActuationGeometry", ...
    "cornerId", identity.cornerId, ...
    "cornerGeometryIdentity", identity.cornerGeometryIdentity, ...
    "actuationType", identity.actuationType, ...
    "suspensionAttachment", struct( ...
        "id", "ACTUATION_ROD_SUSPENSION", ...
        "body", identity.suspensionAttachmentBody, ...
        "pointStatic_m", identity.suspensionAttachmentPointStatic_m), ...
    "rocker", struct( ...
        "orientationMode", inferredOrientationMode( ...
            identity.rockerAxisDirection_unit), ...
        "axis", struct("point_m", identity.rockerAxisPoint_m, ...
            "direction_unit", identity.rockerAxisDirection_unit, ...
            "pointConvention", "CLOSEST_TO_VEHICLE_ORIGIN"), ...
        "actuationRodPoint", struct("id", "ACTUATION_ROD_ROCKER", ...
            "pointStatic_m", identity.rockerRodPointStatic_m), ...
        "damperPoint", struct("id", "DAMPER_ROCKER", ...
            "pointStatic_m", identity.rockerDamperPointStatic_m)), ...
    "damper", struct("chassisPoint", struct("id", "DAMPER_CHASSIS", ...
        "point_m", identity.damperChassisPoint_m), ...
        "staticLength_m", norm(identity.rockerDamperPointStatic_m - ...
        identity.damperChassisPoint_m)), ...
    "actuationRod", struct("staticLength_m", norm( ...
        identity.suspensionAttachmentPointStatic_m - ...
        identity.rockerRodPointStatic_m)), ...
    "metadata", struct("lengthUnit", "m", ...
        "coordinateSystem", "X_REAR_Y_RIGHT_Z_UP"), ...
    "identity", identity);
end

function mode = inferredOrientationMode(axisDirection)
if isequal(axisDirection, [1,0,0])
    mode = "YZ_PLANE";
elseif isequal(axisDirection, [0,1,0])
    mode = "XZ_PLANE";
else
    mode = "CUSTOM";
end
end

function value = comparisonTolerance(reference)
tolerances = fsd.model.numericTolerances();
value = 10 * (tolerances.AbsTol_m + ...
    tolerances.RelTol * max([abs(reference(:)); 1]));
end

function tf = isPoint(value, requireFinite)
tf = isnumeric(value) && isreal(value) && isequal(size(value), [1, 3]);
if tf && requireFinite
    tf = all(isfinite(value));
end
end

function tf = isFiniteScalar(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && isfinite(value);
end

function invalid(message, varargin)
error("fsd:kinematics:InvalidActuationResult", message, varargin{:});
end
