function isValid = validateSteeringResult(result, steering)
%VALIDATESTEERINGRESULT Validate a v0.5 bilateral steering result.

fsd.model.validateSteeringSystemGeometry(steering);
if ~isstruct(result) || ~isscalar(result)
    invalid("SteeringAxleResult must be a scalar struct.");
end
required = ["schemaVersion", "kind", "steeringSystemIdentity", ...
    "requestedRackTravel_m", "achievedRackTravel_m", ...
    "requestedWheelTravel_m", "leftResult", "rightResult", ...
    "leftConverged", "rightConverged", "converged", "status", ...
    "failureReason", "diagnostics", "elapsedTime_s"];
if ~all(isfield(result, required)) || ...
        string(result.schemaVersion) ~= "0.5.0" || ...
        string(result.kind) ~= "SteeringAxleResult" || ...
        ~isequal(result.steeringSystemIdentity, steering.identity) || ...
        ~isFiniteScalar(result.requestedRackTravel_m) || ...
        ~isnumeric(result.requestedWheelTravel_m) || ...
        ~isreal(result.requestedWheelTravel_m) || ...
        ~isequal(size(result.requestedWheelTravel_m), [1, 2]) || ...
        any(~isfinite(result.requestedWheelTravel_m)) || ...
        ~islogical(result.converged) || ~isscalar(result.converged) || ...
        ~islogical(result.leftConverged) || ...
        ~isscalar(result.leftConverged) || ...
        ~islogical(result.rightConverged) || ...
        ~isscalar(result.rightConverged) || ...
        ~isstruct(result.diagnostics) || ~isscalar(result.diagnostics) || ...
        ~all(isfield(result.diagnostics, ...
        ["left", "right", "bilateralConverged"])) || ...
        ~isFiniteScalar(result.elapsedTime_s) || result.elapsedTime_s < 0
    invalid("SteeringAxleResult fields have invalid values.");
end
validateCorner(result.leftResult, steering, "LEFT", ...
    result.requestedRackTravel_m, result.requestedWheelTravel_m(1));
validateCorner(result.rightResult, steering, "RIGHT", ...
    result.requestedRackTravel_m, result.requestedWheelTravel_m(2));
expectedConverged = result.leftResult.converged && ...
    result.rightResult.converged;
if result.leftConverged ~= result.leftResult.converged || ...
        result.rightConverged ~= result.rightResult.converged || ...
        result.converged ~= expectedConverged || ...
        ~isequal(result.diagnostics.left, result.leftResult.diagnostics) || ...
        ~isequal(result.diagnostics.right, result.rightResult.diagnostics) || ...
        ~islogical(result.diagnostics.bilateralConverged) || ...
        ~isscalar(result.diagnostics.bilateralConverged) || ...
        result.diagnostics.bilateralConverged ~= expectedConverged
    invalid("Bilateral convergence fields contradict corner results.");
end
if result.converged
    if string(result.status) ~= "CONVERGED" || ...
            result.achievedRackTravel_m ~= result.requestedRackTravel_m || ...
            strlength(string(result.failureReason)) ~= 0
        invalid("A converged steering result has inconsistent aggregates.");
    end
else
    if ~ismember(string(result.status), ...
            ["NO_CONVERGENCE", "NOT_ATTEMPTED"]) || ...
            ~isnan(result.achievedRackTravel_m) || ...
            strlength(string(result.failureReason)) == 0
        invalid("A failed steering result has inconsistent aggregates.");
    end
end
isValid = true;
end

function validateCorner(value, steering, side, rackTravel_m, wheelTravel_m)
required = ["schemaVersion", "kind", "geometryIdentity", "cornerId", ...
    "requestedWheelTravel_m", "achievedWheelTravel_m", ...
    "requestedRackTravel_m", "achievedRackTravel_m", ...
    "tieRodInboardStatic_m", "tieRodInboardCurrent_m", "state", ...
    "uprightPose", "wheelAxis", "camber_rad", "geometricContact", ...
    "rackZeroKinematicResult", "converged", "status", ...
    "failureReason", "diagnostics"];
if ~isstruct(value) || ~isscalar(value) || ~all(isfield(value, required)) || ...
        string(value.schemaVersion) ~= "0.5.0" || ...
        string(value.kind) ~= "SteeringCornerResult"
    invalid("A steering corner result has an invalid schema.");
end
if side == "LEFT"
    geometry = steering.frontAxleGeometry.leftGeometry;
    staticInner_m = steering.rackGeometry.leftInnerStatic_m;
    expectedCorner = "FL";
else
    geometry = steering.frontAxleGeometry.rightGeometry;
    staticInner_m = steering.rackGeometry.rightInnerStatic_m;
    expectedCorner = "FR";
end
expectedCurrent_m = staticInner_m + ...
    rackTravel_m * steering.rackGeometry.axisDirection;
tolerance = comparisonTolerance(geometry.hardpoints.xyz_m);
if string(value.cornerId) ~= expectedCorner || ...
        ~isequal(value.geometryIdentity, fsd.model.geometryIdentity(geometry)) || ...
        abs(value.requestedWheelTravel_m - wheelTravel_m) > tolerance || ...
        abs(value.requestedRackTravel_m - rackTravel_m) > tolerance || ...
        max(abs(value.tieRodInboardStatic_m - staticInner_m)) > tolerance || ...
        max(abs(value.tieRodInboardCurrent_m - expectedCurrent_m)) > tolerance
    invalid("A steering corner result does not belong to this system target.");
end
try
    fsd.kinematics.validateKinematicResult(value.rackZeroKinematicResult);
catch cause
    exception = MException("fsd:kinematics:InvalidSteeringResult", ...
        "rackZeroKinematicResult violates the v0.3 contract.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
if ~isequal(value.rackZeroKinematicResult.geometryIdentity, ...
        value.geometryIdentity) || ...
        abs(value.rackZeroKinematicResult.requestedWheelTravel_m - ...
        wheelTravel_m) > tolerance
    invalid("The rack-zero reference does not match the steering target.");
end
if value.converged
    if string(value.status) ~= "CONVERGED" || ...
            ~value.rackZeroKinematicResult.converged || ...
            abs(value.achievedRackTravel_m - rackTravel_m) > tolerance || ...
            abs(value.achievedWheelTravel_m - wheelTravel_m) > tolerance || ...
            any(~isfinite(value.wheelAxis)) || ~isfinite(value.camber_rad) || ...
            string(value.geometricContact.status) ~= "FINITE"
        invalid("A converged steering corner contains invalid output.");
    end
    fsd.kinematics.validateSuspensionState( ...
        value.state, value.geometryIdentity, "FINITE");
    validatePoseAndConstraints(value, geometry, expectedCurrent_m, tolerance);
else
    if ~ismember(string(value.status), ...
            ["NO_CONVERGENCE", "NOT_ATTEMPTED"]) || ...
            ~isnan(value.achievedRackTravel_m) || ...
            ~isnan(value.achievedWheelTravel_m) || ...
            ~all(isnan(value.wheelAxis)) || ~isnan(value.camber_rad) || ...
            ~all(isnan(value.geometricContact.point_m))
        invalid("A failed steering corner must not publish finite outputs.");
    end
    fsd.kinematics.validateSuspensionState( ...
        value.state, value.geometryIdentity, "NAN");
    validateFailedPose(value.uprightPose, geometry, tolerance);
end
end

function validatePoseAndConstraints(value, geometry, tieInboard_m, tolerance)
pose = value.uprightPose;
staticIds = string(geometry.cornerId) + "_" + ...
    ["UBJ"; "LBJ"; "TIE_ROD_OUTBOARD"; "WHEEL_CENTER"; "CONTACT_PATCH"];
staticPoints_m = points(geometry, staticIds);
wheelCenterStatic_m = staticPoints_m(4, :);
validatePoseShape(pose, wheelCenterStatic_m, tolerance);
expectedRotation = fsd.geometry.rotationVectorToMatrix( ...
    pose.rotationVector_rad);
if max(abs(expectedRotation - pose.rotationMatrix), [], "all") > tolerance
    invalid("Steering pose rotation vector and matrix disagree.");
end
expectedPoints_m = fsd.geometry.transformPointsRigid(staticPoints_m, ...
    wheelCenterStatic_m, pose.translation_m, pose.rotationMatrix);
expectedAxis = (pose.rotationMatrix * geometry.wheel.wheelAxis(:))';
expectedAxis = expectedAxis ./ norm(expectedAxis, 2);
expectedContact = fsd.geometry.geometricWheelContact( ...
    value.state.wheelCenter_m, value.wheelAxis, ...
    value.geometricContact.geometricRadius_m);
if max(abs(expectedPoints_m - value.state.xyz_m), [], "all") > tolerance || ...
        max(abs(expectedAxis - value.wheelAxis)) > tolerance || ...
        max(abs(value.state.wheelAxis - value.wheelAxis)) > tolerance || ...
        string(expectedContact.status) ~= "FINITE" || ...
        max(abs(expectedContact.point_m - ...
        value.geometricContact.point_m)) > tolerance
    invalid("Steering state contradicts its upright pose.");
end
prefix = string(geometry.cornerId) + "_";
fixedIds = prefix + ["UCA_FWD_CHASSIS"; "UCA_AFT_CHASSIS"; ...
    "LCA_FWD_CHASSIS"; "LCA_AFT_CHASSIS"];
fixed_m = points(geometry, fixedIds);
staticMoving = [staticPoints_m(1,:); staticPoints_m(1,:); ...
    staticPoints_m(2,:); staticPoints_m(2,:)];
currentMoving = [value.state.ubj_m; value.state.ubj_m; ...
    value.state.lbj_m; value.state.lbj_m];
staticLengths = sqrt(sum((staticMoving - fixed_m).^2, 2));
currentLengths = sqrt(sum((currentMoving - fixed_m).^2, 2));
staticTieIn = fsd.model.getPoint(geometry, prefix + "TIE_ROD_INBOARD");
staticTieOut = staticPoints_m(3, :);
if any(abs(currentLengths - staticLengths) > tolerance) || ...
        abs(norm(value.state.tieRodOutboard_m - tieInboard_m) - ...
        norm(staticTieOut - staticTieIn)) > tolerance
    invalid("Steering state violates a rigid link constraint.");
end
end

function validateFailedPose(pose, geometry, tolerance)
wheelCenterStatic_m = fsd.model.getPoint(geometry, ...
    string(geometry.cornerId) + "_WHEEL_CENTER");
validatePoseShape(pose, wheelCenterStatic_m, tolerance);
if ~all(isnan(pose.translation_m)) || ...
        ~all(isnan(pose.rotationVector_rad)) || ...
        ~all(isnan(pose.rotationMatrix), "all")
    invalid("A failed steering pose must use NaN moving fields.");
end
end

function validatePoseShape(pose, wheelCenterStatic_m, tolerance)
required = ["referencePointStatic_m", "translation_m", ...
    "rotationVector_rad", "rotationMatrix"];
if ~isstruct(pose) || ~isscalar(pose) || ~all(isfield(pose, required)) || ...
        ~isRealNumericSize(pose.referencePointStatic_m, [1, 3]) || ...
        ~isRealNumericSize(pose.translation_m, [1, 3]) || ...
        ~isRealNumericSize(pose.rotationVector_rad, [1, 3]) || ...
        ~isRealNumericSize(pose.rotationMatrix, [3, 3]) || ...
        any(~isfinite(pose.referencePointStatic_m)) || ...
        max(abs(pose.referencePointStatic_m - wheelCenterStatic_m)) > tolerance
    invalid("Steering upright pose has an invalid contract.");
end
end

function output = points(geometry, ids)
output = zeros(numel(ids), 3);
for index = 1:numel(ids)
    output(index,:) = fsd.model.getPoint(geometry, ids(index));
end
end

function value = comparisonTolerance(reference)
tolerances = fsd.model.numericTolerances();
value = 10 * (tolerances.AbsTol_m + ...
    tolerances.RelTol * max([abs(reference(:)); 1]));
end

function tf = isFiniteScalar(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && isfinite(value);
end

function tf = isRealNumericSize(value, expectedSize)
tf = isnumeric(value) && isreal(value) && isequal(size(value), expectedSize);
end

function invalid(message)
error("fsd:kinematics:InvalidSteeringResult", message);
end
