function isValid = validateAxleHeaveSweepResult(sweep)
%VALIDATEAXLEHEAVESWEEPRESULT Validate a composed axle heave sweep.

if ~isstruct(sweep) || ~isscalar(sweep)
    invalid("AxleHeaveSweepResult must be a scalar struct.");
end
required = ["schemaVersion", "kind", "axleIdentity", ...
    "requestedWheelTravel_m", "converged", "leftConverged", ...
    "rightConverged", "status", "allConverged", "elapsedTime_s", ...
    "leftSweep", "rightSweep", "results"];
for index = 1:numel(required)
    if ~isfield(sweep, required(index))
        invalid("AxleHeaveSweepResult is missing field '%s'.", ...
            required(index));
    end
end
if ~isTextScalar(sweep.schemaVersion) || ...
        string(sweep.schemaVersion) ~= "0.4.0" || ...
        ~isTextScalar(sweep.kind) || ...
        string(sweep.kind) ~= "AxleHeaveSweepResult"
    invalid("Unsupported or invalid AxleHeaveSweepResult schema.");
end
try
    fsd.model.validateAxleIdentity(sweep.axleIdentity);
    fsd.kinematics.validateBumpSweepResult(sweep.leftSweep);
    fsd.kinematics.validateBumpSweepResult(sweep.rightSweep);
catch cause
    exception = MException("fsd:kinematics:InvalidAxleHeaveSweepResult", ...
        "Axle sweep contains an invalid identity or corner sweep.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
count = numel(sweep.requestedWheelTravel_m);
if ~isnumeric(sweep.requestedWheelTravel_m) || ...
        ~isreal(sweep.requestedWheelTravel_m) || ...
        ~iscolumn(sweep.requestedWheelTravel_m) || count == 0 || ...
        any(~isfinite(sweep.requestedWheelTravel_m)) || ...
        ~islogical(sweep.converged) || ...
        ~isequal(size(sweep.converged), [count, 1]) || ...
        ~islogical(sweep.leftConverged) || ...
        ~isequal(size(sweep.leftConverged), [count, 1]) || ...
        ~islogical(sweep.rightConverged) || ...
        ~isequal(size(sweep.rightConverged), [count, 1]) || ...
        ~isstring(sweep.status) || ...
        ~isequal(size(sweep.status), [count, 1]) || ...
        ~islogical(sweep.allConverged) || ~isscalar(sweep.allConverged) || ...
        ~isnumeric(sweep.elapsedTime_s) || ~isreal(sweep.elapsedTime_s) || ...
        ~isscalar(sweep.elapsedTime_s) || ~isfinite(sweep.elapsedTime_s) || ...
        sweep.elapsedTime_s < 0 || ~isstruct(sweep.results) || ...
        ~iscolumn(sweep.results) || numel(sweep.results) ~= count
    invalid("AxleHeaveSweepResult fields have invalid types or dimensions.");
end
if ~isequal(sweep.leftSweep.geometryIdentity, ...
        sweep.axleIdentity.leftGeometryIdentity) || ...
        ~isequal(sweep.rightSweep.geometryIdentity, ...
        sweep.axleIdentity.rightGeometryIdentity) || ...
        ~isequal(sweep.requestedWheelTravel_m, ...
        sweep.leftSweep.requestedWheelTravel_m) || ...
        ~isequal(sweep.requestedWheelTravel_m, ...
        sweep.rightSweep.requestedWheelTravel_m)
    invalid("Corner sweeps do not belong to the declared axle sweep.");
end
for index = 1:count
    try
        fsd.kinematics.validateAxleKinematicResult(sweep.results(index));
    catch cause
        exception = MException( ...
            "fsd:kinematics:InvalidAxleHeaveSweepResult", ...
            "Axle sweep contains invalid result %d.", index);
        exception = addCause(exception, cause);
        throwAsCaller(exception);
    end
    if ~isequal(sweep.results(index).axleIdentity, sweep.axleIdentity)
        invalid("Result %d belongs to a different axle identity.", index);
    end
end
resultRequested = reshape([sweep.results.requestedWheelTravel_m], [], 1);
resultConverged = reshape([sweep.results.converged], [], 1);
resultLeft = reshape([sweep.results.leftConverged], [], 1);
resultRight = reshape([sweep.results.rightConverged], [], 1);
resultStatus = reshape(string({sweep.results.status}), [], 1);
if ~isequal(sweep.requestedWheelTravel_m, resultRequested) || ...
        ~isequal(sweep.converged, resultConverged) || ...
        ~isequal(sweep.leftConverged, resultLeft) || ...
        ~isequal(sweep.rightConverged, resultRight) || ...
        ~isequal(sweep.status, resultStatus) || ...
        sweep.allConverged ~= all(resultConverged)
    invalid("Axle sweep aggregate fields contradict contained results.");
end
isValid = true;
end

function tf = isTextScalar(value)
tf = (ischar(value) && isrow(value)) || ...
    (isstring(value) && isscalar(value) && ~ismissing(value));
end

function invalid(message, varargin)
error("fsd:kinematics:InvalidAxleHeaveSweepResult", ...
    message, varargin{:});
end
