function isValid = validateSteeringCornerResult(value)
%VALIDATESTEERINGCORNERRESULT Validate a standalone v0.5 steering corner.

if ~isstruct(value) || ~isscalar(value)
    invalid("SteeringCornerResult must be a scalar struct.");
end
required = ["schemaVersion", "kind", "steeringSystemIdentity", ...
    "geometryIdentity", "cornerId", "requestedWheelTravel_m", ...
    "achievedWheelTravel_m", "requestedRackTravel_m", ...
    "achievedRackTravel_m", "tieRodInboardStatic_m", ...
    "tieRodInboardCurrent_m", "state", "uprightPose", "wheelAxis", ...
    "camber_rad", "geometricContact", "rackZeroKinematicResult", ...
    "converged", "status", "failureReason", "diagnostics"];
if any(~isfield(value, required)) || ...
        string(value.schemaVersion) ~= "0.5.0" || ...
        string(value.kind) ~= "SteeringCornerResult"
    invalid("Unsupported or incomplete SteeringCornerResult schema.");
end
if ~islogical(value.converged) || ~isscalar(value.converged)
    invalid("Steering corner convergence flag must be logical scalar.");
end
try
    fsd.model.validateSteeringSystemIdentity(value.steeringSystemIdentity);
    fsd.model.validateGeometryIdentity(value.geometryIdentity);
catch cause
    exception = MException("fsd:kinematics:InvalidSteeringCornerResult", ...
        "Steering corner contains an invalid identity.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end

[expectedIdentity, staticInner_m] = identityForCorner( ...
    value.steeringSystemIdentity, string(value.cornerId));
tolerance_m = comparisonTolerance(expectedIdentity.hardpointXyz_m);
if ~isequal(value.geometryIdentity, expectedIdentity) || ...
        ~isFiniteScalar(value.requestedWheelTravel_m) || ...
        ~isFiniteScalar(value.requestedRackTravel_m) || ...
        ~isFinitePoint(value.tieRodInboardStatic_m) || ...
        ~isFinitePoint(value.tieRodInboardCurrent_m) || ...
        max(abs(value.tieRodInboardStatic_m-staticInner_m)) > tolerance_m
    invalid("Steering corner identity or requested target is inconsistent.");
end
expectedCurrent_m = staticInner_m + value.requestedRackTravel_m * ...
    value.steeringSystemIdentity.rackAxisDirection;
if max(abs(value.tieRodInboardCurrent_m-expectedCurrent_m)) > tolerance_m
    invalid("Tie-rod inboard motion contradicts rack translation.");
end

try
    fsd.kinematics.validateKinematicResult(value.rackZeroKinematicResult);
catch cause
    exception = MException("fsd:kinematics:InvalidSteeringCornerResult", ...
        "rackZeroKinematicResult is invalid.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
if ~isequal(value.rackZeroKinematicResult.geometryIdentity, ...
        expectedIdentity) || ...
        abs(value.rackZeroKinematicResult.requestedWheelTravel_m - ...
        value.requestedWheelTravel_m) > tolerance_m
    invalid("Rack-zero reference does not match the corner target.");
end
if value.converged && ~value.rackZeroKinematicResult.converged
    invalid("A converged steering corner requires a converged rack-zero reference.");
end

validateDiagnostics(value.diagnostics, value.status, value.converged);
validateContact(value, expectedIdentity, tolerance_m);
if value.converged
    if string(value.status) ~= "CONVERGED" || ...
            strlength(string(value.failureReason)) ~= 0 || ...
            ~isFiniteScalar(value.achievedWheelTravel_m) || ...
            abs(value.achievedWheelTravel_m-value.requestedWheelTravel_m) > ...
            tolerance_m || ...
            value.achievedRackTravel_m ~= value.requestedRackTravel_m || ...
            ~isFinitePoint(value.wheelAxis) || ~isFiniteScalar(value.camber_rad)
        invalid("Converged steering payload contradicts its target.");
    end
    fsd.kinematics.validateSuspensionState( ...
        value.state, expectedIdentity, "FINITE");
    validateFinitePoseAndConstraints(value, expectedIdentity, ...
        staticInner_m, expectedCurrent_m, tolerance_m);
else
    if ~ismember(string(value.status), ["NO_CONVERGENCE","NOT_ATTEMPTED"]) || ...
            strlength(string(value.failureReason)) == 0 || ...
            string(value.failureReason) ~= string(value.diagnostics.message) || ...
            ~isnan(value.achievedWheelTravel_m) || ...
            ~isnan(value.achievedRackTravel_m) || ...
            ~all(isnan(value.wheelAxis)) || ~isnan(value.camber_rad)
        invalid("Failed steering payload is inconsistent.");
    end
    fsd.kinematics.validateSuspensionState( ...
        value.state, expectedIdentity, "NAN");
    validateFailedPose(value.uprightPose, expectedIdentity, tolerance_m);
end
isValid = true;
end

function validateFinitePoseAndConstraints(value, identity, ...
        staticInner_m, currentInner_m, tolerance_m)
ids = string(value.cornerId) + "_" + ...
    ["UBJ";"LBJ";"TIE_ROD_OUTBOARD";"WHEEL_CENTER";"CONTACT_PATCH"];
staticMoving_m = identityPoints(identity, ids);
wheelCenterStatic_m = staticMoving_m(4,:);
pose = value.uprightPose;
validatePoseShape(pose, wheelCenterStatic_m, tolerance_m, true);
expectedRotation = fsd.geometry.rotationVectorToMatrix(pose.rotationVector_rad);
expectedPoints_m = fsd.geometry.transformPointsRigid(staticMoving_m, ...
    wheelCenterStatic_m, pose.translation_m, pose.rotationMatrix);
expectedAxis = (pose.rotationMatrix*identity.wheelAxis(:))';
expectedAxis = expectedAxis/norm(expectedAxis);
expectedTravel_m = expectedPoints_m(4,3)-wheelCenterStatic_m(3);
expectedCamber_rad = fsd.kinematics.camberFromWheelAxis( ...
    expectedAxis, value.cornerId);
if max(abs(expectedRotation-pose.rotationMatrix), [], "all") > tolerance_m || ...
        max(abs(expectedPoints_m-value.state.xyz_m), [], "all") > tolerance_m || ...
        max(abs(expectedAxis-value.wheelAxis)) > tolerance_m || ...
        abs(expectedTravel_m-value.achievedWheelTravel_m) > tolerance_m || ...
        abs(expectedCamber_rad-value.camber_rad) > tolerance_m
    invalid("Steering pose, state, wheel axis, travel or camber disagree.");
end
fixedIds = string(value.cornerId) + "_" + ...
    ["UCA_FWD_CHASSIS";"UCA_AFT_CHASSIS"; ...
    "LCA_FWD_CHASSIS";"LCA_AFT_CHASSIS"];
fixed_m = identityPoints(identity, fixedIds);
staticJoint_m = [staticMoving_m(1,:);staticMoving_m(1,:); ...
    staticMoving_m(2,:);staticMoving_m(2,:)];
currentJoint_m = [value.state.ubj_m;value.state.ubj_m; ...
    value.state.lbj_m;value.state.lbj_m];
if any(abs(vecnorm(currentJoint_m-fixed_m,2,2) - ...
        vecnorm(staticJoint_m-fixed_m,2,2)) > tolerance_m) || ...
        abs(norm(value.state.tieRodOutboard_m-currentInner_m) - ...
        norm(staticMoving_m(3,:)-staticInner_m)) > tolerance_m
    invalid("Steering state violates a rigid-link constraint.");
end
end

function validateFailedPose(pose, identity, tolerance_m)
wheelCenterStatic_m = identityPoint(identity, ...
    string(identity.cornerId)+"_WHEEL_CENTER");
validatePoseShape(pose, wheelCenterStatic_m, tolerance_m, false);
end

function validatePoseShape(pose, wheelCenterStatic_m, tolerance_m, finitePayload)
required = ["referencePointStatic_m","translation_m", ...
    "rotationVector_rad","rotationMatrix"];
if ~isstruct(pose) || ~isscalar(pose) || any(~isfield(pose,required)) || ...
        ~isFinitePoint(pose.referencePointStatic_m) || ...
        ~isnumeric(pose.translation_m) || ~isequal(size(pose.translation_m),[1,3]) || ...
        ~isnumeric(pose.rotationVector_rad) || ...
        ~isequal(size(pose.rotationVector_rad),[1,3]) || ...
        ~isnumeric(pose.rotationMatrix) || ~isequal(size(pose.rotationMatrix),[3,3]) || ...
        max(abs(pose.referencePointStatic_m-wheelCenterStatic_m)) > tolerance_m
    invalid("Steering upright pose has an invalid contract.");
end
if finitePayload
    if any(~isfinite(pose.translation_m)) || ...
            any(~isfinite(pose.rotationVector_rad)) || ...
            any(~isfinite(pose.rotationMatrix),"all")
        invalid("Converged steering pose must be finite.");
    end
elseif ~all(isnan(pose.translation_m)) || ...
        ~all(isnan(pose.rotationVector_rad)) || ...
        ~all(isnan(pose.rotationMatrix),"all")
    invalid("Failed steering pose must use NaN moving fields.");
end
end

function validateDiagnostics(value, status, converged)
required = ["solver","toolbox","attempted","constraintIds", ...
    "lengthErrors_m","maxConstraintError_m","residualVector", ...
    "residualNorm","maxResidual","exitFlag","iterations", ...
    "functionEvaluations","continuationSteps","message"];
expectedIds = ["UCA_FWD";"UCA_AFT";"LCA_FWD";"LCA_AFT";"TIE_ROD"];
if ~isstruct(value) || ~isscalar(value) || any(~isfield(value,required)) || ...
        ~isTextScalar(value.solver) || ~isTextScalar(value.toolbox) || ...
        ~isTextScalar(value.message) || ...
        ~islogical(value.attempted) || ~isscalar(value.attempted) || ...
        ~isstring(value.constraintIds) || ...
        ~isequal(value.constraintIds,expectedIds) || ...
        ~isnumeric(value.lengthErrors_m) || ~isreal(value.lengthErrors_m) || ...
        ~isequal(size(value.lengthErrors_m),[5,1]) || ...
        ~isnumeric(value.residualVector) || ~isreal(value.residualVector) || ...
        ~isequal(size(value.residualVector),[5,1]) || ...
        ~isRealScalar(value.maxConstraintError_m) || ...
        ~isRealScalar(value.residualNorm) || ...
        ~isRealScalar(value.maxResidual) || ...
        ~isRealScalar(value.exitFlag) || ...
        ~isNonnegativeFiniteScalar(value.iterations) || ...
        ~isNonnegativeFiniteScalar(value.functionEvaluations) || ...
        ~isNonnegativeFiniteScalar(value.continuationSteps) || ...
        value.attempted ~= (string(status) ~= "NOT_ATTEMPTED") || ...
        (converged && ~value.attempted)
    invalid("Steering diagnostics have an invalid contract.");
end
if ~value.attempted && (value.iterations ~= 0 || ...
        value.functionEvaluations ~= 0 || value.continuationSteps ~= 0 || ...
        value.exitFlag ~= 0)
    invalid("NOT_ATTEMPTED steering diagnostics report solver activity.");
end
end

function points_m = identityPoints(identity, ids)
points_m = zeros(numel(ids),3);
for index = 1:numel(ids)
    points_m(index,:) = identityPoint(identity,ids(index));
end
end

function [geometryIdentity, staticInner_m] = identityForCorner(identity, cornerId)
if cornerId == "FL"
    geometryIdentity = identity.frontAxleIdentity.leftGeometryIdentity;
    staticInner_m = identity.leftInnerStatic_m;
elseif cornerId == "FR"
    geometryIdentity = identity.frontAxleIdentity.rightGeometryIdentity;
    staticInner_m = identity.rightInnerStatic_m;
else
    invalid("SteeringCornerResult cornerId must be FL or FR.");
end
end

function validateContact(value, identity, tolerance_m)
contact = value.geometricContact;
required = ["status", "point_m", "geometricRadius_m", "diagnostic"];
if ~isstruct(contact) || ~isscalar(contact) || any(~isfield(contact, required)) || ...
        ~isnumeric(contact.point_m) || ~isreal(contact.point_m) || ...
        ~isequal(size(contact.point_m), [1,3]) || ...
        ~isnumeric(contact.geometricRadius_m) || ...
        ~isscalar(contact.geometricRadius_m)
    invalid("Geometric contact has an invalid schema.");
end
if value.converged
    wheelCenterStatic_m = identityPoint(identity, ...
        string(value.cornerId)+"_WHEEL_CENTER");
    contactStatic_m = identityPoint(identity, ...
        string(value.cornerId)+"_CONTACT_PATCH");
    radius_m = norm(contactStatic_m-wheelCenterStatic_m);
    expected = fsd.geometry.geometricWheelContact( ...
        value.state.wheelCenter_m, value.wheelAxis, radius_m);
    if string(contact.status) ~= string(expected.status) || ...
            abs(contact.geometricRadius_m-radius_m) > tolerance_m || ...
            max(abs(contact.point_m-expected.point_m)) > tolerance_m || ...
            string(contact.diagnostic) ~= string(expected.diagnostic)
        invalid("Geometric contact contradicts wheel geometry.");
    end
else
    if string(contact.status) ~= "KINEMATICS_NOT_CONVERGED" || ...
            ~all(isnan(contact.point_m)) || ...
            ~isnan(contact.geometricRadius_m) || ...
            string(contact.diagnostic) ~= string(value.failureReason)
        invalid("Failed steering contact payload is inconsistent.");
    end
end
end

function point_m = identityPoint(identity, id)
row = identity.hardpointIds == id;
if nnz(row) ~= 1
    invalid("Geometry identity is missing a required hardpoint.");
end
point_m = identity.hardpointXyz_m(row,:);
end

function value = comparisonTolerance(reference)
tolerances = fsd.model.numericTolerances();
value = 10*(tolerances.AbsTol_m + ...
    tolerances.RelTol*max([abs(reference(:));1]));
end

function tf = isFiniteScalar(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && isfinite(value);
end

function tf = isFinitePoint(value)
tf = isnumeric(value) && isreal(value) && ...
    isequal(size(value), [1,3]) && all(isfinite(value));
end

function tf = isRealScalar(value)
tf = isnumeric(value) && isreal(value) && isscalar(value);
end

function tf = isNonnegativeFiniteScalar(value)
tf = isRealScalar(value) && isfinite(value) && value >= 0;
end

function tf = isTextScalar(value)
tf = (ischar(value) && isrow(value)) || ...
    (isstring(value) && isscalar(value) && ~ismissing(value));
end

function invalid(message)
error("fsd:kinematics:InvalidSteeringCornerResult", message);
end
