function isValid = validateAxleRollResult(result)
%VALIDATEAXLEROLLRESULT Validate a v0.6 body-roll closure result.

required = ["schemaVersion", "kind", "axleIdentity", ...
    "requestedBodyRollAngle_rad", "requestedAxleHeave_m", ...
    "achievedBodyRollAngle_rad", "achievedAxleHeave_m", ...
    "wheelTravel_m", "wheelTravelDifferential_m", "axleTravelResult", ...
    "leftGeometricContact", "rightGeometricContact", "roadFrame", ...
    "targetRoadLine", "solvedContactRoadLine", "closureResidual_m", ...
    "roadAngleError_rad", "converged", "status", "failureReason", ...
    "diagnostics", "elapsedTime_s"];
if ~isstruct(result) || ~isscalar(result) || ...
        ~all(isfield(result, required)) || ...
        string(result.schemaVersion) ~= "0.6.0" || ...
        string(result.kind) ~= "AxleRollResult" || ...
        ~isFiniteScalar(result.requestedBodyRollAngle_rad) || ...
        abs(result.requestedBodyRollAngle_rad) >= pi/2 || ...
        ~isFiniteScalar(result.requestedAxleHeave_m) || ...
        ~islogical(result.converged) || ~isscalar(result.converged) || ...
        ~isFiniteScalar(result.elapsedTime_s) || result.elapsedTime_s < 0
    invalid("AxleRollResult has an invalid aggregate contract.");
end
try
    fsd.model.validateAxleIdentity(result.axleIdentity);
catch cause
    exception = MException("fsd:kinematics:InvalidAxleRollResult", ...
        "AxleRollResult contains an invalid axle identity.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
validateDiagnostics(result.diagnostics);
if result.converged
    validateConverged(result);
else
    validateFailed(result);
end
isValid = true;
end

function validateConverged(result)
if string(result.status) ~= "CONVERGED" || ...
        strlength(string(result.failureReason)) ~= 0 || ...
        ~isFiniteScalar(result.achievedBodyRollAngle_rad) || ...
        ~isFiniteScalar(result.achievedAxleHeave_m) || ...
        result.achievedBodyRollAngle_rad ~= ...
        result.requestedBodyRollAngle_rad || ...
        result.achievedAxleHeave_m ~= result.requestedAxleHeave_m || ...
        ~isnumeric(result.wheelTravel_m) || ...
        ~isequal(size(result.wheelTravel_m), [1,2]) || ...
        any(~isfinite(result.wheelTravel_m)) || ...
        ~isFiniteScalar(result.wheelTravelDifferential_m) || ...
        ~isFiniteScalar(result.closureResidual_m) || ...
        ~isFiniteScalar(result.roadAngleError_rad)
    invalid("A converged AxleRollResult must publish finite consistent data.");
end
try
    fsd.kinematics.validateAxleTravelResult(result.axleTravelResult);
catch cause
    exception = MException("fsd:kinematics:InvalidAxleRollResult", ...
        "AxleRollResult contains an invalid axle travel result.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
if ~result.axleTravelResult.converged || ...
        ~isequal(result.axleTravelResult.axleIdentity, result.axleIdentity) || ...
        ~isequal(result.axleTravelResult.requestedWheelTravel_m, ...
        result.wheelTravel_m) || ...
        abs(mean(result.wheelTravel_m) - result.requestedAxleHeave_m) > ...
        tolerance(result.wheelTravel_m) || ...
        abs(result.wheelTravelDifferential_m - ...
        diffFlipped(result.wheelTravel_m)) > tolerance(result.wheelTravel_m)
    invalid("Axle roll wheel travels contradict the closure contract.");
end
leftExpected = contactFromIdentity(result.axleIdentity.leftGeometryIdentity, ...
    result.axleTravelResult.leftResult);
rightExpected = contactFromIdentity(result.axleIdentity.rightGeometryIdentity, ...
    result.axleTravelResult.rightResult);
validateContact(result.leftGeometricContact, leftExpected);
validateContact(result.rightGeometricContact, rightExpected);
expectedFrame = fsd.geometry.bodyRollRoadFrame( ...
    result.requestedBodyRollAngle_rad);
expectedSolved = fsd.geometry.roadLineFromContacts( ...
    leftExpected.point_m, rightExpected.point_m);
expectedTarget = fsd.geometry.roadLineFromBodyRoll( ...
    result.requestedBodyRollAngle_rad, ...
    0.5 * (leftExpected.point_m(2:3) + rightExpected.point_m(2:3)));
if ~isequal(result.roadFrame, expectedFrame) || ...
        ~sameRoadLine(result.solvedContactRoadLine, expectedSolved) || ...
        ~sameRoadLine(result.targetRoadLine, expectedTarget)
    invalid("Axle roll road representations contradict its contacts.");
end
expectedResidual = fsd.geometry.roadClosureResidual( ...
    result.requestedBodyRollAngle_rad, ...
    leftExpected.point_m, rightExpected.point_m);
crossValue = expectedFrame.direction_yz(1) * ...
    expectedSolved.direction_yz(2) - expectedFrame.direction_yz(2) * ...
    expectedSolved.direction_yz(1);
expectedAngle = atan2(crossValue, dot(expectedFrame.direction_yz, ...
    expectedSolved.direction_yz));
if abs(result.closureResidual_m - expectedResidual) > ...
        tolerance([result.closureResidual_m, expectedResidual]) || ...
        abs(result.roadAngleError_rad - expectedAngle) > ...
        10 * result.diagnostics.angleTolerance_rad || ...
        abs(expectedResidual) > result.diagnostics.residualTolerance_m || ...
        abs(expectedAngle) > result.diagnostics.angleTolerance_rad
    invalid("Axle roll closure residual or angle is inconsistent.");
end
end

function validateFailed(result)
allowed = ["NOT_ATTEMPTED", "ROOT_NOT_BRACKETED", ...
    "KINEMATIC_NONCONVERGENCE", "SCALAR_NO_CONVERGENCE", ...
    "CONTACT_DEGENERATE", "COINCIDENT_CONTACTS", ...
    "INVERTED_CONTACT_ORDER"];
if ~ismember(string(result.status), allowed) || ...
        strlength(string(result.failureReason)) == 0 || ...
        ~isnan(result.achievedBodyRollAngle_rad) || ...
        ~isnan(result.achievedAxleHeave_m) || ...
        ~all(isnan(result.wheelTravel_m)) || ...
        ~isnan(result.wheelTravelDifferential_m) || ...
        ~isnan(result.closureResidual_m) || ...
        ~isnan(result.roadAngleError_rad) || ...
        ~isempty(fieldnames(result.axleTravelResult)) || ...
        ~all(isnan(result.leftGeometricContact.point_m)) || ...
        ~all(isnan(result.rightGeometricContact.point_m))
    invalid("A failed AxleRollResult must not publish valid state metrics.");
end
end

function validateDiagnostics(value)
required = ["solver", "attempted", "stage", "continuationStep", ...
    "attemptedBodyRollAngle_rad", "attemptedAxleHeave_m", ...
    "initialDelta_m", "bracket_m", "bracketExpansions", ...
    "rootIterations", "rootFunctionEvaluations", "rootExitFlag", ...
    "kinematicEvaluations", "residual_m", "lastLeftStatus", ...
    "lastRightStatus", "residualTolerance_m", "angleTolerance_rad", ...
    "objectiveRequests", "cacheHits", "validEvaluationCount", ...
    "invalidEvaluationCount", "boundaryRefinements", ...
    "bracketElapsedTime_s", "rootElapsedTime_s", ...
    "negativeBoundaryEncountered", "positiveBoundaryEncountered", ...
    "negativeBoundaryExpansion", "positiveBoundaryExpansion", ...
    "bracketSelectionPolicy", "message", "path"];
if ~isstruct(value) || ~isscalar(value) || ~all(isfield(value, required)) || ...
        ~islogical(value.attempted) || ~isscalar(value.attempted)
    invalid("Axle roll diagnostics have an invalid contract.");
end
counts = [value.kinematicEvaluations, value.objectiveRequests, ...
    value.cacheHits, value.validEvaluationCount, ...
    value.invalidEvaluationCount, value.boundaryRefinements];
if any(~isfinite(counts)) || any(counts < 0) || ...
        value.kinematicEvaluations ~= ...
        value.validEvaluationCount+value.invalidEvaluationCount || ...
        value.objectiveRequests ~= value.kinematicEvaluations+value.cacheHits || ...
        ~isFiniteNonnegativeScalar(value.bracketElapsedTime_s) || ...
        ~isFiniteNonnegativeScalar(value.rootElapsedTime_s)
    invalid("Axle roll diagnostic counters are inconsistent.");
end
if ~islogical(value.negativeBoundaryEncountered) || ...
        ~isscalar(value.negativeBoundaryEncountered) || ...
        ~islogical(value.positiveBoundaryEncountered) || ...
        ~isscalar(value.positiveBoundaryEncountered) || ...
        ~isFiniteNonnegativeScalar(value.negativeBoundaryExpansion) || ...
        ~isFiniteNonnegativeScalar(value.positiveBoundaryExpansion) || ...
        value.negativeBoundaryEncountered ~= ...
        (value.negativeBoundaryExpansion > 0) || ...
        value.positiveBoundaryEncountered ~= ...
        (value.positiveBoundaryExpansion > 0) || ...
        string(value.bracketSelectionPolicy) ~= ...
        "nearest-valid-adjacent-to-previous-root"
    invalid("Axle roll bracket diagnostics are inconsistent.");
end
validatePathDiagnostics(value.path);
end

function validatePathDiagnostics(value)
required = ["scalarSolves", "heaveStates", "rollStates", ...
    "uniqueFunctionEvaluations", "cornerSolves", "objectiveRequests", ...
    "cacheHits", "boundaryRefinements", "bracketElapsedTime_s", ...
    "rootElapsedTime_s"];
if ~isstruct(value) || ~isscalar(value) || ~all(isfield(value, required))
    invalid("Axle roll path diagnostics have an invalid contract.");
end
numbers = struct2array(value);
if any(~isfinite(numbers)) || any(numbers < 0) || ...
        value.scalarSolves ~= value.heaveStates+value.rollStates || ...
        value.cornerSolves ~= 2*value.uniqueFunctionEvaluations || ...
        value.objectiveRequests ~= ...
        value.uniqueFunctionEvaluations+value.cacheHits
    invalid("Axle roll path diagnostic counters are inconsistent.");
end
end

function expected = contactFromIdentity(identity, result)
centerStatic = identityPoint(identity, ...
    string(identity.cornerId) + "_WHEEL_CENTER");
datum = identityPoint(identity, ...
    string(identity.cornerId) + "_CONTACT_PATCH");
radius_m = norm(datum - centerStatic);
ideal = fsd.geometry.geometricWheelContact( ...
    result.state.wheelCenter_m, result.wheelAxis, radius_m);
expected = struct("status", string(ideal.status), ...
    "point_m", double(ideal.point_m), "geometricRadius_m", radius_m, ...
    "diagnostic", string(ideal.diagnostic));
end

function point = identityPoint(identity, id)
point = identity.hardpointXyz_m(identity.hardpointIds == id, :);
end

function validateContact(actual, expected)
required = ["status", "point_m", "geometricRadius_m", "diagnostic"];
if ~isstruct(actual) || ~isscalar(actual) || ~all(isfield(actual, required)) || ...
        string(actual.status) ~= "FINITE" || ...
        max(abs(actual.point_m - expected.point_m)) > ...
        tolerance(expected.point_m) || ...
        abs(actual.geometricRadius_m - expected.geometricRadius_m) > ...
        tolerance(expected.geometricRadius_m)
    invalid("Axle roll contact contradicts its kinematic state.");
end
end

function tf = sameRoadLine(first, second)
tf = isstruct(first) && isstruct(second) && ...
    string(first.status) == "FINITE" && string(second.status) == "FINITE" && ...
    max(abs(first.coefficients - second.coefficients)) <= ...
    tolerance(second.coefficients) && ...
    max(abs(first.direction_yz - second.direction_yz)) <= ...
    tolerance(second.direction_yz);
end

function value = diffFlipped(travel)
value = travel(1) - travel(2);
end

function value = tolerance(reference)
t = fsd.model.numericTolerances();
value = 10 * (t.AbsTol_m + t.RelTol * max([abs(reference(:)); 1]));
end

function tf = isFiniteScalar(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && isfinite(value);
end

function tf = isFiniteNonnegativeScalar(value)
tf = isFiniteScalar(value) && value >= 0;
end

function invalid(message)
error("fsd:kinematics:InvalidAxleRollResult", message);
end
