function isValid = validateActuationSweepResult(sweep, actuation)
%VALIDATEACTUATIONSWEEPRESULT Validate a complete ordered actuation sweep.

if nargin < 2
    actuation = [];
end
if ~isstruct(sweep) || ~isscalar(sweep)
    invalid("ActuationSweepResult must be a scalar struct.");
end
required = ["schemaVersion", "kind", "actuationIdentity", ...
    "sourceGeometryIdentity", "sourceSweepKind", ...
    "requestedWheelTravel_m", "achievedWheelTravel_m", ...
    "rockerAngle_rad", "damperLength_m", "damperCompression_m", ...
    "conditioning", "converged", "allConverged", ...
    "elapsedTime_s", "performance", "results"];
if any(~isfield(sweep, required)) || ...
        string(sweep.schemaVersion) ~= "0.7.0" || ...
        string(sweep.kind) ~= "ActuationSweepResult" || ...
        string(sweep.sourceSweepKind) ~= "BumpSweepResult"
    invalid("Unsupported or incomplete ActuationSweepResult schema.");
end
try
    fsd.model.validateActuationIdentity(sweep.actuationIdentity);
catch cause
    exception = MException("fsd:kinematics:InvalidActuationSweepResult", ...
        "Sweep contains an invalid actuation identity.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
if ~isempty(actuation) && ...
        ~isequal(sweep.actuationIdentity, actuation.identity)
    error("fsd:kinematics:ActuationIdentityMismatch", ...
        "Actuation sweep belongs to another ActuationGeometry.");
end
count = numel(sweep.requestedWheelTravel_m);
numericColumns = ["requestedWheelTravel_m", "achievedWheelTravel_m", ...
    "rockerAngle_rad", "damperLength_m", "damperCompression_m", ...
    "conditioning"];
for index = 1:numel(numericColumns)
    value = sweep.(numericColumns(index));
    if ~isnumeric(value) || ~isreal(value) || ...
            ~isequal(size(value), [count, 1])
        invalid("Sweep numeric arrays must be N-by-1.");
    end
end
if count == 0 || any(~isfinite(sweep.requestedWheelTravel_m)) || ...
        ~islogical(sweep.converged) || ...
        ~isequal(size(sweep.converged), [count,1]) || ...
        ~islogical(sweep.allConverged) || ~isscalar(sweep.allConverged) || ...
        ~isnumeric(sweep.elapsedTime_s) || ~isscalar(sweep.elapsedTime_s) || ...
        ~isfinite(sweep.elapsedTime_s) || sweep.elapsedTime_s < 0 || ...
        ~isstruct(sweep.performance) || ~isscalar(sweep.performance) || ...
        ~all(isfield(sweep.performance, ...
        ["rockerClosureSolveCount", "notAttemptedCount"])) || ...
        ~isNonnegativeInteger(sweep.performance.rockerClosureSolveCount) || ...
        ~isNonnegativeInteger(sweep.performance.notAttemptedCount) || ...
        ~isstruct(sweep.results) || ~iscolumn(sweep.results) || ...
        numel(sweep.results) ~= count
    invalid("Sweep fields have invalid types or dimensions.");
end
expectedReference_rad = 0;
continuationAvailable = true;
for index = 1:count
    fsd.kinematics.validateActuationResult(sweep.results(index), actuation);
    if ~isequal(sweep.results(index).actuationIdentity, ...
            sweep.actuationIdentity)
        invalid("Sweep mixes actuation identities.");
    end
    current = sweep.results(index);
    if ~continuationAvailable
        if string(current.status) ~= "NOT_ATTEMPTED" || ...
                current.diagnostics.attempted || ...
                isfinite(current.diagnostics.referenceRockerAngle_rad)
            invalid("States after a continuation failure must be NOT_ATTEMPTED.");
        end
    else
        if current.diagnostics.attempted && ...
                current.diagnostics.referenceRockerAngle_rad ~= ...
                expectedReference_rad
            invalid("Sweep continuation reference does not match the previous branch.");
        end
        if current.converged
            expectedReference_rad = current.rockerAngle_rad;
        else
            continuationAvailable = false;
        end
    end
end
attempted = arrayfun(@(item) item.diagnostics.attempted, sweep.results);
if ~isequal(sweep.sourceGeometryIdentity, ...
        sweep.actuationIdentity.cornerGeometryIdentity) || ...
        ~isequal(sweep.requestedWheelTravel_m, reshape( ...
        [sweep.results.sourceRequestedWheelTravel_m], [], 1)) || ...
        ~isequaln(sweep.achievedWheelTravel_m, reshape( ...
        [sweep.results.sourceAchievedWheelTravel_m], [], 1)) || ...
        ~isequaln(sweep.rockerAngle_rad, reshape( ...
        [sweep.results.rockerAngle_rad], [], 1)) || ...
        ~isequaln(sweep.damperLength_m, reshape( ...
        [sweep.results.damperLength_m], [], 1)) || ...
        ~isequaln(sweep.damperCompression_m, reshape( ...
        [sweep.results.damperCompression_m], [], 1)) || ...
        ~isequaln(sweep.conditioning, reshape( ...
        [sweep.results.conditioning], [], 1)) || ...
        ~isequal(sweep.converged, reshape( ...
        [sweep.results.converged], [], 1)) || ...
        sweep.allConverged ~= all(sweep.converged) || ...
        sweep.performance.rockerClosureSolveCount ~= ...
        sum(attempted) || ...
        sweep.performance.notAttemptedCount ~= ...
        nnz(string({sweep.results.status}) == "NOT_ATTEMPTED")
    invalid("Sweep aggregate fields contradict contained results.");
end
isValid = true;
end

function invalid(message, varargin)
error("fsd:kinematics:InvalidActuationSweepResult", message, varargin{:});
end

function tf = isNonnegativeInteger(value)
tf = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= 0 && value == round(value);
end
