function isValid = validateAxleTravelSweepResult(sweep)
%VALIDATEAXLETRAVELSWEEPRESULT Validate a v0.6 asymmetric axle sweep.

required = ["schemaVersion", "kind", "axleIdentity", ...
    "requestedWheelTravel_m", "converged", "leftConverged", ...
    "rightConverged", "status", "allConverged", "elapsedTime_s", ...
    "leftSweep", "rightSweep", "results"];
if ~isstruct(sweep) || ~isscalar(sweep) || ...
        ~all(isfield(sweep, required)) || ...
        string(sweep.schemaVersion) ~= "0.6.0" || ...
        string(sweep.kind) ~= "AxleTravelSweepResult" || ...
        ~isnumeric(sweep.requestedWheelTravel_m) || ...
        ~isreal(sweep.requestedWheelTravel_m) || ...
        size(sweep.requestedWheelTravel_m, 2) ~= 2 || ...
        isempty(sweep.requestedWheelTravel_m) || ...
        any(~isfinite(sweep.requestedWheelTravel_m), "all") || ...
        ~islogical(sweep.converged) || ~iscolumn(sweep.converged) || ...
        ~islogical(sweep.leftConverged) || ...
        ~iscolumn(sweep.leftConverged) || ...
        ~islogical(sweep.rightConverged) || ...
        ~iscolumn(sweep.rightConverged) || ...
        ~isstring(sweep.status) || ~iscolumn(sweep.status) || ...
        ~islogical(sweep.allConverged) || ~isscalar(sweep.allConverged) || ...
        ~isnumeric(sweep.elapsedTime_s) || ~isreal(sweep.elapsedTime_s) || ...
        ~isscalar(sweep.elapsedTime_s) || ~isfinite(sweep.elapsedTime_s) || ...
        sweep.elapsedTime_s < 0
    invalid("AxleTravelSweepResult has an invalid aggregate contract.");
end
count = size(sweep.requestedWheelTravel_m, 1);
if numel(sweep.converged) ~= count || ...
        numel(sweep.leftConverged) ~= count || ...
        numel(sweep.rightConverged) ~= count || numel(sweep.status) ~= count
    invalid("Axle travel sweep aggregate arrays have invalid dimensions.");
end
try
    fsd.model.validateAxleIdentity(sweep.axleIdentity);
    fsd.kinematics.validateBumpSweepResult(sweep.leftSweep);
    fsd.kinematics.validateBumpSweepResult(sweep.rightSweep);
catch cause
    exception = MException("fsd:kinematics:InvalidAxleTravelSweepResult", ...
        "Axle travel sweep contains invalid component contracts.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
if ~isstruct(sweep.results) || ~iscolumn(sweep.results) || ...
        numel(sweep.results) ~= count || ...
        ~isequal(sweep.leftSweep.requestedWheelTravel_m, ...
        sweep.requestedWheelTravel_m(:,1)) || ...
        ~isequal(sweep.rightSweep.requestedWheelTravel_m, ...
        sweep.requestedWheelTravel_m(:,2)) || ...
        ~isequal(sweep.leftSweep.geometryIdentity, ...
        sweep.axleIdentity.leftGeometryIdentity) || ...
        ~isequal(sweep.rightSweep.geometryIdentity, ...
        sweep.axleIdentity.rightGeometryIdentity)
    invalid("Axle travel sweep component paths disagree.");
end
for index = 1:count
    fsd.kinematics.validateAxleTravelResult(sweep.results(index));
    if ~isequal(sweep.results(index).axleIdentity, sweep.axleIdentity) || ...
            ~isequal(sweep.results(index).requestedWheelTravel_m, ...
            sweep.requestedWheelTravel_m(index,:))
        invalid("Contained axle travel result does not match its target.");
    end
end
expectedConverged = reshape([sweep.results.converged], [], 1);
expectedLeft = reshape([sweep.results.leftConverged], [], 1);
expectedRight = reshape([sweep.results.rightConverged], [], 1);
expectedStatus = reshape(string({sweep.results.status}), [], 1);
if ~isequal(sweep.converged, expectedConverged) || ...
        ~isequal(sweep.leftConverged, expectedLeft) || ...
        ~isequal(sweep.rightConverged, expectedRight) || ...
        ~isequal(string(sweep.status), expectedStatus) || ...
        sweep.allConverged ~= all(expectedConverged)
    invalid("Axle travel sweep aggregates contradict contained results.");
end
isValid = true;
end

function invalid(message)
error("fsd:kinematics:InvalidAxleTravelSweepResult", message);
end
