function isValid = validateAxleRollSweepResult(sweep)
%VALIDATEAXLEROLLSWEEPRESULT Validate an ordered v0.6 body-roll sweep.

required = ["schemaVersion", "kind", "axleIdentity", ...
    "requestedBodyRollAngle_rad", "requestedAxleHeave_m", ...
    "converged", "status", "allConverged", "elapsedTime_s", ...
    "performance", "results"];
if ~isstruct(sweep) || ~isscalar(sweep) || ...
        ~all(isfield(sweep, required)) || ...
        string(sweep.schemaVersion) ~= "0.6.0" || ...
        string(sweep.kind) ~= "AxleRollSweepResult" || ...
        ~isnumeric(sweep.requestedBodyRollAngle_rad) || ...
        ~iscolumn(sweep.requestedBodyRollAngle_rad) || ...
        isempty(sweep.requestedBodyRollAngle_rad) || ...
        any(~isfinite(sweep.requestedBodyRollAngle_rad)) || ...
        any(abs(sweep.requestedBodyRollAngle_rad) >= pi/2) || ...
        ~isnumeric(sweep.requestedAxleHeave_m) || ...
        ~isscalar(sweep.requestedAxleHeave_m) || ...
        ~isfinite(sweep.requestedAxleHeave_m) || ...
        ~islogical(sweep.converged) || ~iscolumn(sweep.converged) || ...
        numel(sweep.converged) ~= numel(sweep.requestedBodyRollAngle_rad) || ...
        ~isstring(sweep.status) || ~iscolumn(sweep.status) || ...
        numel(sweep.status) ~= numel(sweep.requestedBodyRollAngle_rad) || ...
        ~islogical(sweep.allConverged) || ~isscalar(sweep.allConverged) || ...
        ~isnumeric(sweep.elapsedTime_s) || ~isreal(sweep.elapsedTime_s) || ...
        ~isscalar(sweep.elapsedTime_s) || ~isfinite(sweep.elapsedTime_s) || ...
        sweep.elapsedTime_s < 0 || ...
        ~isstruct(sweep.results) || ~iscolumn(sweep.results) || ...
        numel(sweep.results) ~= numel(sweep.requestedBodyRollAngle_rad)
    invalid("AxleRollSweepResult has an invalid aggregate contract.");
end
validatePerformance(sweep.performance, sweep.results, sweep.elapsedTime_s);
try
    fsd.model.validateAxleIdentity(sweep.axleIdentity);
catch cause
    exception = MException("fsd:kinematics:InvalidAxleRollSweepResult", ...
        "Axle roll sweep contains an invalid axle identity.");
    exception = addCause(exception, cause);
    throwAsCaller(exception);
end
for index = 1:numel(sweep.results)
    fsd.kinematics.validateAxleRollResult(sweep.results(index));
    if ~isequal(sweep.results(index).axleIdentity, sweep.axleIdentity) || ...
            sweep.results(index).requestedBodyRollAngle_rad ~= ...
            sweep.requestedBodyRollAngle_rad(index) || ...
            sweep.results(index).requestedAxleHeave_m ~= ...
            sweep.requestedAxleHeave_m
        invalid("Contained axle roll result does not match its sweep target.");
    end
end
expectedConverged = reshape([sweep.results.converged], [], 1);
expectedStatus = reshape(string({sweep.results.status}), [], 1);
if ~isequal(sweep.converged, expectedConverged) || ...
        ~isequal(string(sweep.status), expectedStatus) || ...
        sweep.allConverged ~= all(expectedConverged)
    invalid("Axle roll sweep aggregates contradict contained results.");
end
isValid = true;
end

function validatePerformance(value, results, elapsed_s)
required = ["wallTime_s", "internalScalarStates", "heaveStates", ...
    "rollStates", "uniqueFunctionEvaluations", "cornerSolves", ...
    "objectiveRequests", "cacheHits", "boundaryRefinements", ...
    "bracketElapsedTime_s", "rootElapsedTime_s"];
if ~isstruct(value) || ~isscalar(value) || ~all(isfield(value, required))
    invalid("Axle roll sweep performance has an invalid contract.");
end
paths = arrayfun(@(result) result.diagnostics.path, results);
expected = [elapsed_s, sum([paths.scalarSolves]), ...
    sum([paths.heaveStates]), sum([paths.rollStates]), ...
    sum([paths.uniqueFunctionEvaluations]), sum([paths.cornerSolves]), ...
    sum([paths.objectiveRequests]), sum([paths.cacheHits]), ...
    sum([paths.boundaryRefinements]), sum([paths.bracketElapsedTime_s]), ...
    sum([paths.rootElapsedTime_s])];
actual = [value.wallTime_s, value.internalScalarStates, value.heaveStates, ...
    value.rollStates, value.uniqueFunctionEvaluations, value.cornerSolves, ...
    value.objectiveRequests, value.cacheHits, value.boundaryRefinements, ...
    value.bracketElapsedTime_s, value.rootElapsedTime_s];
if any(~isfinite(actual)) || any(actual < 0) || ~isequal(actual, expected) || ...
        value.cornerSolves ~= 2*value.uniqueFunctionEvaluations || ...
        value.internalScalarStates ~= value.heaveStates+value.rollStates
    invalid("Axle roll sweep performance contradicts contained diagnostics.");
end
end

function invalid(message)
error("fsd:kinematics:InvalidAxleRollSweepResult", message);
end
